### ISSUE TITLE
Channel grouping like in NewPipe with "play all" button and "watched" filter.

### ISSUE THREAD

**Issue by grappas** [libre-tube/LibreTube#1370] opened 2022-09-24 12:52 UTC
### Describe your suggested feature

How I like my youtube client:

Group channels as "music", "podcasts", etc...

Then I would like to "play all" so that I could listen it on my earphones. 

But I don't want to listen twice the same videos thus filter "watched" would be useful for that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-24 17:01
Dupe of #1267, not planned unless the API supports it

**Closed by Bnyro** 2022-09-24 17:01 UTC
Labels: enhancement
