### ISSUE TITLE
Error when double-clicking to X

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3386] opened 2023-03-25 13:42 UTC
### Steps to reproduce

1Double-click X at the same time to close the player
2.Error

### Expected behavior

There should be no error.

### Actual behavior

A)  java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:127)
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:299)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:59)
	at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:4403)
	at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:1206)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:3679)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:3472)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:3481)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1378)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5440)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    

B)java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:14)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:25)
	at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:73)
	at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:5)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:276)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:6)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:29)
	at androidx.constraintlayout.motion.widget.MotionLayout.dispatchDraw(MotionLayout.java:63)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.updateDisplayListIfDirty(View.java:22753)
	at android.view.View.draw(View.java:23628)
	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
	at android.view.View.draw(View.java:23901)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1378)
	at android.view.View.updateDisplayListIfDirty(View.java:22767)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5440)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5148)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    
    

### LibreTube version

0.13.0 Latest debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/227720700-6fa8aeea-aaf1-464c-b4a8-2a45ea48a148.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-26 08:31
Duplicate of #3372

**Closed by Bnyro** 2023-03-26 08:32 UTC
Labels: bug
