### ISSUE TITLE
Getting Crashed Upon Clicking Library Button 

### ISSUE THREAD

**Issue by vjdan** [libre-tube/LibreTube#4501] opened 2023-08-15 21:40 UTC
### Steps to reproduce

1. Open App
2. Click On Library Button 

### Expected behavior

It should open the user library like watch later playlist etc 

### Actual behavior

Instead it is getting very hard crash. I removed app, cleared cash, cleared data but still happening. Below shared error code:

java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    

### LibreTube version

0.17.1

### Android version

Android 13

### Other details

java.lang.ArrayIndexOutOfBoundsException: length=4; index=-1
	at com.github.libretube.ui.fragments.LibraryFragment.onViewCreated(SourceFile:377)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:1429)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:92)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:74)
	at androidx.fragment.app.DialogFragment$1.run(SourceFile:22)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-15 21:41
Duplicate of #4491.

**Closed by Bnyro** 2023-08-15 21:41 UTC
Labels: bug

**Comment by vjdan** [comment] 2023-08-15 21:43
> Duplicate of #4491.

Sorry indeed it's been reported already

**Comment by Bnyro** [comment] 2023-08-15 21:50
See https://github.com/libre-tube/LibreTube/issues/4491#issuecomment-1679177440 for how to fix it yourself (don't take that file, export a backup yourself and edit that file). The crash only occurs in very rare situations, so it's not going to be fixed with a new release soon.
