### ISSUE TITLE
Offline video player doesn't show playback notification

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2467] opened 2022-12-21 13:10 UTC
### Steps to reproduce

1. Play a downloaded video

### Expected behavior

A player control notification should pop up.

### Actual behavior

It doesn't

### LibreTube version

0.9.1

### Android version

Android 10, MIUI 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-21 14:01
Dupe of #1467

**Closed by Bnyro** 2022-12-21 14:01 UTC
Labels: bug
