### ISSUE TITLE
[DEBUG APK] App crashes while importing database 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4655] opened 2023-08-28 22:01 UTC
### Steps to reproduce

1. Open the app for first time
2. Click on `Restore`
3. Select backup file

### Expected behavior

Database should be properly exported. 

### Actual behavior

App crashes. 

### LibreTube version

0.17.1 debug

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2023-08-28 22:22
Potentially a duplicate of https://github.com/libre-tube/LibreTube/issues/3427?

**Comment by catgangdev** [comment] 2023-08-29 03:47
I have same in release build... But when I checked back-up files they are empty. No data in there

**Comment by catgangdev** [comment] 2023-08-29 03:47
This error I got when tried to restore that (empty) json backup file



kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: 
	at okio.Okio.JsonDecodingException(SourceFile:1)
	at okio.Okio.JsonDecodingException(SourceFile:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(SourceFile:57)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(SourceFile:13)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(SourceFile:114)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(SourceFile:42)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNextToken(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(SourceFile:45)
	at com.github.libretube.obj.PipedImportPlaylistFile$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.obj.PipedImportPlaylistFile$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio.Okio.decodeByReader(SourceFile:25)
	at okio.Okio.decodeFromStream(SourceFile:15)
	at okio.Path$Companion.importPlaylists(SourceFile:128)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$getPlaylistsFile$1$1$1.invokeSuspend(SourceFile:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f7e9e46, Dispatchers.IO]

**Comment by catgangdev** [comment] 2023-08-29 04:03
It seems whole backup and restore feature broken. I tried to restore playlist from YouTube CSV file it ends with error


java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at okio.Path$Companion.importPlaylists(SourceFile:315)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$getPlaylistsFile$1$1$1.invokeSuspend(SourceFile:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a6416c1, Dispatchers.IO]

**Comment by DerZwergGimli** [comment] 2023-08-30 19:01
Hey i do get a similar error:

I'm trying to import a CSV file from youtube into libretube (btw the exported csv file has approx 5000 rows)

```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at okio.Path$Companion.importPlaylists(SourceFile:315)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$getPlaylistsFile$1$1$1.invokeSuspend(SourceFile:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4982c70, Dispatchers.IO]
    
```

**Comment by Bnyro** [comment] 2023-08-30 19:11
If the Json file is empty, it's a Duplicate of https://github.com/libre-tube/LibreTube/issues/3427.

@DerZwergGimli Your issue is unrelated, please open a new one with a CSV file to reproduce the issue.

**Comment by Bnyro** [comment] 2023-08-31 07:59
Closing as Duplicate of https://github.com/libre-tube/LibreTube/issues/3427

**Closed by Bnyro** 2023-08-31 07:59 UTC
Labels: bug
