### ISSUE TITLE
Cannot control video while comment section is popped up.

### ISSUE THREAD

**Issue by gracie95** [libre-tube/LibreTube#3266] opened 2023-03-07 14:28 UTC
### Steps to reproduce

1. Play a video
2. Open comments section.
3. Try to adjust any behavior to the video.

### Expected behavior

The media button (play, etc.) should appear while press to the video area.

### Actual behavior

That don't work.

### LibreTube version

0.12.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-07 14:45
Duplicate of #2922

**Closed by Bnyro** 2023-03-07 14:45 UTC
Labels: bug
