### ISSUE TITLE
Instant error

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2221] opened 2022-12-04 06:54 UTC
### Steps to reproduce

1.https://piped.video/watch?v=RTvDRh8IvPE&t=141
2.Play the video
3.After a while, an error occurred.

### Expected behavior

It shouldn't have been.

### Actual behavior

com.fasterxml.jackson.databind.JsonMappingException: (was com.google.net.cronet.okhttptransport.CronetTimeoutException) (through reference chain: com.github.libretube.api.obj.Channel["relatedStreams"]->java.util.ArrayList[11])
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:194)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:173)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:118)
	at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:9)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:3)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2211590, Dispatchers.IO]
Caused by: com.google.net.cronet.okhttptransport.CronetTimeoutException
	at com.google.net.cronet.okhttptransport.OkHttpBridgeRequestCallback$CronetBodySource.read(OkHttpBridgeRequestCallback.java:195)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:4)
	at okio.ForwardingSource.read(ForwardingSource.kt:8)
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:1)
	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:14)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
	at java.io.InputStreamReader.read(InputStreamReader.java:180)
	at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:142)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:9)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._finishString(ReaderBasedJsonParser.java:109)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.getText(ReaderBasedJsonParser.java:14)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:1)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:159)
	... 14 more
    

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

When watching the video, the error occurred instant.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment] 2022-12-04 09:45
Works fine for me.

**Comment by Bnyro** [comment] 2022-12-04 11:45
Can't reproduce either.
Apart from that the error message indicates that you were browsing a channel and thus it's not related to the video, hence we'll need a more detailed description on how to reproduce.

**Comment by Dertyiula** [comment] 2022-12-04 12:42
What can I do?

**Comment by Bnyro** [comment] 2022-12-04 17:18
> Can't reproduce either.
> Apart from that the error message indicates that you were browsing a channel and thus it's not related to the video, hence we'll need a more detailed description on how to reproduce.
>
.

**Comment by akano12** [comment] 2022-12-04 18:09
> What can I do?

Can you share more information that could help us face the same error you reported?
Can you try to reproduce the error?
Can you try to reproduce on another device?

**Comment by Dertyiula** [comment] 2022-12-04 18:57
The error does not reoccur.I don't know what to do.Do not repeat the error

**Comment by Bnyro** [comment] 2022-12-05 18:07
No clue how it should be fixed then ...

**Closed by Bnyro** 2022-12-05 18:07 UTC
Labels: bug
