### ISSUE TITLE
channel opening searchbar issue

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1313] opened 2022-09-17 23:09 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/97352673/190879133-0d6458d2-c59f-4031-a0be-49b69d581e62.mp4

### Expected behavior

Channel should open

### Actual behavior

Searchbar opens 

### LibreTube version

0.5.1

### Android version

Android 12 One UI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-18 07:53
dupe of #1312

**Closed by Bnyro** 2022-09-18 07:53 UTC
Labels: bug
