### ISSUE TITLE
Player Notification(Notification action)

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#819] opened 2022-07-18 17:34 UTC
### Describe your suggested feature

![Screenshot_20220718-213125_NewPipe](https://user-images.githubusercontent.com/104249296/179569460-3978767a-390e-4e7e-a7fd-1906c69d8c23.jpg)
![Screenshot_20220718-213108_NewPipe](https://user-images.githubusercontent.com/104249296/179569482-83e5c49e-08f0-4ff5-a123-076821a29acb.jpg)
![Screenshot_20220718-213056_NewPipe](https://user-images.githubusercontent.com/104249296/179569489-ee27df4c-8cef-4931-bc81-6a43edddbc91.jpg)
![Screenshot_20220718-213041_NewPipe](https://user-images.githubusercontent.com/104249296/179569495-a2e347b3-e4c1-4ede-ab7b-6bac545d7265.jpg)
![Screenshot_20220718-213011_NewPipe](https://user-images.githubusercontent.com/104249296/179569506-ce5902b5-7b91-49ed-9393-419a21acf078.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-07-18 17:35
dupe of #636

**Closed by Bnyro** 2022-07-18 17:35 UTC
Labels: enhancement
