### ISSUE TITLE
Player UI hide while user intract with that

### ISSUE THREAD

**Issue by Monirzadeh** [libre-tube/LibreTube#3018] opened 2023-02-10 19:06 UTC
### Steps to reproduce

1. Play a video
2. Tap on that to show progress bar
3. Grab pointer and constantly move that (show a thumbnail from current position)
4. Try to Keep doing that for more than 10 second
5. As you see ui automatic hide after 3 second(default behavior) and you can't move pointer on progress bar more than 3 sec.

### Expected behavior

While you interact with ui specifically  moving pointer(use thumbnail functionality ) ui should not hide. Ui should hide when user finger remove.

### Actual behavior

When you try to move pointer auto hide ui( 3 second) is active and prevent user from continue interact with player (thumbnail functionality) more than that.

### LibreTube version

0.11.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-10 19:09
Duplicate of #2976, already resolved in debug builds :)

**Closed by Bnyro** 2023-02-10 19:09 UTC
Labels: bug
