### ISSUE TITLE
the bad place in ru translation

### ISSUE THREAD

**Issue by Wjxfi** [libre-tube/LibreTube#2409] opened 2022-12-17 00:52 UTC
![292014.jpg](https://user-images.githubusercontent.com/113500363/208214495-8c634ce7-1410-4c33-865b-e71dc4da6c86.jpg)

there is a bad spot above the orange bar. fix it

A friend found this and told me to show you

**Comment by Bnyro** [comment] 2022-12-17 07:37
Dupe of #2275

**Closed by Bnyro** 2022-12-17 07:37 UTC
Labels: bug
