### ISSUE TITLE
Even if home tab is hidden, it still launches home tab on app launch

### ISSUE THREAD

**Issue by MillionsToOne** [libre-tube/LibreTube#3843] opened 2023-05-28 06:26 UTC
### Steps to reproduce

1. Hide home tab from settings
2. Restart app
3. App launches and the bug occurs

### Expected behavior

It should load the following tab that isn't hidden e.g. subscriptions tab

### Actual behavior

Should only open one of the tabs that isn't hidden

### LibreTube version

0.14.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-28 07:21
Duplicate of #3121, see the comments there.

**Closed by Bnyro** 2023-05-28 07:21 UTC
Labels: bug
