### ISSUE TITLE
Add option to separately export playlists

### ISSUE THREAD

**Issue by ticklemyIP** [libre-tube/LibreTube#6351] opened 2024-08-13 19:43 UTC
### Describe your suggested feature

As video playing with the app recently become impossible with the login bot error on every instance many people are looking for a replacement to this app (including me) that is not notoriously unreliable.

One feature to help this process would be an option to export playlists from the app so that users can manually convert this playlist export file or other apps can implement an import feature for it. I recommend .json

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by admntn** [comment] 2024-08-15 13:38
Absolutely in agreement with this request as the app is endlessly failing. Please, at least give us the option to export the Playlist. Json/csv formats, anything than we can possibly re-upload in YouTube again or in any app capable of working at least 50% of times.
I understand the problem is spreading touching the majority of third parties app, not LibreTube only. For this reason the issue should be given more attention and a different priority.
Thanks in advance for your help.

**Comment by shuvashish76** [comment] 2024-08-16 00:33
Relevant issue on NewPipe: https://github.com/TeamNewPipe/NewPipe/issues/11440

**Comment by PhrozenByte** [comment] 2024-08-16 19:02
More or less a duplicate of #5195

Considering that #5195 is by far the most upvoted suggestion and the fact that this is brought up basically any time Piped has substantial issues with YouTube breaking stuff, I feel like that one should at least think about that `priority: low` tag. I truly love LibreTube, it's by far the best UI, but LibreTube really makes it hard to bridge the time till a fix is developed.

**Comment by Bnyro** [comment] 2024-08-24 14:23
I've misread the title when I was initially labeling that issue with priority low.

You already have the possibility to export all your playlists via Settings -> Backup & Restore. There's no common format for that by other YouTube frontends, thus you should ask other projects for adopting the format.

**Closed by Bnyro** 2024-08-24 14:23 UTC
Labels: enhancement, priority: low
