### ISSUE TITLE
Split autoplay options

### ISSUE THREAD

**Issue by gitabekaunt** [libre-tube/LibreTube#2882] opened 2023-01-27 20:42 UTC
### Describe your suggested feature

I'd like autoplay to be split to 2 different options or changed so that autoplay for playlist/queue is on and autoplay outside of that (a normal video) is off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2023-01-27 21:25
Dupe of #1810

**Closed** 2023-01-27 21:29 UTC
Labels: enhancement

**Comment by ThomasLeigh** [comment] 2023-03-16 13:03
It would be of a great help to be able to completely disable video autoplay within the app.

**Comment by ThomasLeigh** [comment] 2023-03-16 17:14
> You can disable autoplay already

Do you mean that I can disable autoplay by using data saving mode? I'd like to be able to disable autoplay but without a need to using data saving mode because it makes video covers/thumbnails hidden and it's important for me to have them still visible.

**Comment by xIUPITERx** [comment] 2023-03-16 17:48
![Screenshot_20230316_184555_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/225708278-f0839d49-10ac-4609-b98d-45ef243eb7e9.png)

**Comment by ThomasLeigh** [comment] 2023-03-16 18:29
> ![Screenshot_20230316_184555_LibreTube Debug.png](https://user-images.githubusercontent.com/97352673/225708278-f0839d49-10ac-4609-b98d-45ef243eb7e9.png)

Thank You for Your interest to help me. What I mean is to be able to disable autoplaying each video I open, not only the next ones. I often just download videos and don't want them to be automatically played. It would be great if there would be no need to pause videos each and every time. I know there is data saving mode which could help, but it also hides videos covers which are important for me to see.
