### ISSUE TITLE
New bug in Settings

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#4244] opened 2023-07-16 18:47 UTC
### Steps to reproduce

1. Go Settings
2. Click Instance

### Expected behavior

No error feedback.

### Actual behavior

App crash.

### LibreTube version

0.16.1

### Android version

13

### Other details

java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{210822d VFED.V... ......ID 0,0-1096,2266 #7f0a0283 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@3d61167, layout:androidx.recyclerview.widget.LinearLayoutManager@cc3509d, context:com.github.libretube.ui.activities.SettingsActivity@10b488b
 at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(SourceFile:29)
 at com.github.libretube.ui.fragments.HomeFragment$loadPlaylists$2.onItemRangeChanged(SourceFile:12)
 at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(SourceFile:19)
 at androidx.preference.Preference.notifyChanged(SourceFile:17)
 at androidx.preference.Preference.setSummaryProvider(SourceFile:3)
 at com.github.libretube.ui.preferences.InstanceSettings.access$initInstancesPref(SourceFile:105)
 at com.github.libretube.ui.preferences.InstanceSettings$initInstancesPref$1.invokeSuspend(Unknown Source:12)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
 at kotlinx.coroutines.UndispatchedCoroutine.afterResume(SourceFile:54)
 at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:32)
 at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
 at androidx.work.Worker$2.run(SourceFile:53)
 at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c95bdf8, Dispatchers.IO]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-16 18:51
Duplicate of #4216

**Closed by Bnyro** 2023-07-16 18:51 UTC
Labels: bug
