### ISSUE TITLE
Very Slow Video Load Up Time

### ISSUE THREAD

**Issue by parasgargexx20** [libre-tube/LibreTube#275] opened 2022-05-21 14:00 UTC
Hi,
I use the kavin.rocks (Official) instance (Indian Instance) and turns out it's pretty slow.I tried to check the speed of load up with multiple 1080 MPEG_4 videos and it's taking atleast 20 seconds or more to load up the video even with a 75 MBPS 3G Wifi Internet.I compared it to YouTube Vanced and it's noticeably faster loads up in like 10 sec or earlier and sometimes rarely 15 at worst which doesn't happen often though to be honest.

**Comment by Bnyro** [comment] 2022-05-21 14:12
We're aware if it and trying out best to fix it, dupe of #231

**Closed by Bnyro** 2022-05-21 14:12 UTC

**Comment by parasgargexx20** [comment] 2022-05-21 14:34
Nice
