### ISSUE TITLE
Crash on a specific channel

### ISSUE THREAD

**Issue by SA-Kasraie** [libre-tube/LibreTube#2839] opened 2023-01-23 10:58 UTC
### Steps to reproduce

1. Search for OpenAI
2. Click on the channel
3. Crash happens

### Expected behavior

Viewing channel without crash.

### Actual behavior

Crash accord.

### LibreTube version

0.11.0 (Not the debug version)

### Android version

Android 11

### Other details

Crash report:

kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 242: Expected string literal but 'null' literal was found at path: $.bannerUrl
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: .....eusercontent.com","bannerUrl":null,"description":"OpenAI’s m.....
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:1)
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:64)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:34)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:7)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:14)
	at org.chromium.net.UploadDataSink.decodeStringElement(UploadDataSink.java:6)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:119)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7460dc6, Dispatchers.Main.immediate]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-23 12:12
Dupe of #2813

**Closed by Bnyro** 2023-01-23 12:12 UTC
Labels: bug
