### ISSUE TITLE
Error when reopening after pressing back button to leave

### ISSUE THREAD

**Issue by elfein727** [libre-tube/LibreTube#1217] opened 2022-09-06 13:46 UTC
### Steps to reproduce

Watch a video to end
Press back button until you guess the app should close
(Possibly) Attempt to press 'x' on the video before the app closes
Reopen the app

### Expected behavior

No error

### Actual behavior

Error

### LibreTube version

0.5.0

### Android version

Lineage (2021)

### Other details

Doesn't seem to be catastrophic, but perhaps worthy to explore. Here is the error:

```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.github.libretube.db.obj.WatchPosition.videoId' on a null object reference
	at com.github.libretube.db.dao.WatchPositionDao_Impl$2.bind(WatchPositionDao_Impl.java:2)
	at androidx.room.EntityDeletionOrUpdateAdapter.handle(EntityDeletionOrUpdateAdapter.java:2)
	at com.github.libretube.db.dao.WatchPositionDao_Impl.delete(WatchPositionDao_Impl.java:3)
	at com.github.libretube.db.DatabaseHelper$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:6)
	at java.lang.Thread.run(Thread.java:923)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Nephys222** [comment] 2022-09-06 14:31
@elfein727 Try cleaning uninstall the previous version before updating to the latest version.

**Comment by Bnyro** [comment] 2022-09-06 21:37
Dupe of #1194, not sure yet what its caused by

**Closed by Bnyro** 2022-09-06 21:37 UTC
Labels: bug
