### ISSUE TITLE
No Video loads then crashes

### ISSUE THREAD

**Issue by HageFale** [libre-tube/LibreTube#4697] opened 2023-09-05 18:28 UTC
### Steps to reproduce

1. I press on a Video nothinh happens its loading forever
2. Then whole app crashes.
3. All bullshit please fix

### Expected behavior

Video needs to load if i click on it.

### Actual behavior

No Video is loading then it crashes...
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{9371c28 VFED.V... ......ID 0,0-1080,2129 #7f0a0288 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@9ffc45b, layout:androidx.recyclerview.widget.LinearLayoutManager@dab1772, context:com.github.libretube.ui.activities.SettingsActivity@47d485e
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(SourceFile:29)
	at com.github.libretube.ui.fragments.HomeFragment$loadPlaylists$2.onItemRangeChanged(SourceFile:12)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(SourceFile:19)
	at androidx.preference.Preference.notifyChanged(SourceFile:17)
	at androidx.preference.Preference.setSummaryProvider(SourceFile:3)
	at com.github.libretube.ui.preferences.InstanceSettings.access$initInstancesPref(SourceFile:105)
	at com.github.libretube.ui.preferences.InstanceSettings$initInstancesPref$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(SourceFile:54)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:32)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@80f38be, Dispatchers.IO]
    

### LibreTube version

0.17.1

### Android version

Android 13 MIUI 14.0.6

### Other details

java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{9371c28 VFED.V... ......ID 0,0-1080,2129 #7f0a0288 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@9ffc45b, layout:androidx.recyclerview.widget.LinearLayoutManager@dab1772, context:com.github.libretube.ui.activities.SettingsActivity@47d485e
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(SourceFile:29)
	at com.github.libretube.ui.fragments.HomeFragment$loadPlaylists$2.onItemRangeChanged(SourceFile:12)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(SourceFile:19)
	at androidx.preference.Preference.notifyChanged(SourceFile:17)
	at androidx.preference.Preference.setSummaryProvider(SourceFile:3)
	at com.github.libretube.ui.preferences.InstanceSettings.access$initInstancesPref(SourceFile:105)
	at com.github.libretube.ui.preferences.InstanceSettings$initInstancesPref$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(SourceFile:54)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:32)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@80f38be, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-09-05 20:04
Duplicate of  #4216

**Closed by Bnyro** 2023-09-05 20:04 UTC
Labels: bug
