### ISSUE TITLE
Landscape layout used in portrait mode when opening app via 3rd party app while in landscape mode

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#5401] opened 2023-12-29 10:33 UTC
### Steps to reproduce

1. Ensure your phone is in landscape mode
2. Open the link to the video in any 3rd party app

### Expected behavior

The video should open in fullscreen mode, touching the screen should bring up the player interface, rotating the phone should open the video in portrait mode player UI, if the player is minimised, rotating the screen to horizontal should do nothing (at least if rotation is not enabled in the settings).

### Actual behavior

Touching the screen doesn't bring up the player interface, rotating the phone opens the video in minimised state, if the player is minimised, rotating the screen to horizontal opens the video in full screen. Opening the video in portrait mode from the minimised state completely breaks the UI.

https://github.com/libre-tube/LibreTube/assets/63293432/2bf69762-aa68-47f2-ae13-e46b60e0e972

### LibreTube version

Nightly 0.12.1 commit 887d062

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by lu4p** [comment] 2024-01-10 19:54
I definitely had this happen to me before but didn't know how to reproduce it.

**Comment by M00NJ** [comment] 2024-01-11 20:01
Me too. I think it happens sometimes when I switch back from PiP.

**Comment by abGit9** [comment] 2024-03-06 04:53
This is hard to reproduce but there does seem to be an issue when switching between landscape and portrait modes. The exact behavior is hard to peg but there always seems to be a glitch. Sometimes when landscape  -> portrait, my video just disappears.   Other times, the ui doesn't change it all.

**Comment by Bnyro** [comment] 2024-05-01 14:20
This should be fixed since https://github.com/libre-tube/LibreTube/issues/5698 - we now wait until the main activity is rendered before loading the video link - during that time Android also properly reacts to LibreTube's request to change the app orientation to landscape / portrait.

**Closed by Bnyro** 2024-05-01 14:20 UTC
Labels: bug

**Comment by DanielProg39** [comment] 2024-05-01 19:58
Yup, this one's gone now :partying_face:
