### ISSUE TITLE
Import playlist error and crash

### ISSUE THREAD

**Issue by Chungaa** [libre-tube/LibreTube#2948] opened 2023-02-02 21:17 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/109001366/216450913-2656cc93-08d1-43d9-b69a-26b7c619712d.mp4

### Expected behavior

The playlist shows that there are no videos stored, but there are videos stored.
Then when you press random play, the app crashes.

### Actual behavior

n

### LibreTube version

0.11.1

### Android version

Android 12

### Other details

Smartphone Realme GT Neo 2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment] 2023-02-03 03:42
Can you upload the video in English?

**Comment by Bnyro** [comment] 2023-02-03 06:14
Duplicate of #2608

**Closed by Bnyro** 2023-02-03 06:14 UTC
Labels: bug
