### ISSUE TITLE
Facing this error of auto crash while backup/restore. 

### ISSUE THREAD

**Issue by hanimebeast** [libre-tube/LibreTube#4693] opened 2023-09-04 15:56 UTC
### Steps to reproduce

i have reinstall the app. but error is not getting resolve. facing crash while restoring/ backing up locally. also the instance get stucl.

```
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{d07a45d VFED.V... ......ID 0,0-1080,2093 #7f0a0288 app:id/recycler_view}, adapter:androidx.preference.PreferenceGroupAdapter@fac7c96, layout:androidx.recyclerview.widget.LinearLayoutManager@d4381d2, context:com.github.libretube.ui.activities.SettingsActivity@b2d1f6
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(SourceFile:29)
	at com.github.libretube.ui.fragments.HomeFragment$loadPlaylists$2.onItemRangeChanged(SourceFile:12)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(SourceFile:19)
	at androidx.preference.Preference.notifyChanged(SourceFile:17)
	at androidx.preference.Preference.setSummaryProvider(SourceFile:3)
	at com.github.libretube.ui.preferences.InstanceSettings.access$initInstancesPref(SourceFile:105)
	at com.github.libretube.ui.preferences.InstanceSettings$onCreatePreferences$1.invokeSuspend(SourceFile:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e5595ff, Dispatchers.IO]
    ```

### Expected behavior

The backup / restore feature and app player should run videos

### Actual behavior

crashing

### LibreTube version

0.17.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-09-04 16:26
The app crashes when selecting an instance or when restoring a back up? Because the crash log is the same as several issues (issue was fixed in debug builds) and happens when selecting an instance. 

Try and report with debug build

**Comment by Bnyro** [comment] 2023-09-04 17:18
I think it might be a good idea to add a mandatory checkbox that users should test the latest alpha build first before opening an issue to avoid having so many duplicates.

**Comment by akano12** [comment] 2023-09-04 18:02
> I think it might be a good idea to add a mandatory checkbox that users should test the latest alpha build first before opening an issue to avoid having so many duplicates.

Sounds good but the version number of the artifacts generated shouldn't be the same as the stable version (both debug and stable use same versions) 

It's possible to use commit hashes as version number but imo it's not a good idea in this scenario considering there's at least 3 builds being released daily so tracking which one is newer is a bit unpractical.

Or use a suffix next to the version number to indicate the build number (like 0.17.1-b1 or b3....)

**Comment by Bnyro** [comment] 2023-09-05 20:08
@akano12 I like the idea of enumerating the debug version names, however it's probably not that easy to implement.

Closing as duplicate of https://github.com/libre-tube/LibreTube/issues/4216

**Closed by Bnyro** 2023-09-05 20:08 UTC
Labels: bug

**Comment by hanimebeast** [comment] 2023-09-08 04:04
> The app crashes when selecting an instance or when restoring a back up? Because the crash log is the same as several issues (issue was fixed in debug builds) and happens when selecting an instance.
> 
> Try and report with debug build
> 
> You can find debug builds here https://github.com/libre-tube/NightlyBuilds/tree/main
> 
> And the issue I'm referring to #4216




using the nigtly debug apk version, No error has been face yet. using since 3 days
