### ISSUE TITLE
Download crush 

### ISSUE THREAD

**Issue by dr-chissico** [libre-tube/LibreTube#4250] opened 2023-07-17 15:30 UTC
### Steps to reproduce

1. Open App
2. Search a video
3. Try to download
4. Download begin
5. Selecting a file being downloaded app crush

### Expected behavior

Open the file to see the status was expected.

### Actual behavior

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/DORMIR OUVINDO ESTES 5 SALMOS mudará a sua vida_126_kbps_M4A.mp4
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
	at j$.nio.file.spi.a.x(Unknown Source:14)
	at j$.nio.file.Files.readAttributes(SourceFile:0)
	at j$.nio.file.Files.size(Unknown Source:5)
	at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(SourceFile:293)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:1136)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(Unknown Source:5)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:838)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(SourceFile:64)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26557)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(SourceFile:541)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(SourceFile:245)
	at retrofit2.Utils.verticalSolvingPass(SourceFile:31)
	at retrofit2.Utils.solveVerticalMatchConstraint(SourceFile:102)
	at retrofit2.Utils.verticalSolvingPass(SourceFile:186)
	at retrofit2.Utils.verticalSolvingPass(SourceFile:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(SourceFile:440)
	at androidx.lifecycle.ViewModelProvider.solveLinearSystem(SourceFile:36)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(SourceFile:1183)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:382)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(SourceFile:72)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(SourceFile:160)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:835)
	at android.view.View.measure(View.java:26557)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4142)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2836)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3113)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2543)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9465)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	... 3 more
    

### LibreTube version

0.16.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-17 15:33
duplicate of #3379

**Closed by Bnyro** 2023-07-17 15:33 UTC
Labels: bug
