### ISSUE TITLE
The search button is not visible.

### ISSUE THREAD

**Issue by Binleti** [libre-tube/LibreTube#2028] opened 2022-11-24 09:00 UTC
### Describe your suggested feature

1.Do a search.

2.Click search in more options.

3.Press the home button.

4.The search button is not visible.

### Other details

https://user-images.githubusercontent.com/118555547/203738614-e47c6943-d003-4d26-a145-b7448e18ce44.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-11-24 09:36
dupe of #1834

**Closed** 2022-11-24 09:48 UTC
Labels: enhancement
