### ISSUE TITLE
I suggest adding a function black list

### ISSUE THREAD

**Issue by rhp7rholype** [libre-tube/LibreTube#2354] opened 2022-12-11 23:44 UTC
Hello. I suggest that can channels could be added to the black list so that they could not appear in the recommendations.

For example, a long press on the video that we want to add to the black list, and in the coming menu, "to get a channel on the black list."

I don't know how hard it is to do this, but I think it's gonna be a useful function

Thank You

**Comment by Bnyro** [comment] 2022-12-15 18:43
dupe of  #1173, still no plans for adding something like that

**Closed by Bnyro** 2022-12-15 18:43 UTC
