### ISSUE TITLE
Crash on listing subscription

### ISSUE THREAD

**Issue by Cinorid** [libre-tube/LibreTube#1213] opened 2022-09-04 13:43 UTC
### Steps to reproduce

Open the app and go to subscription 

### Expected behavior

Opening normally 

### Actual behavior

Crashing 

### LibreTube version

0.5

### Android version

Android 7

### Other details

java.lang.ArithmeticException: divide by zero
	at com.github.libretube.util.SetWatchProgressLengthKt$setWatchProgressLength$2.onGlobalLayout(SetWatchProgressLength.kt:5)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2278)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6782)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
	at android.view.Choreographer.doCallbacks(Choreographer.java:742)
	at android.view.Choreographer.doFrame(Choreographer.java:674)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-04 14:09
Dupe of #1092

**Closed by Bnyro** 2022-09-04 14:09 UTC
Labels: bug
