### ISSUE TITLE
Playback issue when switching to video player

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#2964] opened 2023-02-04 13:01 UTC
### Steps to reproduce

1.Change LibreTube to an audio player.
2.Play sound
3.Click the video player button below the audio player
4.All videos in the queue are played continuously

### Expected behavior

Only the current video should be played and the next video should not be played until the current video is finished

### Actual behavior

The opposite of the above occurs.

https://user-images.githubusercontent.com/124310688/216769052-1ef8a979-e251-4ee3-b6b6-b90a69d4aa9b.mp4

### LibreTube version

0.11.1 Debug və 0.11.1

### Android version

Android 12 and 13🤔

### Other details

But when switching to the audio player, this problem does not exist

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-04 13:15
Duplicate of #2800

**Closed by Bnyro** 2023-02-04 13:15 UTC
Labels: bug
