### ISSUE TITLE
Apps crashes

### ISSUE THREAD

**Issue by Jwjshhi** [libre-tube/LibreTube#3567] opened 2023-04-16 05:32 UTC
### Steps to reproduce

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.LibraryFragment$fetchPlaylists$1$1.invokeSuspend(LibraryFragment.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@96119af, Dispatchers.Main.immediate]
    

### Expected behavior

.

### Actual behavior

App keep crashing
For no reasion
When i click on the watch history it crashes
Sometime it crashes randomly 

### LibreTube version

0.14.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-04-16 06:59
Duplicate of #3551

**Closed by Bnyro** 2023-04-16 06:59 UTC
Labels: bug
