### ISSUE TITLE
Video progress moves forward when switching from audio to default player

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#2807] opened 2023-01-21 20:26 UTC
### Steps to reproduce

1. Open any video
2. Go to audio mode using the button in the colored group of buttons
3. Click on the 3rd button in the button group at the bottom of the audio view to switch back to the default video player

### Expected behavior

The video player should continue at the video duration the audio player ended at.

### Actual behavior

The video progress moves forward, often skips to the end.

### LibreTube version

0.11.0

### Android version

Android 13 (GrapheneOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment] 2023-01-22 03:45
Duplicate of #2800

**Closed** 2023-01-22 07:30 UTC
Labels: bug
