### ISSUE TITLE
Icons Flickering at Miniplayer

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1619] opened 2022-10-20 06:55 UTC
### Steps to reproduce

1. Play any video
2. Swipe down the player

### Expected behavior

Icons should not show up there.

### Actual behavior

Icons flicker at the player window in miniplayer

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

Reference image and GIF:

> ![Screenshot_20221020-122008~3](https://user-images.githubusercontent.com/87353286/196877197-3914877e-953c-4206-b470-de677af82a3a.png)

> ![ezgif-2-b8f6505242](https://user-images.githubusercontent.com/87353286/196875865-19f6374c-f0a6-4f8c-a4bc-b842da562c4f.gif)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-10-20 16:16
I think this is a dupe of #1280.

**Comment by Bnyro** [comment] 2022-10-20 16:44
True, we'll go on tracking it here :)

**Closed** 2022-10-30 08:38 UTC
Labels: bug

**Comment by xIUPITERx** [comment] 2022-11-12 21:40
Still not fixed in 7.0.
![Screenshot_20221112-223829_LibreTube.jpg](https://user-images.githubusercontent.com/97352673/201495636-114f1a8b-3b5b-4a8e-95c1-c770c2b16a68.jpg)
