### ISSUE TITLE
full screen issue with gesture

### ISSUE THREAD

**Issue by ariyacz** [libre-tube/LibreTube#5818] opened 2024-03-27 08:12 UTC
### Steps to reproduce

full screen the video with gesture
screen goes to portrait full screen and navbar hide.. and nothing display with touch.. 
with button everything is fine.. 

### Expected behavior

screen should be landscape with navbar display with touch.. 

### Actual behavior

when i full screen a video with gesture.. the screen rorate to portrait mode and the navbar goes hide...
even if full screen setting is on landscape mode this happens.. 

### LibreTube version

22.1

### Android version

12

### Other details

i have this overlaying issue since version 19...
when i full screen a video with gesture.. the screen rorate to portrait mode and the navbar goes hide...
with full screen button everything is fine..
everytime after releasing new update i test and still this issue force me to downgrade to version 19... in version 19 with same setting everything works great..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-27 09:57
Duplicate of https://github.com/libre-tube/LibreTube/issues/5743

**Closed by Bnyro** 2024-03-27 09:57 UTC
Labels: bug

**Comment by ariyacz** [comment] 2024-03-27 12:42
you just marked it as duplicate?
i seen that post already.. but there wasn't any solution..
i can't use any new update for this issue.. I'm libertube user since version 0.4..
give me a solution or tell me is it a bug that's gonna fix..? because I'm confused

**Comment by M00NJ** [comment] 2024-03-29 11:02
Opening duplicate issues does not make the maintainer fix them faster. If anything the opposite, because it wastes time and is annoying. Also your not entitled to anything because you've been using the application for a long time. You using the app doesn't benefit the developer in any way because it's free, so I don't understand your throught process. Neither do I understand the point of your question. Yes, obviously it's a bug and not intended behavior and since it's not marked as `wontfix` it will be worked on eventually.
