### ISSUE TITLE
Cannot return to main interface from "Play in the background" interface

### ISSUE THREAD

**Issue by e075e** [libre-tube/LibreTube#5205] opened 2023-11-19 09:53 UTC
### Steps to reproduce

1. search any video
2. long press on it
3. choose "Play in the background"
4. touch the current playing panel at the bottom to open its full interface 

### Expected behavior

- the top button to dismiss the playing interface is visible
- pressing Android's back button returns to the main interface

### Actual behavior

- There is not any button to go to the main interface (first screenshot).
- pressing Android's back button returns to the Android home

# workaround
1. open the Android notification panel
2. touch the libretube notification

the "Play in the background" panel appears, but now with a top button to dismiss it (second screenshot)

# no top button
![1](https://github.com/libre-tube/LibreTube/assets/15078341/9faa1b21-f7ed-445a-be1d-9b8a9a56cc07)

# with top button
![2](https://github.com/libre-tube/LibreTube/assets/15078341/ee989b43-a69a-491a-85f9-42a80251311e)

### LibreTube version

0.20.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-11-19 10:00
Duplicate of #4114, but I'll close the other issue because this one contains more details.

**Closed** 2023-12-17 16:12 UTC
Labels: bug, help wanted
