### ISSUE TITLE
Player background bug

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2901] opened 2023-01-29 15:13 UTC
### Steps to reproduce

1. Play a video
2. Put it in background
3. Wait a few minutes
4. Experience either Android or something kills the player

### Expected behavior

Play the video in the background until I don't stop it manually

### Actual behavior

It stops

### LibreTube version

0.11.1

### Android version

Android 13

### Other details

Note this does not happen in music mode as far as I checked

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M3DZIK** [comment] 2023-01-30 21:19
the same issue for me

**Comment by Bnyro** [comment] 2023-01-30 21:31
Duplicate of #1847 and #2231

**Closed by Bnyro** 2023-01-30 21:31 UTC
Labels: bug

**Comment by farline99** [comment] 2023-02-03 16:26
Same here, but both universal apk and arm64 had this bug, player is killed after 2-4 minutes. Android 12, ArrowOS. Battery optimization is disabled at all :(
