### ISSUE TITLE
Not working when the screen is switched off

### ISSUE THREAD

**Issue by SSuper-supreme** [libre-tube/LibreTube#4309] opened 2023-07-26 05:52 UTC
### Steps to reproduce

1. I play a video
2. I switched off the screen
3. The video keeps playing
4. After few minutes the video paused
5. The video works right away if I turned the screen on, for example, by double-klicking the screen or pressing the power button, even if the phone is still locked.
6. This problem comes with old libretube versions
7. My phone is "honor note 8"

### Expected behavior

Libretube should keep working when the screen is off

### Actual behavior

It stops working after few minutes when the screen turned  off

### LibreTube version

0.16.1

### Android version

8

### Other details

After it stops, Libretube works again when the screen turned on even if the phone is still locked

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-26 06:11
duplicate of #3589

**Closed by Bnyro** 2023-07-26 06:11 UTC
Labels: bug

**Comment by SSuper-supreme** [comment] 2023-07-26 06:40
> duplicate of #3589

It is not duplicate as there's no notification appearsvafter the video is paused, and the video continue working automatically when the screen is on again. Please, read issue #3589 carefully.
