### ISSUE TITLE
App crash when opening channel

### ISSUE THREAD

**Issue by leg7** [libre-tube/LibreTube#1196] opened 2022-08-28 18:51 UTC
### Steps to reproduce

Open libre tube
Search for "ltt"
Click on the channel

### Expected behavior

Youtube channel should open

### Actual behavior

Crashes

### LibreTube version

0.5.0

### Android version

Android 13 GrapheneOS

### Other details

java.lang.ArithmeticException: divide by zero
	at com.github.libretube.util.SetWatchProgressLengthKt$setWatchProgressLength$2.onGlobalLayout(SetWatchProgressLength.kt:5)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3352)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-08-28 19:14
Dupe of #1092, resolved.

**Closed by Bnyro** 2022-08-28 19:14 UTC
Labels: bug
