### ISSUE TITLE
Various UI bugs

### ISSUE THREAD

**Issue by l-zacarias** [libre-tube/LibreTube#6223] opened 2024-07-12 11:48 UTC
### Steps to reproduce

1. Open the libretube app
2. Play a random video
3. Play by pulling down the video player to different heights on the screen

### Expected behavior

The video viewport should automatically resize to the correct size when it returns to the top of the screen

### Actual behavior

As you can see in my screen record there are still some UI inconsistencies in the app when changing the system theme or android wallpaper colors, some of them like the mini player overlapping the bottom tabs happens randomly even no matter if you change theme or colors.

### LibreTube version

0.24.0

### Android version

Android 14

### Device

Oneplus 9 Pro running Lineage os 21

### Other details

**Screen Record Video**
https://drive.google.com/file/d/1EhLDGr0xI4gTdrrWDfK_RUymmTrFVlsD/view?usp=sharing

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-07-12 17:53
Duplicate of https://github.com/libre-tube/LibreTube/issues/5816

**Closed by Bnyro** 2024-07-12 17:53 UTC
Labels: bug
