### ISSUE TITLE
Error when opening the downloaded video due to Watch progress

### ISSUE THREAD

**Issue by Figim** [libre-tube/LibreTube#6748] opened 2024-11-18 06:09 UTC
### Steps to reproduce

1. Play normal video. Which you have not downloaded
2. Then play the downloaded video
3. Error

### Expected behavior

The video should play

### Actual behavior

FATAL EXCEPTION: main
Process: com.github.libretube.debug, PID: 27111
java.lang.RuntimeException: Unable to create service com.github.libretube.services.VideoOfflinePlayerService: java.lang.IllegalStateException: Session ID must be unique. ID=
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4953)
	at android.app.ActivityThread.access$1800(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2300)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalStateException: Session ID must be unique. ID=
	at androidx.media3.session.MediaSession.<init>(MediaSession.java:686)
	at androidx.media3.session.MediaLibraryService$MediaLibrarySession.<init>(MediaLibraryService.java:679)
	at androidx.media3.session.MediaLibraryService$MediaLibrarySession$Builder.build(MediaLibraryService.java:659)
	at com.github.libretube.services.AbstractPlayerService.createPlayerAndMediaSession(AbstractPlayerService.kt:221)
	at com.github.libretube.services.AbstractPlayerService.onCreate(AbstractPlayerService.kt:156)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4940)
	... 9 more

Or Second error👇

FATAL EXCEPTION: main
Process: com.github.libretube.debug, PID: 28757
kotlin.UninitializedPropertyAccessException: lateinit property playerController has not been initialized
	at com.github.libretube.ui.activities.OfflinePlayerActivity.saveWatchPosition(OfflinePlayerActivity.kt:259)
	at com.github.libretube.ui.activities.OfflinePlayerActivity.access$saveWatchPosition(OfflinePlayerActivity.kt:49)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$watchPositionTimer$1.invoke(OfflinePlayerActivity.kt:63)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$watchPositionTimer$1.invoke(OfflinePlayerActivity.kt:63)
	at com.github.libretube.util.PauseableTimer$resume$1.run$lambda$0(PauseableTimer.kt:26)
	at com.github.libretube.util.PauseableTimer$resume$1.$r8$lambda$VxhLTNquOdMkkzQSVVQ4K3PqWGw(Unknown Source:0)
	at com.github.libretube.util.PauseableTimer$resume$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
### LibreTube version

0.26.0 Debug

### Android version

All

### Other details

https://github.com/user-attachments/assets/15e97025-7343-4bb7-8ad5-9900d4096e1d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-11-18 07:33
Duplicate of https://github.com/libre-tube/LibreTube/issues/6738

**Closed by Bnyro** 2024-11-18 07:33 UTC
Labels: bug
