### ISSUE TITLE
In audio mode, player gets stuck and not showing search page

### ISSUE THREAD

**Issue by deepakjuly20** [libre-tube/LibreTube#4308] opened 2023-07-26 04:43 UTC
### Steps to reproduce

1. First turn to audio mode.
2. Then play any video from home or search page.
3. The player will open and start playing only audio.
4. Now press back button from android system navigation bar only.
5. The player will minimse at bottom of search or home page.
6. Now open the minimised video by tapping on the minimised thumbnail. The video will again open in audio mode.
7. Keep repeating steps 4 to 6.
8. After a few times you do it, the audio player stucks and does not return to search or home page. The 3 dot menu disappears and nothing else works except the current player controls.
9. U cant minimise the player again. Nor switching to other tabs work.
10. Kindly note this happens in audio mode only. Or when i switch from video to audio mode inside the player itself .

### Expected behavior

The audio player should minimize and open an infinite number of times.

### Actual behavior

But it stucks after a couple of times making back button and  other tab buttons unresponsive.

### LibreTube version

0.16.1

### Android version

13

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-26 05:14
Duplicate of #4114

**Closed by Bnyro** 2023-07-26 05:14 UTC
Labels: bug
