### ISSUE TITLE
New content does not appear

### ISSUE THREAD

**Issue by Grkrz** [libre-tube/LibreTube#2763] opened 2023-01-19 19:34 UTC
### Steps to reproduce

Often subscribed content does not appear on the app even if subscribed on piped web it is showing up. 
On the app not showing up
On the webbrowser with piped web appears.
Sometimes in the app content appear many hours later.
Some of yt channels dont appear at all.

### Expected behavior

.

### Actual behavior

.

### LibreTube version

Latest 0.10

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-19 19:57
Duplicate of #1424

**Closed by Bnyro** 2023-01-19 19:57 UTC
Labels: bug
