### ISSUE TITLE
[FEATURE] options . vertical | horizontal | auto position for app and for full-screen mode

### ISSUE THREAD

**Issue by DI555** [libre-tube/LibreTube#127] opened 2022-04-14 12:57 UTC
**Describe the feature you'd like to see added**

whould like to see two options , - vertical | horizontal | auto position for app and for full-screen mode!

(now works only vertical position for app, and auto position for full-screen mode)

**Comment by Bnyro** [comment] 2022-05-18 08:52
Dupe of #24

**Closed by Bnyro** 2022-05-18 08:52 UTC
Labels: duplicate
