### ISSUE TITLE
the mini player position is same even if no navigation icon is selected 

### ISSUE THREAD

**Issue by tanay-pingalkar** [libre-tube/LibreTube#3788] opened 2023-05-17 06:50 UTC
### Steps to reproduce

The trending page, subscription are not so usefull to me, so i  removed all navigation options, which is a great option to have.

### Expected behavior

So it is expected that the navigation bar disappears and the mini player should move down as there is not navigation option and only a single page of library is present. 

### Actual behavior

But it doesn't, and stays at the same position as before as the navigation bar is there even though navigation bar has disappeared. So looks misplaced and i think its more of a bug than enhancement. 
![Screenshot_20230517-120530_LibreTube](https://github.com/libre-tube/LibreTube/assets/72514547/88472571-2cfe-4240-a22e-d20c72b23ae3)

### LibreTube version

latest

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-17 08:12
Duplicate of #2548

**Closed by Bnyro** 2023-05-17 08:12 UTC
Labels: bug
