### ISSUE TITLE
crashes when toggling light/dark mode while some menus are open

### ISSUE THREAD

**Issue by salad612** [libre-tube/LibreTube#4434] opened 2023-08-12 19:17 UTC
This form is for crashes when the comment section is open, more scenarios when crashes occur are in the replies below.

### Steps to reproduce

1. Set app theme to system
2. Go to a video that has comments
3. Open the comment section
4. Toggle system dark mode on or off (like by toggling battery saver or toggling dark mode in quick settings)

### Expected behavior

Switches between dark mode and light mode in the app, ideally without closing the comments section as that would be inconvenient

### Actual behavior

Crashes

### LibreTube version

0.16.1

### Android version

Android 13

### Other details
here is the log

```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.CommentsMainFragment.onViewCreated(SourceFile:77)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:296)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:301)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:301)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:144)
	at androidx.fragment.app.FragmentManager.moveToState(SourceFile:62)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(SourceFile:36)
	at androidx.fragment.app.FragmentActivity.onStart(SourceFile:35)
	at androidx.appcompat.app.AppCompatActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
	at android.app.Activity.performStart(Activity.java:8367)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3669)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
    
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-13 09:26
That's because we pass arguments to the constructors of any `DialogFragment` classes. We should pass the arguments via bundles instead. But that's quite some work and not really something of high priority at the moment.

**Comment by anshtya** [comment] 2023-09-01 10:44
> 
Hello. Can I give it a try ?

**Comment by Bnyro** [comment] 2023-09-01 11:41
Sure.

**Comment by anshtya** [comment] 2023-09-02 13:51
Hello. I want to ask, when the dark mode is toggled from the status bar, the player minimizes and comment section isn't closed, so according the issue should I focus only to prevent the app crash or both i.e. to prevent crash as well as the closing of comment section? I'm just confused about the issue's title and the stated expected behaviour. I'm currently working on the `DialogFragment` thing.

**Comment by Bnyro** [comment] 2023-09-02 13:54
I think it's sufficient to only focus on avoiding any crashes when possible - Android usually recompositions all fragments and activities when the dark mode is toggled and hence it's not that easy to prevent the sheet to hide.

**Comment by anshtya** [comment] 2023-09-02 16:51
There are some dialogs like `DeletePlaylistDialog` which consist of a callback function in its constructor. I'm not sure if the callback can be put in `Bundle` and passed to the dialog.

**Comment by Bnyro** [comment] 2023-09-02 17:28
That's not possible, for these cases we have to use a `FragmentResultListener`: see https://developer.android.com/guide/fragments/communicate#fragment-result.

**Comment by anshtya** [comment] 2023-09-03 06:54
The callbacks are not working for me right now with `FragmentResultListener`. Every dialogs except the callback dialogs are done.

**Comment by Bnyro** [comment] 2023-09-03 06:59
Did you make sure to set the listener to the same `FragmentManager` as the `DialogFragment#show(FragmentManager)` method uses. E.g. `childFragmentManager.setFragmentResultListener { key, bundle -> }` when using `VideoOptionsBottomSheet(...).show(childFragmentManager, null)`.

**Comment by anshtya** [comment] 2023-09-03 09:10
Yes.

**Comment by Bnyro** [comment] 2023-09-03 11:02
Could you maybe already open a draft PR using the `FragmentResultListener` so that it's possible for us to find the issue or debug it?

**Comment by anshtya** [comment] 2023-09-03 11:03
Oh ok.

**Comment by anshtya** [comment] 2023-09-04 10:29
I think I know why my `FragmentResultListener` is not working because I am putting its code in `SomeBottomSheet` and when any option is selected from the sheet, the sheet gets closed. So it will not receive any result from the dialog.

**Closed** 2023-09-13 15:44 UTC
Labels: bug, priority: low, contribution-friendly
