### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1193] opened 2022-08-28 16:33 UTC
### Steps to reproduce

I don't exactly know how it came.

### Expected behavior

Should load videos. The LibreTube Debug app is still working in the same Network.

### Actual behavior

Videos don't load and "Network error" is displayed.

![Screenshot_20220828-173052_LibreTube](https://user-images.githubusercontent.com/97352673/187084534-3139b8eb-a9eb-4b85-b76c-957bcc599af9.jpg)

### LibreTube version

0.5.0

### Android version

Android 12 One UI 4.1

### Other details

Clearing cache and storage didn't help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-08-28 16:49
The issue is in the release or in the debug version?

**Comment by xIUPITERx** [comment] 2022-08-28 19:10
It's in the release version.

**Comment by Bnyro** [comment] 2022-08-28 19:15
Then it's either an issue of the instance you are using or already somehow fixed by the recent changes in the debug builds ...

**Closed** 2022-08-28 19:15 UTC
Labels: bug
