### ISSUE TITLE
Local copy of instance subscriptions

### ISSUE THREAD

**Issue by gojzdar** [libre-tube/LibreTube#5420] opened 2024-01-02 19:22 UTC
### Describe your suggested feature

Every time an instance goes offline, it takes my subscriptions with it.
This isn't a problem if you have exported subscriptions in the past, but it is still very annoying, especially if you haven't exported them, like me when I first downloaded libretube.

If you to export subscriptions while the instance you are using is down (which happens quite often), you get a 0B file.
To fix this, you could just cache the subscriptions on disc for whenever this happens. Since the subscriptions file is NEVER > 1mb, it shouldn't really matter. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-01-02 19:37
Duplicate of https://github.com/libre-tube/LibreTube/discussions/5195

**Closed by Bnyro** 2024-01-02 19:37 UTC
Labels: enhancement
