### ISSUE TITLE
App crash when entering channel from video

### ISSUE THREAD

**Issue by CryogenicPotato** [libre-tube/LibreTube#2837] opened 2023-01-23 08:21 UTC
### Steps to reproduce

Hello, I've been watching the following video: https://piped.video/watch?v=Cu5msj7yWbo

If I click on channel's title below the video player, I get the following exception:

kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 261: Expected string literal but 'null' literal was found at path: $.bannerUrl
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: .....eusercontent.com","bannerUrl":null,"description":"Uploading .....
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:1)
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:64)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:34)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:7)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:14)
	at org.chromium.net.UploadDataSink.decodeStringElement(UploadDataSink.java:6)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:119)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4b903e8, Dispatchers.Main.immediate]
    

### Expected behavior

Should not throw exception

### Actual behavior

Throws the above exception

### LibreTube version

0.11.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by CryogenicPotato** [comment] 2023-01-23 08:23
Uuups! Hold on, that night have just been fixed with commits https://github.com/libre-tube/LibreTube/commit/e96f36f27702ff80a8f43c35098167e75e1c0f4b

If that's the case, please disregard this issue.

**Comment by Bnyro** [comment] 2023-01-23 12:13
Indeed that commit fixed it, dupe of #2813

**Closed by Bnyro** 2023-01-23 12:13 UTC
Labels: bug
