### ISSUE TITLE
Videos are missing in Subscription Feed

### ISSUE THREAD

**Issue by Schninzent** [libre-tube/LibreTube#2349] opened 2022-12-11 17:46 UTC
### Steps to reproduce

1: Import your Subscriptions 

2: Compare the videos in your LibreTube Subscription Feed to the videos of the official YouTube App 

### Expected behavior

Videos in the Subscription Feed should be the same on both Apps

### Actual behavior

Some videos are missing in LibreTube. 

For example: 

![Screenshot_20221211-182557](https://user-images.githubusercontent.com/57478561/206919453-08082ca6-4bf6-4e3f-b983-48d8872247d3.png)

Compared to the normal YouTube App: 

![Screenshot_20221211-182547~2](https://user-images.githubusercontent.com/57478561/206919551-035a82a3-ac10-40e0-a025-44c0dad552ba.png)

As one can see, there is one video missing between "Terry B" and "GCN", even though I am subscribed to this specific channel in LibreTube. 
I had the same problem for other Channels. 

### LibreTube version

0.9.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-11 17:52
dupe of #1424

**Closed by Bnyro** 2022-12-11 17:52 UTC
Labels: bug
