### ISSUE TITLE
Auto hide the Nav bar and the header bar while scrolling

### ISSUE THREAD

**Issue by Toiletmason** [libre-tube/LibreTube#3568] opened 2023-04-16 07:20 UTC
### Describe your suggested feature

If they disappear when scrolling down and then reappear when scrolling up would be sufficient.

### Other details

I don't know whether or not a better method could be used. I just know the nav bar at the bottom takes up a lot of real estate. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-04-16 10:57
Duplicate of #1912

**Closed by Bnyro** 2023-04-16 10:58 UTC
Labels: enhancement
