### ISSUE TITLE
Videos Start Small in Upper Left Corner

### ISSUE THREAD

**Issue by FrenchToucan** [libre-tube/LibreTube#6433] opened 2024-09-01 15:29 UTC
### Steps to reproduce

1.Open app. 
2. Select any video from Subscriptions feed.
3. Player begins with tiny video in upper left corner. 

### Expected behavior

Video begins to play, filling the top half of the screen.

### Actual behavior

It plays in a tiny rectangle in the upper left corner of the Libretube window (not pictured in picture).

### LibreTube version

0.25.1

### Android version

Android 15 Beta 1

### Other details

Minimize Libretube and maximize again or minimize just the video and maximize again or turn the screen off and on to fix for that video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-09-01 16:24
Duplicate of https://github.com/libre-tube/LibreTube/issues/5816

**Closed by Bnyro** 2024-09-01 16:24 UTC
Labels: bug

**Comment by FrenchToucan** [comment] 2024-09-01 16:59
@Bnyro I'm noticing the opposite of the linked issue, if I'm reading it correctly. Swiping from the mini player fixes my issue.

**Comment by Bnyro** [comment] 2024-09-01 20:14
Please just add that as a comment to th existing issue, there's likely the same cause behind it.
