### ISSUE TITLE
backup & restore issue

### ISSUE THREAD

**Issue by itsmmt305** [libre-tube/LibreTube#3427] opened 2023-03-28 05:16 UTC
### Steps to reproduce

be using version 0.13 or 0.13.1

open settings via ellipses menu
tap on backup & restore
tap on backup under app backup
   or tap on restore and select a .json backup file

### Expected behavior

when tapping on backup files (documentsui) should open for saving the backup file
or
when selecting a .json file, a dialog to restart should appear indicating that file has been selected, like in previous versions.

### Actual behavior

nothing happens in either case

### LibreTube version

0.13.1

### Android version

Android 12 / MIUI 13

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Raj9039852537** [comment] 2023-03-28 12:16
Same problem occurred in android 13 custom rom in version 0.13.1

**Comment by SebiTalent04** [comment] 2023-03-28 21:24
Can reproduce on 0.131, Android 11/Emui 12.

**Comment by akano12** [comment] 2023-04-02 19:03
Can't reproduce either.
Works well on S20 Android 13.

**Comment by muhammad-ans** [comment] 2023-04-07 17:27
Can  reproduce, Actually I was trying to backup from old device when i click on backup and select all things it does not open files UI. If I don't select watch history and remember positions it does open up and creates a backup.
I think issue here is when history is large it does not open up. Because on other devices i tried it opens up as history size is small.
Version 0.13.1
Android 10

**Comment by muhammad-ans** [comment] 2023-04-07 17:30
I'm not sure if history size has anything to do with it because in previous versions it worked fine.

**Comment by Beariddle** [comment] 2023-04-15 13:32
Can reproduce this issue myself as well. I tested every entry in the backup menu, and the feature only works for me when I uncheck 'watch history'. Just to be sure, I tested every single other entry, and the issue only got "fixed" whenever I uncheck 'watch history'.


Device: Poco F3 (alioth)
Android version: 12
LibreTube version: 0.14.0

**Comment by SalusVF** [comment] 2023-04-16 04:03
> Can reproduce this issue myself as well. The feature only works for me when I uncheck 'watch history'. Just to be sure, I tested every single other entry, and the issue only got "fixed" whenever I uncheck 'watch history'.
> 
> Device: Poco F3 (alioth) Android version: 12 LibreTube version: 0.14.0
> 
> Edit: I re-tested it on a different device and the backup feature did work as is intended, however the only difference was the size/length of the 'watch history' list. On my primary device, that list is astronomically larger compared to the 10-odd entries on the secondary tested smartphone.

I experienced the same on a Pixel 6 with Android 13. Tested with LibreTube 0.13.1 and 0.14. Only when I uncheck "watch history" i am propted to select the save location. If "watch history" is selected nothing happens.

**Comment by itsmmt305** [comment] 2023-04-16 05:43
oh umm
it didnt show up the first time i tapped it but when i tapped it again, it worked. i dont know now if this qualifies as a bug.. but even then like it should not require me tapping 'backup' again right.? should i close this or what now?

**Comment by SalusVF** [comment] 2023-04-16 05:52
> oh umm it didnt show up the first time i tapped it but when i tapped it again, it worked. i dont know now if this qualifies as a bug.. but even then like it should not require me tapping 'backup' again right.? should i close this or what now?

Now that you suggested that I've tried and I can tap as many times as I want. Nothing happens as long as the "watched history" is included in the backup. For me, that is still a clear bug.

**Comment by itsmmt305** [comment] 2023-04-16 15:36
oh thanks for confirming. attach a scr rec if you can.. idk, might help the dev

**Comment by RuthlessRuler** [comment] 2023-05-05 20:05
I'm facing a similar issue but for me unchecking the Bookmarks works, Unchecking Watch History works.
Trying multiple times and long pressing the Backup button on Popup button is also a hit & miss.

So probably maybe something to do with backup file taking some time to be prepared by the app (like large Watch History slowing down.

**Comment by Bnyro** [comment] 2023-05-08 14:51
Could anyone please test the latest debug builds?

**Comment by SalusVF** [comment] 2023-05-08 15:58
I have tried and it does not seem to be fixed yet. 
![screen-20230508-174321](https://user-images.githubusercontent.com/53519166/236871977-705a14f8-5917-4340-9d6e-fb34ae4bae1d.gif)

**Comment by r1klz** [comment] 2023-05-11 07:19
> oh umm it didnt show up the first time i tapped it but when i tapped it again, it worked. i dont know now if this qualifies as a bug.. but even then like it should not require me tapping 'backup' again right.? should i close this or what now?
> Screenrecorder-2023-04-16-21-02-18-914.mp4

Oh, nice. 😄 I hadn't read your comment before... But yeah, at least it's working that way for both of us.

**Comment by kyklish** [comment] 2023-06-04 09:37
v.0.15.0

1. Backup - All checked - Not works
2. Backup - Uncheck `Watch history` and `Remember position` - Works
3. Backup - All checked - Works
4. Wait 5-10 seconds
5. Backup - All checked - Not works
6. Repeat 2nd and 3rd lines, works again.

**Comment by SalusVF** [comment] 2023-06-04 14:32
> v.0.15.0, Android One v11 App: fresh install from izzyDroid repo.
> 
> 1. Backup - All checked - Not works
> 2. Backup - Uncheck `Watch history` and `Remember position` - Works
> 3. Backup - All checked - Works
> 4. Wait 5-10 seconds
> 5. Backup - All checked - Not works
> 6. Repeat 2nd and 3rd steps, works again.
> 
> App was not closed between steps above, one session.
> 
> It's very glitched bug. Uncheck some row and backup works, select all and backup works, uncheck same row again and backup not work.
> 
> Start app (no videos in watch history), backup not work, uncheck some rows (for example `Bookmarks` and `Channel groups`) and check them back immediately - backup works.

I can reproduce that also on v 0.15.0 and a Android 13. Moreover, when I try to load the generated backup file i get always this error:

`android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: subscriptionGroups.name (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(Unknown Source:2)
	at androidx.room.EntityInsertionAdapter.insert(SourceFile:8)
	at com.github.libretube.db.dao.WatchHistoryDao_Impl$5.call(SourceFile:36)
	at com.github.libretube.db.dao.WatchHistoryDao_Impl$5.call(SourceFile:5)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(SourceFile:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.media3.common.util.Util$$ExternalSyntheticLambda7.run(SourceFile:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2f4195, Dispatchers.IO]
    `

**Comment by kyklish** [comment] 2023-06-05 15:02
> > v.0.15.0, Android One v11 App: fresh install from izzyDroid repo.
> > 
> > 1. Backup - All checked - Not works
> > 2. Backup - Uncheck `Watch history` and `Remember position` - Works
> > 3. Backup - All checked - Works
> > 4. Wait 5-10 seconds
> > 5. Backup - All checked - Not works
> > 6. Repeat 2nd and 3rd steps, works again.
> > 
> > App was not closed between steps above, one session.
> > 
> > It's very glitched bug. Uncheck some row and backup works, select all and backup works, uncheck same row again and backup not work.
> > 
> > Start app (no videos in watch history), backup not work, uncheck some rows (for example `Bookmarks` and `Channel groups`) and check them back immediately - backup works.
> 
> I can reproduce that also on v 0.15.0 and a Android 13. Moreover, when I try to load the generated backup file i get always this error:
> 
> `android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: subscriptionGroups.name (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
> 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
> 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
> 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
> 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
> 	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(Unknown Source:2)
> 	at androidx.room.EntityInsertionAdapter.insert(SourceFile:8)
> 	at com.github.libretube.db.dao.WatchHistoryDao_Impl$5.call(SourceFile:36)
> 	at com.github.libretube.db.dao.WatchHistoryDao_Impl$5.call(SourceFile:5)
> 	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(SourceFile:6)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
> 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
> 	at androidx.media3.common.util.Util$$ExternalSyntheticLambda7.run(SourceFile:57)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
> 	at java.lang.Thread.run(Thread.java:1012)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f2f4195, Dispatchers.IO]
>     `

Does backup's `json` file populated? I got some errors, when I try import empty file with subscriptions. Maybe backup's file is empty?

**Comment by navkaran0305** [comment] 2023-06-28 18:46
> v.0.15.0, Android One v11 App: fresh install from izzyDroid repo.
> 
> 1. Backup - All checked - Not works
> 2. Backup - Uncheck `Watch history` and `Remember position` - Works
> 3. Backup - All checked - Works
> 4. Wait 5-10 seconds
> 5. Backup - All checked - Not works
> 6. Repeat 2nd and 3rd steps, works again.
> 
> App was not closed between steps above, one session.
> 
> It's very glitched bug. Uncheck some row and backup works, select all and backup works, uncheck same row again and backup not work.
> 
> Start app (no videos in watch history), backup not work, uncheck some rows (for example `Bookmarks` and `Channel groups`) and check them back immediately - backup works.

I can't make the backup work if it includes the `Watch history` even if I follow these steps. If I include the `Watch history` at any point, the file selector UI does not show up.

App version - 0.15.1
Android version - 13.0

**Comment by meiphoo7-Mae** [comment] 2023-07-20 04:24
Yes, the backup issue definitely has something to do with one or more large items in the backup.
Can you (I mean other users in this thread) try this:
- Go to settings, leave all boxes checked. Then press backup.
-> backup fails.
- Do not close the settings and wait one full minute, then press backup again.
-> backup succeeds.

The waiting time is apparently needed to prepare the backup.
It might be shorter depending on the contents of the backup.
After doing this I get a backup of 138.7 kB. With the first item unchecked the backup is 16.7 kB.

**Comment by navkaran0305** [comment] 2023-07-27 20:09
> Yes, the backup issue definitely has something to do with one or more large items in the backup. Can you (I mean other users in this thread) try this:
> 
> * Go to settings, leave all boxes checked. Then press backup.
>   -> backup fails.
> * Do not close the settings and wait one full minute, then press backup again.
>   -> backup succeeds.
> 
> The waiting time is apparently needed to prepare the backup. It might be shorter depending on the contents of the backup. After doing this I get a backup of 138.7 kB. With the first item unchecked the backup is 16.7 kB.

@meiphoo7-Mae Tried this and waited 5 min. before pressing backup, still no luck

App version - 0.16.1
Android version - 13.0

**Comment by S7venLights** [comment] 2023-08-27 21:56
I am only able to backup: 
Watch History
Remember Position
Bookmarks
Channel groups
and Preferences

together… (Although this works for me since I can export subscriptions and playlists separately through the other export options)

I can also backup some things independently from others eg clicking backup and just choosing subscriptions

On latest LibreTube

**Comment by catgangdev** [comment] 2023-08-29 03:45
Seems I have same issue on latest build too. Tried to restore piped libre playlist json file and getting this error


kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: 
	at okio.Okio.JsonDecodingException(SourceFile:1)
	at okio.Okio.JsonDecodingException(SourceFile:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(SourceFile:57)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(SourceFile:13)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(SourceFile:114)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(SourceFile:42)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNextToken(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(SourceFile:45)
	at com.github.libretube.obj.PipedImportPlaylistFile$$serializer.deserialize(SourceFile:1)
	at com.github.libretube.obj.PipedImportPlaylistFile$$serializer.deserialize(SourceFile:2)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio.Okio.decodeByReader(SourceFile:25)
	at okio.Okio.decodeFromStream(SourceFile:15)
	at okio.Path$Companion.importPlaylists(SourceFile:128)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$getPlaylistsFile$1$1$1.invokeSuspend(SourceFile:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f7e9e46, Dispatchers.IO]

**Comment by Unaiperezdiaz** [comment] 2023-09-18 19:28
kotlinx.serialization.MissingFieldException: Field 'index' is required for type with serial name 'com.github.libretube.db.obj.SubscriptionGroup', but it was missing at path: $.channelGroups[0]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:93)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79)
	at com.github.libretube.obj.BackupFile$$serializer.deserialize(BackupFile.kt:13)
	at com.github.libretube.obj.BackupFile$$serializer.deserialize(BackupFile.kt:13)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.internal.JsonStreamsKt.decodeByReader(JsonStreams.kt:39)
	at kotlinx.serialization.json.JvmStreamsKt.decodeFromStream(JvmStreams.kt:61)
	at com.github.libretube.helpers.BackupHelper.restoreAdvancedBackup(BackupHelper.kt:111)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$getBackupFile$1$1.invokeSuspend(BackupRestoreSettings.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@98635d0, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Field 'index' is required for type with serial name 'com.github.libretube.db.obj.SubscriptionGroup', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at com.github.libretube.db.obj.SubscriptionGroup.<init>(SubscriptionGroup.kt:7)
	at com.github.libretube.db.obj.SubscriptionGroup$$serializer.deserialize(SubscriptionGroup.kt:7)
	at com.github.libretube.db.obj.SubscriptionGroup$$serializer.deserialize(SubscriptionGroup.kt:7)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 26 more
    
Crash restoring backup on the last build of debug version

**Comment by Bnyro** [comment] 2023-09-26 10:39
Are there any changes to the situation of **exporting** backups in the most recent release (0.18.1)?

**Comment by Unaiperezdiaz** [comment] 2023-09-26 11:09
I have already tested with the last debug build, the backup restore works fine (no crashes 😄)

**Comment by SalusVF** [comment] 2023-09-30 21:24
You are right. It seems to work for me now too.

**Comment by navkaran0305** [comment] 2023-09-30 21:36
Backup working confirmed. Also tested backup integrity by restoring on another device. My approx. backup size was 580kb. Kudos to the developers 🎉🎉

**Comment by Bnyro** [comment] 2023-09-30 21:37
Neat, then we can finally close this one 🎉

**Closed by Bnyro** 2023-09-30 21:37 UTC
Labels: bug, help wanted
