### ISSUE TITLE
Automatic captions not working

### ISSUE THREAD

**Issue by AlfinJosephNJ** [libre-tube/LibreTube#6291] opened 2024-07-26 15:54 UTC
### Steps to reproduce

When playing videos the **auto generated captions doesn't show** but the captions added by the creator works fine without any issue. 

### Expected behavior

The autogenerated captions while playing videos should work when we switch the captions to autogenerated. 

### Actual behavior

Instead there is no autogenerated captions

### LibreTube version

0.24.0

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-07-28 08:11
Duplicate of https://github.com/libre-tube/LibreTube/issues/5511

**Closed by Bnyro** 2024-07-28 08:11 UTC
Labels: bug
