### ISSUE TITLE
Audio only playback doesn't respect autoplay option

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#1311] opened 2022-09-17 21:59 UTC
### Steps to reproduce

1. Have autoplay off.
2. Play any video in audio only mode
3. Wait for the video to finish
4. No matter the settings, the next video will play in audio only mode

### Expected behavior

It should stop the playback, or if the repeat option is set, replay the audio

### Actual behavior

Next video plays, and the media player still shows the previous video (the video that was playing in audio mode, before it started playing the next one)

### LibreTube version

0.5.1

### Android version

Android 12

### Other details

Samsung Galaxy A72
OneUI 4.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-18 07:49
dupe of #1157

**Closed** 2022-09-18 07:49 UTC
Labels: bug
