### ISSUE TITLE
Ignoring the camera island/notch makes harder to seek the video

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2286] opened 2022-12-07 14:28 UTC
### Steps to reproduce

1. Open a video
2. Try going to 0:00 of the video
3. You can't because the camera island is there.

### Expected behavior

Make the seek bar to start next at the camera island, without covering itself. (The best example for that, is NewPipe)

![IMG_20221207_152502](https://user-images.githubusercontent.com/76624594/206205042-32bbbb8e-24c7-4e76-ad67-4de8cb169717.jpg)
![IMG_20221207_152659](https://user-images.githubusercontent.com/76624594/206205085-40a1e864-74fb-424e-92c9-4795929e6960.jpg)

### Actual behavior

Currently it displays the bar like the camera island wasn't there, which is a big problem. 

### LibreTube version

0.9.0

### Android version

Android 13

### Other details

OnePlus 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Kruna1Pate1** [comment] 2022-12-07 15:09
Duplicate of #2261

**Closed by Kruna1Pate1** 2022-12-07 15:09 UTC
Labels: bug
