### ISSUE TITLE
Tapping in Featured (playlists) videos does not show pause/play button

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#1939] opened 2022-11-20 11:57 UTC
### Steps to reproduce

How to reproduce:

1. Subscribe to a few channels. LibreTube will show videos from these in Featured tab
2. Now tap to a video in Featured tab, it will play it and if we tap on the screen it will show Pause/Play button (so we can pause the video)
3. Now tap to the next video in Featured tab to play it.
4. Tap to screen - it will not show Pause/Play button.
5. Tap to another video in Featured tab - it will not show Pause/Play button either.
6. After tapping to a few videos it might eventually show Pause/Play button but it will then disappear again if we tap to another video.

I can upload a video if required.

### Expected behavior

Pause/Play on tap should be available when playing all videos

### Actual behavior

Pause/Play on tap doesn't appear when playing videos in Featured tab

### LibreTube version

0.8.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment] 2022-11-20 14:49
Can't reproduce, works fine for me.

**Comment by Bnyro** [comment] 2022-11-20 15:32
Same for me, a video recording would be helpful

**Comment by xIUPITERx** [comment] 2022-11-25 08:02
I have that to sometimes, if you tab very often and wait or you minimize it to the miniplayer and back it will work just fine.
The double tab for seek works for me without problems.

**Comment by Bnyro** [comment] 2023-01-14 07:31
I was able to reproduce it back then when the issue was created but now I can't anymore thus I assume it got fixed by some other commit.

**Closed by Bnyro** 2023-01-14 07:31 UTC
Labels: bug
