### ISSUE TITLE
[BUG] Share does not use selected instance

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#72] opened 2022-03-16 16:03 UTC
**Describe the bug**
The share feature does not use the selected instance.

**To Reproduce**
1. Go to a video
2. Click on Share
4. The link is generated with piped.tokhmi.xyz instead of the selected one (kavin.rocks)

**Smartphone (please complete the following information):**
 - Device: One Plus 3T
 - Android version: LineageOS 18 microg - 11.0

![Screenshot_20220316-175900_Trebuchet_1](https://user-images.githubusercontent.com/51162078/158633957-7ef1bd16-0b90-40f2-8630-2cada1c26c0e.png)

**Comment by lilcheti** [comment] 2022-03-16 16:14
This is a duplicate of #49 There is no way to get the instances clients so I just selected one of them and use it for the client. I was thinking using youtube.com instead but I'm not sure that's a good thing to do.

**Closed** 2022-03-16 16:20 UTC
Labels: bug
