### ISSUE TITLE
trends shown on first run

### ISSUE THREAD

**Issue by Sa1Gur** [libre-tube/LibreTube#3019] opened 2023-02-10 20:39 UTC
### Steps to reproduce

1. Disable home and trends.
2. Open app.
3. You still see trends in subscription tab
4. Go to Library tab
5. Return to Subscription. Now trends are gone 

### Expected behavior

No trends on subscription tab

### Actual behavior

trends shown in subscription tab on first run

### LibreTube version

0.11.1

### Android version

Android 13, Samsung Z3 Fold

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-10 20:52
You need to set the home tab to the subscriptions tab too by pressing the home icon in the navigation bar settings. Also a duplicate of https://github.com/libre-tube/LibreTube/issues/2587#issuecomment-1371529646.

**Closed by Bnyro** 2023-02-10 20:52 UTC
Labels: bug

**Comment by Sa1Gur** [comment] 2023-02-10 21:10
Thanks!
