### ISSUE TITLE
Issue When Returning From Search

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1617] opened 2022-10-20 06:14 UTC
### Steps to reproduce

1. Search for anything
2. Click back button
3. The search bar closes only
4 Click back button again
5. History tab opens
6. Click back button again
7. You'll return to the tab where you were before searching.

### Expected behavior

Let say:
- I'm on home page
- I searched for something
- Clicking back button should return to the home page with a single press of back button only

### Actual behavior

Instead, it requires multiple taps to go back to the home tab, and opens history tab for no reason.

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

> Uploaded screen recording, but that was playing as audio only 😑, so giving streamable link.
[Video Link](https://drive.google.com/file/d/1lLKCXR3-HS3ZmWOw3WyUlYwV5FLqc61j/view?usp=drivesdk)

Here's sequenced screenshots:
> - On first back gesture, only search bar closes (see screenshot 3), instead it should have gone straight to the home tab where I was before searching.

![Screenshot_20221020-111041~2](https://user-images.githubusercontent.com/87353286/196869108-8002ea5c-13e9-4c93-ab91-577b90073219.png)
![Screenshot_20221020-111057~2](https://user-images.githubusercontent.com/87353286/196869152-3f80aa32-daa0-446f-875c-669f096669f9.png)
![Screenshot_20221020-111107~2](https://user-images.githubusercontent.com/87353286/196869182-45068433-33f6-42a8-85c9-1e21c257bb99.png)
![Screenshot_20221020-111111~2](https://user-images.githubusercontent.com/87353286/196869215-7af85588-2e40-4473-972f-6c123fe8287e.png)
![Screenshot_20221020-111041~2](https://user-images.githubusercontent.com/87353286/196869686-06b5a7c0-38da-49f2-b01b-c14d94823f9b.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-10-20 11:27
Dupe of #1599

**Closed by Bnyro** 2022-10-20 11:27 UTC
Labels: bug
