### ISSUE TITLE
NullPointerException opening video

### ISSUE THREAD

**Issue by gbieging** [libre-tube/LibreTube#3389] opened 2023-03-25 18:26 UTC
### Steps to reproduce

Clicked on video in subscription list.
Don't know how to reproduce, Happened once so far

### Expected behavior

No error

### Actual behavior

App went back to start page. 
Stack trace printed:

```
java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:17)
	at androidx.room.MultiInstanceInvalidationClient$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:91)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### LibreTube version

0.13.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-25 19:06
duplicate of #3372

**Closed by Bnyro** 2023-03-25 19:06 UTC
Labels: bug

**Comment by farline99** [comment] 2023-03-26 13:20
It is not (i think) a duplicate of that issue. It has different logs. My logs are like that.

> java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:17)
	at androidx.room.MultiInstanceInvalidationClient$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:91)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
