### ISSUE TITLE
Go to the end of video if you switchback to video mode

### ISSUE THREAD

**Issue by Monirzadeh** [libre-tube/LibreTube#2862] opened 2023-01-24 18:18 UTC
### Steps to reproduce

1. play any video (go to middle of that)
2. switch to audio mode, wait until start playing
3. back to video mode again

### Expected behavior

It should continue video in video mode

### Actual behavior

Go to the end of video

### LibreTube version

0.11.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-24 18:50
duplicate of #2800

**Closed by Bnyro** 2023-01-24 18:50 UTC
Labels: bug
