### ISSUE TITLE
Automatically select best Piped instance

### ISSUE THREAD

**Issue by ehea617** [libre-tube/LibreTube#3269] opened 2023-03-08 03:15 UTC
### Describe your suggested feature

An option on the instance settings page to allow LibreTube to manage the selected Piped instance and automatically select a working instance on app launch. This would improve user experience as it would lower the amount of times needed to enter the settings and select a different instance due to the current selected instance being down, extremely slow, or broken.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-08 06:15
Duplicate of #3152

**Closed** 2023-03-08 06:15 UTC
Labels: enhancement
