### ISSUE TITLE
Option to disable/hide shorts

### ISSUE THREAD

**Issue by iwannet** [libre-tube/LibreTube#4089] opened 2023-06-24 07:53 UTC
### Describe your suggested feature

An option in the settings were you can disable/hide all shorts from showing up on your subs and home page.

This feature would be really usefull, thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-24 07:54
duplicate of #4065

**Closed by Bnyro** 2023-06-24 07:54 UTC
Labels: enhancement

**Comment by iwannet** [comment] 2023-06-24 07:55
Lol i could find the duplicate
