### ISSUE TITLE
Persist Notification Controls 

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4594] opened 2023-08-22 22:43 UTC
### Steps to reproduce

1- Play a video
2- Have a notification that can be cleared when tapping on clear notifications button

### Expected behavior

Notification controls shouldn't be affected

### Actual behavior

Notification controls dismissed

### LibreTube version

0.17.1

### Android version

Android 13

### Other details

This only happens when tapping on 'clear' button from notifications panel **and if and only if** there's a notification that could be dismissed (like the notification from the firewall in the recording below or a chat notification from telegram/signal.....).

LT notification itself can't be dismissed, but when clearing other notifications it gets cleared for some reason 

https://user-images.githubusercontent.com/50032603/262499560-b31d3f37-0354-4aef-9770-59002dad02e3.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-08-22 22:45
https://github.com/libre-tube/LibreTube/assets/50032603/b31d3f37-0354-4aef-9770-59002dad02e3

**Comment by Bnyro** [comment] 2023-08-23 06:47
Can't reproduce on Stock Android 13. I believe that's rather an Android issue as the notification is already marked as persistent and hence should not be dismissable.

**Comment by Bnyro** [comment] 2023-08-27 10:59
Closing since the behavior is controlled by Android and media notifications like LibreTube's are set to not be dismissable by default.

**Closed by Bnyro** 2023-08-27 10:59 UTC
Labels: bug, can't reproduce
