### ISSUE TITLE
The video quality is displayed incorrectly.

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2234] opened 2022-12-04 20:51 UTC
### Steps to reproduce

1.Open any video.
2.Set the quality to 1080p.
3.The quality is displayed incorrectly.

### Expected behavior

1080p should be visible.

### Actual behavior

https://user-images.githubusercontent.com/119277871/205514914-6b6bcd64-0cc6-4364-b35a-fd20d2990707.mp4

### LibreTube version

0.9.0

### Android version

Android 12

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabs-Unk** [comment] 2022-12-05 12:45
I am having same issue in both android 10 devices I do use
rog 2 and moto g5
In my case I do change from 1080 to 1440 and it do still showing like 1080

**Comment by Bnyro** [comment] 2022-12-05 19:16
dupe of #2005

**Closed by Bnyro** 2022-12-05 19:16 UTC
Labels: bug
