### ISSUE TITLE
LibreTube does not play some videos

### ISSUE THREAD

**Issue by rsssxd** [libre-tube/LibreTube#3135] opened 2023-02-20 09:55 UTC
### Steps to reproduce

LibreTube does not open some videos at all, including the background.
Sample video
https://piped.video/watch?v=ksjjOldZq2U

### Expected behavior

.

### Actual behavior

.

### LibreTube version

A13 DivestOS

### Android version

v0.12.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-20 10:01
duplicate of #3051

**Closed by Bnyro** 2023-02-20 10:01 UTC
Labels: bug
