### ISSUE TITLE
Language inconsistencies

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2311] opened 2022-12-08 23:34 UTC
### Steps to reproduce

Didn't get the chance to see what causes it exactly. It seems random, but after restarting the app it doesn't seem to happen again for some time.

### Expected behavior

All of the UI elements should be in the set language

### Actual behavior

Some assets (Navigation bar, settings...) are in the user set language (English), and some are in the system language (Mostly button labels like the ones under the video or the play all button in the playlist). When the app is restarted it seems to be back to normal.

### LibreTube version

0.9.0

### Android version

Android 13

### Other details

This issue was also in some earlier versions.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-12-09 13:56
Could be a dupe of #1445.

**Comment by pawa2401** [comment] 2022-12-10 09:36
It could be caused by the same thing, though in my case (as mentioned before) this happens seemingly randomly, and I couldn't trigger it manually.
Also in #1445 the gesture controls could be at fault.

**Comment by Bnyro** [comment] 2023-05-14 08:56
No plans to further investigate here, there's no better way to change the language so nothing can be improved.

**Closed by Bnyro** 2023-05-14 08:56 UTC
Labels: bug, priority: low
