### ISSUE TITLE
Video will not load after repeated clicks, but will display title and other info

### ISSUE THREAD

**Issue by Digitalhell666** [libre-tube/LibreTube#4696] opened 2023-09-05 14:29 UTC
### Steps to reproduce

Click selected video
Title, description and engagement info display while video screen remains black.

### Expected behavior

Click video and video begins to play

### Actual behavior

Click selected video
Title, description and engagement info display while video screen remains black. Time marker indicates 00:00 - 00:00
After repeated clicks on a random suggested video from the LT homepage the suggested video will play, but then when trying to go back to my selected video the screen remains black. 

### LibreTube version

17.1

### Android version

Android 12

### Other details

![Screenshot_20230905-102250_LibreTube](https://github.com/libre-tube/LibreTube/assets/135291660/6ba3d01a-2ce4-4efd-ba4b-92445488319c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SeerLite** [comment] 2023-09-15 18:53
Same issue on 0.18.0
Android 12

![Screenshot_20230915-155238_LibreTube.png](https://github.com/libre-tube/LibreTube/assets/21978144/1b18f648-1ea6-459a-8f9f-d90dcf63432d)

**Comment by kik-btaski** [comment] 2023-09-19 08:34
@Digitalhell666 @SeerLite 
Actually this issue is due to piped instance. Whenever i encounter this issue, i change the piped instance to some other instance in the settings, then it works. Mostly switching between kavin.rocks, lunar.icu, frontendfriendly.xyz instances works. 

When you switch instances, the videos sequence in the subscriptions screen also have some differences. That is also the issue that some instances works some not :sweat_smile: . I think these instances delays in syncing their database with youtube in their different schedules.

@Bnyro can libretube have non privacy mode to avoid using the instances ? Disable Piped proxy setting is there but i think it does not work like NewPipe app after enabling it.

**Comment by Digitalhell666** [comment] 2023-09-19 12:36
When I first encountered this issue the first thing I did was try a different instance to no real change in performance. One thing I've noticed is that if I repeatedly click on the video I want I can eventually force it to play after a lot of clicks.

**Comment by akano12** [comment] 2023-09-19 14:04
Are you still facing this problem on latest version (0.18.1)?

**Comment by kik-btaski** [comment] 2023-09-19 14:14
@akano12 
yes still facing. screen looks something like this👇

example video: https://www.youtube.com/watch?v=oRdxUFDoQe0

instance: kavin.rocks

![Screenshot_20230919-194247_LibreTube](https://github.com/libre-tube/LibreTube/assets/142499381/4661b0c2-5566-4914-bb51-cd5c52af83d8)

**Comment by kik-btaski** [comment] 2023-09-19 14:17
it then stops loading

**Comment by kik-btaski** [comment] 2023-09-22 02:29
Yes but i was thinking of non privacy mode(non proxy) just as in NewPipe so that i dont have to switch to NewPipe for a single video multiple times😅
No proxy setting is there but i think it doesnt work. Just want Libretube to be NewPipe temporary😅

**Comment by Bnyro** [comment] 2023-09-26 10:47
Closing as duplicate of https://github.com/TeamPiped/Piped/issues/2915

**Closed by Bnyro** 2023-09-26 10:47 UTC
Labels: bug, can't reproduce
