### ISSUE TITLE
Shorts end too early

### ISSUE THREAD

**Issue by FineFindus** [libre-tube/LibreTube#4633] opened 2023-08-26 15:47 UTC
### Steps to reproduce

1. Open a YouTube Short
2. Play it until the end
3. Notice how the short ends early, compared to the same short on YouTube

### Expected behavior

The Short should fully play

### Actual behavior

The short ends early ~0.5s early, so often times the last word is cut off.

### LibreTube version

0.17.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-09-14 15:25
Seems to be a duplicate of https://github.com/TeamPiped/Piped/issues/2554

**Closed by Bnyro** 2023-09-14 15:25 UTC
Labels: bug, can't reproduce
