### ISSUE TITLE
Bugs related to comments section loading

### ISSUE THREAD

**Issue by jacktheripper19** [libre-tube/LibreTube#5821] opened 2024-03-28 10:32 UTC
### Steps to reproduce

- play a youtube video.
- click on Comments
- click on a comment, if any, to check the replies.

### Expected behavior

- Comments should show up on any video.
- Replies should be shown when clicked on a comment.
- Replies should correspond to the clicked comment.

### Actual behavior

- when clicking a video, most of the time, its comments do not show up. I have to exit the app and replay it a number of times before they show up.
![Screenshot_20240328-112649](https://github.com/libre-tube/LibreTube/assets/84401946/106e2beb-ae96-4bca-b324-362efd557cea)

- when comments show up, replies are not loaded properly. for example, a comment can have 3 replies, but when clicking on said comment, the replies do no show up. I have to go back and click the comment a number of times before they show up.
![Screenshot_20240328-112320](https://github.com/libre-tube/LibreTube/assets/84401946/bc6b6165-9680-499d-8c5a-b0a5a07a3b19)
![Screenshot_20240328-112338](https://github.com/libre-tube/LibreTube/assets/84401946/44f79756-1498-497d-9873-4551213f884b)

![Screenshot_20240328-113059](https://github.com/libre-tube/LibreTube/assets/84401946/d40d4701-c233-48ac-a06a-8fa720d9d0e8)

- most of the times, replies do no correspond to the   clicked comment. For examples, when clicking a comment to check its replies, then clicking another comment, the replies from the first comment are shown again.
![Screenshot_20240328-113157](https://github.com/libre-tube/LibreTube/assets/84401946/8f8f8f39-7279-41e0-adfd-f82907a1e637)
![Screenshot_20240328-113147](https://github.com/libre-tube/LibreTube/assets/84401946/ed198db3-d27b-495f-be32-50c6afbce584)

### LibreTube version

latest 0.22.1

### Android version

Android 14

### Other details

these issues are independent from the used piped instance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-28 14:17
Duplicate of https://github.com/libre-tube/LibreTube/issues/5746

**Closed by Bnyro** 2024-03-28 14:17 UTC
Labels: bug
