### ISSUE TITLE
Crash on startup, cannot open app

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [libre-tube/LibreTube#4695] opened 2023-09-05 07:54 UTC
### Steps to reproduce

Try to launch the app

### Expected behavior

The app should open

### Actual behavior

The app exists immediately

### LibreTube version

0.17.1 F-Droid

### Android version

Android 13

### Other details

Can't provide anymore than this really. I was using the app fine until about two weeks ago but now it crashes on launch.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-09-05 10:37
Did you try anything to troubleshoot the problem (clearing data, reinstalling....)?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment] 2023-09-05 10:55
I don't really want to lose my playlists and favorites, so I'm wondering if this can be fixed somehow.

**Comment by Bnyro** [comment] 2023-09-05 11:43
Duplicate of #4491, I assume your start tab is the library?
Turn off your internet, open the app, go to settings and do the backup changes described in the issue linked above.

**Comment by akano12** [comment] 2023-09-05 11:45
> I don't really want to lose my playlists and favorites, so I'm wondering if this can be fixed somehow.
 
The crash reason is unknown so devs can't fix issues they're not aware of their cause. 

Can you try to fetch the logcat using adb?

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment] 2023-09-05 12:08
> Duplicate of #4491, I assume your start tab is the library? Turn off your internet, open the app, go to settings and do the backup changes described in the issue linked above.

Sadly the app does not open even when disconnected from WiFi and my carrier.

**Comment by Bnyro** [comment] 2023-09-10 10:17
There's no way to help without a crash log, hence there's nothing we can do for you unfortunately.

**Closed by Bnyro** 2023-09-10 10:17 UTC
Labels: bug, can't reproduce
