### ISSUE TITLE
Remember last channel group selection on app startup instead of All

### ISSUE THREAD

**Issue by matt873** [libre-tube/LibreTube#5801] opened 2024-03-24 13:49 UTC
### Describe your suggested feature

Or an option for switching default channel group.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-24 15:28
Duplicate of https://github.com/libre-tube/LibreTube/issues/5801

**Closed by Bnyro** 2024-03-24 15:28 UTC
Labels: enhancement

**Comment by matt873** [comment] 2024-03-24 21:00
> Duplicate of #5801

It leads to this issue.

**Comment by matt873** [comment] 2024-03-24 21:03
Ok this one #3558
