### ISSUE TITLE
NullPointerException for display account page

### ISSUE THREAD

**Issue by nacimgoura** [libre-tube/LibreTube#1204] opened 2022-09-01 20:08 UTC
### Steps to reproduce

I reproduce this bug when I click on this link : https://www.youtube.com/user/grafikarttv

### Expected behavior

Show the account page

### Actual behavior

```
java.lang.RuntimeException: Unable to resume activity {com.github.libretube/com.github.libretube.activities.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5230)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5269)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.NullPointerException
	at androidx.preference.R$id.toID(Unknown Source:1)
	at com.github.libretube.fragments.ChannelFragment.onCreate(ChannelFragment.kt:3)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:12)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:29)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:138)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:20)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:9)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:8)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:5)
	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:9)
	at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:1)
	at android.app.Activity.performResume(Activity.java:8466)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5200)
	... 13 more
    
```

![Screenshot_20220901-220137_LibreTube](https://user-images.githubusercontent.com/9990521/188002315-f4782126-941f-4a1d-843c-8bcfc5416672.jpg)

### LibreTube version

0.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-02 07:40
Dupe of #1075

**Closed by Bnyro** 2022-09-02 07:40 UTC
Labels: bug
