### ISSUE TITLE
Comments reply panel incorrect placement

### ISSUE THREAD

**Issue by Deathemonic** [libre-tube/LibreTube#2630] opened 2023-01-08 03:47 UTC
### Steps to reproduce

Click on the on comment you want to see the replies

![_ScreenshotFlow](https://user-images.githubusercontent.com/65948476/211179552-5e2b7ee4-b70d-4f6f-976f-867515c664e4.png)

### Expected behavior

The panel should be placed on the buttom

![Screenshot_20230108_114417](https://user-images.githubusercontent.com/65948476/211179538-ac787d2c-60cb-49e4-901a-67eede2d7b64.jpg)

### Actual behavior

The panel floats and blocks the video

![Screenshot_20230108_114616](https://user-images.githubusercontent.com/65948476/211179576-d52844de-91e1-49db-80c5-7e292d05edbc.jpg)

### LibreTube version

0.10.0

### Android version

Android 8+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-08 08:28
Dupe of #2425

**Closed by Bnyro** 2023-01-08 08:28 UTC
Labels: bug
