### ISSUE TITLE
Option to hide comments.

### ISSUE THREAD

**Issue by Lemon-in-Suspense** [libre-tube/LibreTube#2523] opened 2022-12-27 20:28 UTC
### Describe your suggested feature

Please add the option to hide all the comments of the videos (this feature exists in NewPipe).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2022-12-28 00:54
https://github.com/libre-tube/LibreTube/issues/2066#issuecomment-1336388119

**Comment by Lemon-in-Suspense** [comment] 2022-12-28 05:39
> #2066
> 
> [#2066 (comment)](https://github.com/libre-tube/LibreTube/issues/2066#issuecomment-1336388119)

No, I was actually asking for the feature to complete remove the comments from the videos (like in the NewPipe app), so that the user has to turn the comments on/off through the settings.

Necessity- This feature is necessary as we inadvertantly view some of the negative and toxic comments on the videos, which in turn, are not good for our mental health.
So, adding such a button to hide comments completely can give people an option to avoid this problem if they wish to!

**Comment by Aqwuty** [comment] 2022-12-28 06:11
Showing an alert when you click on comments is a better option.

**Comment by Lemon-in-Suspense** [comment] 2022-12-28 06:13
> Showing an alert when you click on comments is a better option.

Yeah, this is a great idea too.

**Comment by Aqwuty** [comment] 2022-12-28 06:27
I think there should be an option to hide some comments.

**Comment by Bnyro** [comment] 2022-12-28 07:17
Still a dupe of #2066

**Closed by Bnyro** 2022-12-28 07:17 UTC
Labels: enhancement
