### ISSUE TITLE
Video captions don't work

### ISSUE THREAD

**Issue by jksekai** [libre-tube/LibreTube#6463] opened 2024-09-07 10:47 UTC
### Steps to reproduce

1. open any video which has captions avaliable
2. click on the gear icon in the video screen and enable captions of choice

### Expected behavior

There should be captions at the bottom of the screen

### Actual behavior

absolutely nothing happens, regardless of the caption settings. 

### LibreTube version

0.25.2 (57)

### Android version

Android 12

### Other details

the issue still exists whether system caption style is enabled or not

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-09-07 14:18
Duplicate of https://github.com/libre-tube/LibreTube/issues/5511

**Closed by Bnyro** 2024-09-07 14:18 UTC
Labels: bug
