### ISSUE TITLE
Crash on reading comments

### ISSUE THREAD

**Issue by Amirraan** [libre-tube/LibreTube#3201] opened 2023-02-27 06:50 UTC
### Steps to reproduce

When I am reading the comments, the app freezes and after restarting, it gives the following error

java.lang.IndexOutOfBoundsException: toIndex = 55
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
	at java.util.ArrayList.subList(ArrayList.java:1008)
	at com.github.libretube.ui.fragments.CommentsMainFragment$onViewCreated$3.invoke(CommentsMainFragment.kt:99)
	at com.github.libretube.ui.preferences.MainSettings$$ExternalSyntheticLambda4.onChanged(R8$$SyntheticClass:12)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:30)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:56)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:15)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:19)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
    

### Expected behavior

. 

### Actual behavior

. 

### LibreTube version

0.12.0

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-21 18:44
Can't reproduce on any of my devices, thus I believe it's been fixed within the last updates.

**Closed by Bnyro** 2023-03-21 18:44 UTC
Labels: bug, can't reproduce
