### ISSUE TITLE
exit full-screen on swipe-down

### ISSUE THREAD

**Issue by laur89** [libre-tube/LibreTube#575] opened 2022-06-20 10:44 UTC
### Describe your suggested feature

As-is:
To exit full-screen mode, user needs to click the icon in the bottom-right corner. No other method exists.

To-be:
Swiping down whilst in full-screen mode exits it. 

### Other details

Somewhat related: #24, #562

With all this, there would be 3 modes for exiting full-screen mode:
- rotate phone (https://github.com/libre-tube/LibreTube/issues/24)
- click the icon (implemented)
- swipe down (this request)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-06-26 15:54
dupe of #166

**Closed by Bnyro** 2022-06-26 15:54 UTC
Labels: enhancement, VideoPlayer
