### ISSUE TITLE
Add more controls in notification

### ISSUE THREAD

**Issue by tvnmguy** [libre-tube/LibreTube#2075] opened 2022-11-26 10:51 UTC
### Describe your suggested feature

Add loop option in notification and also replace black square button with × button 

### Other details

![IMG_20221126_151320](https://user-images.githubusercontent.com/116799295/204085037-12a8908e-ebbb-4ed4-bff5-a79ebcb6848d.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-04 11:41
Dupe of #1891

**Closed** 2022-12-04 11:41 UTC
Labels: enhancement
