### ISSUE TITLE
App Backup Isn't Working

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#3719] opened 2023-05-06 00:58 UTC
### Steps to reproduce

1. Go to Settings
2. Backup & Restore
3. App Backup → Backup

### Expected behavior

It should show the files screen where to save the backup file

Note: The Restore option is working normally

### Actual behavior

Nothing happens

### LibreTube version

0.14.1

### Android version

Android 11 (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-06 05:34
Dupe of #3427

**Closed by Bnyro** 2023-05-06 05:34 UTC
Labels: bug

**Comment by RickyM7** [comment] 2023-05-06 13:17
> 

I searched for dupes but didn't find this issue, sorry

**Comment by Bnyro** [comment] 2023-05-06 14:41
No worries, happens
