### ISSUE TITLE
Latest test version quickly skips silent sections

### ISSUE THREAD

**Issue by rsssxd** [libre-tube/LibreTube#2748] opened 2023-01-17 20:41 UTC
Latest test version quickly skips silent sections. There is no setting to disable this feature

**Comment by Bnyro** [comment] 2023-01-17 20:44
It's contained in the playback speed options when playing a video, dupe of #2744

**Closed by Bnyro** 2023-01-17 20:44 UTC
Labels: bug

**Comment by rsssxd** [comment] 2023-01-17 21:03
@Bnyro 

I know, but it won't do any good. Please check if there is a strange disorder.

The video and audio are suddenly progressing.

**Comment by Bnyro** [comment] 2023-01-17 21:08
https://github.com/libre-tube/LibreTube/blob/master/CODE_OF_CONDUCT.md#our-standards

**Comment by rsssxd** [comment] 2023-01-17 21:14
The settings you mentioned won't do anything. This is giving false information to the user and not accepting responsibility.

This is more against the rules.

**Comment by Bnyro** [comment] 2023-01-17 21:25
I already redirected you to the proper issue for it, tagging or blaming me doesn't make it better.
