### ISSUE TITLE
Subscriptions feed does not show all videos from subscriptions

### ISSUE THREAD

**Issue by An-anonymous-coder** [libre-tube/LibreTube#6717] opened 2024-11-11 18:11 UTC
### Steps to reproduce

1. Go to `Settings > Instance`
2. Toggle on "Disable Piped proxy"
3. Go to Subscriptions tab
4. Refresh the feed

### Expected behavior

All recent uploads from subscriptions should show up.

### Actual behavior

Some recent uploads from some subscriptions (Fireship and Side of Burritos for me) do not show up. 

### LibreTube version

0.25.2

### Android version

Android 15 (GrapheneOS 2024110700)

### Other details

These uploads do show up in NewPipe, Tubular, and FreeTube. 

If you need extra information, I will happily provide it. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FineFindus** [comment] 2024-11-11 18:16
Duplicate of https://github.com/libre-tube/LibreTube/issues/6520 and https://github.com/TeamPiped/Piped/issues/1130

**Closed** 2024-11-11 18:25 UTC
Labels: bug

**Comment by Bnyro** [comment] 2025-01-10 16:36
Local feed extraction added in https://github.com/libre-tube/LibreTube/pull/6938, see https://github.com/libre-tube/LibreTube/issues/6875.
