### ISSUE TITLE
Notification title not visible

### ISSUE THREAD

**Issue by mjain234** [libre-tube/LibreTube#488] opened 2022-06-13 06:34 UTC
I was just playing songs through libretube and when I pulled down notification, I saw that the title is not visible though the music bar appears which was not available in previous version of this app, is it a bug or it is in beta stage? I m in Android 12
https://user-images.githubusercontent.com/70900505/173292977-cdc9a38d-3897-498f-8ece-543e46d73b11.mp4

**Comment by Bnyro** [comment] 2022-06-13 06:43
Thats because I couldn't find a good way to make it work yet (I only added it alreaey because we're still in beta). It's a dupe of #377 btw :)

**Closed** 2022-06-13 06:44 UTC
