### ISSUE TITLE
Shorts blocker/filter

### ISSUE THREAD

**Issue by halvabner** [libre-tube/LibreTube#4065] opened 2023-06-22 11:03 UTC
### Describe your suggested feature

I would like to have any way to remove YouTube Shorts from appearing when I search for videos.
I would like to be able to just set this once and not every time when I search.

If it sounds oddly specific, you should know that many people dislike this short video format and choose to block it in custom desktop clients.
Much thanks in advance ^_^

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-22 13:35
not planned, duplicate of #3836

**Comment by Bnyro** [comment] 2023-06-22 13:36
Since there's no API support for this, adding it on client side could cause various issues

**Closed by Bnyro** 2023-06-22 13:35 UTC
Labels: enhancement

**Comment by iwannet** [comment] 2023-06-24 07:58
Yeahi would also like this
