### ISSUE TITLE
Backup & Restore problem

### ISSUE THREAD

**Issue by MAAB-FW** [libre-tube/LibreTube#4665] opened 2023-08-30 04:20 UTC
### Steps to reproduce

1. start app
2. go to settings
3. Backup & Restore
4. Restore
5. backup.json file blurry not selectable (issue here)

### Expected behavior

json file will be selected and settings will be restored perfectly. 

### Actual behavior

backup.json file doesn't work to select for restore.

### LibreTube version

0.17.1 (latest)

### Android version

android 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-30 07:25
Duplicate of #3427

**Closed by Bnyro** 2023-08-30 07:25 UTC
Labels: bug
