### ISSUE TITLE
[FEATURE] User experience enhancement

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#71] opened 2022-03-16 14:04 UTC
(1) Double tap to seek forward and backward

(2) Pinch to zoom for full scren

(3) Landscape video watching option without enabling auto rotation

(4) Swipe gesture for volume and brightness

(5) Video chapters and comments

(6) PiP functionality

(7) Touch to open links from discription

(8) Default video resolution for mobile data and wifi

(9) An option to open video from youtube

(10) SponsorBlock and Return YouTube Dislike integration

**Comment by hitanol** [comment] 2022-03-20 11:36
Priorizar point 10 bless you libretube

**Comment by alexanderadam** [comment] 2022-04-01 07:37
There's no point in tracking 10 issues in a single issue.
Also point 10 is a duplicate of #71

**Comment by Bnyro** [comment] 2022-06-09 07:36
everything that was planned from the list got added, therefore closing it.
please open issues with only one suggestion per issue next time

**Closed by Bnyro** 2022-06-09 07:36 UTC
Labels: enhancement
