### ISSUE TITLE
View comments in audio playback mode

### ISSUE THREAD

**Issue by balaraz** [libre-tube/LibreTube#5609] opened 2024-02-07 18:43 UTC
### Describe your suggested feature

Add a button to view comments without leaving the audio-only mode.

### Other details

It is very inconvenient that to view comments you need to return to the video mode.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-02-07 19:12
Duplicate of https://github.com/libre-tube/LibreTube/issues/5037

**Closed by Bnyro** 2024-02-07 19:12 UTC
Labels: enhancement
