### ISSUE TITLE
Feature Request: Downloading Subtitles

### ISSUE THREAD

**Issue by notBradPitt** [libre-tube/LibreTube#2507] opened 2022-12-26 09:31 UTC
### Describe your suggested feature

Recently switched from NewPipe to LibreTube and I'm loving it so far. One thing I noticed is that there's no option to download subtitles and there's multiple option for audio of the same bitrate. Perhaps this feature could be implemented in the future 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-26 11:03
Duplicate of #1700

**Closed by Bnyro** 2022-12-26 11:03 UTC
Labels: enhancement
