### ISSUE TITLE
Downloads are slow and/or don't work

### ISSUE THREAD

**Issue by mtris** [libre-tube/LibreTube#456] opened 2022-06-11 06:32 UTC
Dear LibreTube Team: This app is great. Its clever how you're not directly connected to Google. I do have a question/issue regarding the download button on a video page. I click the download cloud, the second screen pops up to select the format. But, when I click the download button on that screen, the dialog screen disappears but nothing downloads. Any suggestions/support is very appreciated. Thank you for your consideration. Sincerely,

**Comment by Bnyro** [comment] 2022-06-11 06:35
Which android version are you on?

**Comment by mtris** [comment] 2022-06-11 07:03
Hello: I tried it on 9 and 10 with the same result. Thanks for the reply

**Comment by Bnyro** [comment] 2022-06-11 07:59
Hmm, that's weird, you don't even get a notification?

**Comment by Bnyro** [comment] 2022-06-11 07:59
and you selected an audio and a video format/quality in the dropdown menu?

**Comment by mtris** [comment] 2022-06-11 08:14
Correction: After choosing the audio/video dropdown, I click download. The cloud icon appears in my status bar. With '"LibreTube" and "Downloading" u see the 'wait' line continuously looping, without downloading. After several minutes, it will ding, and the status changes to "Download failed. failure"

**Comment by Bnyro** [comment] 2022-06-11 08:24
Hmm, could you try it with the latest CI builds?

**Comment by mtris** [comment] 2022-06-11 08:48
I'd try. I apologize, I am not sure what CI builds are

**Comment by Bnyro** [comment] 2022-06-11 09:29
Try this here: https://github.com/libre-tube/LibreTube/actions/runs/2477633507
just download the "app", unzip it and install your arch
and it would be nice if you could try to downloads audio only once and once audio and video

**Comment by Bnyro** [comment] 2022-06-16 10:02
closing because I think its fixed in CI builds

**Comment by vehosah** [comment] 2022-06-16 19:33
I tried the clip, I still can't download anything

**Comment by Bnyro** [comment] 2022-06-16 20:02
you gave LibreTube the storage permissions it asked for?

**Comment by vehosah** [comment] 2022-06-16 20:02
> you gave LibreTube the storage permissions it asked for?

Yes

**Comment by toas-koas** [comment] 2022-08-14 07:08
The same thing happens to me
A notification appears but nothing happens
Version 0.4.2
Android 12 19-20220712-dos-taimen
Pixel 2XL

**Comment by toas-koas** [comment] 2022-08-14 07:24
The same thing happens to me
A notification appears No progress bar appears. After some time, the message appears that the download is finished. But the video is nowhere to be found
Version 0.4.2
Android 12 19-20220712-dos-taimen
Pixel 2XL

**Comment by toas-koas** [comment] 2022-08-14 07:24
The same thing happens to me
A notification appears No progress bar appears. After some time, the message appears that the download is finished. But the video is nowhere to be found
Version 0.4.2
Android 12 19-20220712-dos-taimen
Pixel 2XL

**Comment by Mrnofish** [comment] 2022-08-18 21:48
Same: notification appears, no download in the folder. LineageOS 18.1 (Android 11)

While there's no related entry in the changelog, I'll test again when 0.5.0 hits F-Droid, just in case.

**Comment by Essasetic** [comment] 2022-08-25 11:06
Tested 0.5.0 on my OnePlus Nord 2 (OxygenOS 12).

Can confirm the issue is still there.

**Comment by ulrich321** [comment] 2022-08-28 07:15
I'm using android 11, having the same issue, it says it's downloading, the. The download disappears.

**Comment by warpdesign** [comment] 2022-09-09 19:08
Same problem (Android 13): it's very slow, and once I get the `download finished` notification the destination folder is desperately empty (yes, I have give the necessary permissions).

**Comment by Bnyro** [comment] 2022-09-23 13:12
Closing this with in-app downloads introduced by 0.6.0

**Closed by Bnyro** 2022-09-23 13:12 UTC
Labels: bug, help wanted

**Comment by warpdesign** [comment] 2022-09-23 15:00
I updated to 0.6.0 and it's still not working for me: I attempted to download the audio for some video. I choose `audio` then `126 kbps M4A`.

A notification appeared with a progress bar: when it finished, the notification disappeared and that's it. I was expecting to see a "download finished" notification but none appeared. I looked into the `downloads/LibreTube` folder (I guess it's supposed to be downloaded here?) but it was empty.

**Comment by Bnyro** [comment] 2022-09-23 15:03
Downloads are now located inside the data of the app, which means that you have to navigate to library -> downloads .

You should be able to play your downloaded media there afterwards ;)

**Comment by warpdesign** [comment] 2022-09-23 15:29
Unfortunately this does not help: `Library -> Downloads` is also empty. Not that I did not register/log in: is it needed?

Also, does it mean that files downloaded can only be accessed by LibreTube and no other apps?

**Comment by Bnyro** [comment] 2022-09-23 15:39
1. Registering and logging in is not needed
2. Yes they can only be watched inside the app. That was needed to get rid of the storage permissions and make it easier for users to trust the app. However, downloaded files can be copied manually from `Android/data/com.github.libretube`.

**Comment by Bnyro** [comment] 2022-09-23 15:39
Might be #1353

**Comment by warpdesign** [comment] 2022-09-23 16:20
Ok, so I tried downloading a video with audio, selecting both an audio & a video codec/quality (btw: would be great if the first one was automatically selected: having to select a code each & every time is painful).

I can now see a 55Mb file in `Library -> Downloads`  but it won't play: clicking on it shows the player but the duration is "00:00", so clicking on play button does nothing.

**Comment by Mrnofish** [comment] 2022-09-24 04:32
> Yes they can only be watched inside the app. That was needed to get rid of the storage permissions and make it easier for users to trust the app

Ouch! I was patiently waiting for LibreTube to get to a point where I can finally ditch NewPipe, but having to copy files manually would be no good.

My main use case for the download feature in a YouTube client, is to save the audio locally, so it can be then played as a "local folder" podcast by AntennaPod, which unfortunately has no meaningful support for YT channels.

Even using yt-dlp, which has a simple, open source, Android front-end that makes it tolerable, is less fiddly than fishing stuff from Android/data.
