### ISSUE TITLE
Doesn't video open app when click in notification

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1244] opened 2022-09-09 15:02 UTC
### Steps to reproduce

1. Start playing a video in libretube
2. Go back to home or other app.
3. Click on notification.

### Expected behavior

Should open video in app.

### Actual behavior

Nothing happens. Literally nothing.

### LibreTube version

0.5.1

### Android version

Android 9

### Other details

Not sure if it is actually bug. But it should open in app when I click.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-09 16:07
dupe of #1113

**Closed by Bnyro** 2022-09-09 16:07 UTC
Labels: bug

**Comment by rozari0** [comment] 2022-09-09 18:54
> dupe of #1113

This isssue is not in latest alpha btw. :)

Thanks for this awesome client.
