### ISSUE TITLE
crash while playing a video in background (audio only) you play another video (video mode)

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#5960] opened 2024-05-01 20:42 UTC
### Steps to reproduce

1. Play a video in backgroud (audio only)
2. While the audio is playing, open another video (not audio only)

### Expected behavior

The second video will play

### Actual behavior

Crash

### LibreTube version

0.23.0

### Android version

13

### Other details

```
java.lang.RuntimeException: Unable to stop service com.github.libretube.services.OnlinePlayerService@f0419b: java.lang.IllegalArgumentException: Receiver not registered: androidx.media3.common.util.NetworkTypeObserver$Receiver@32b5938
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4706)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: androidx.media3.common.util.NetworkTypeObserver$Receiver@32b5938
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1836)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
	at com.github.libretube.services.OnlinePlayerService.onDestroy(SourceFile:34)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4686)
	... 9 more
    
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-05-01 20:52
Duplicate of https://github.com/libre-tube/LibreTube/issues/5958

**Closed as completed by Bnyro** 2024-05-01 20:52 UTC
Labels: bug
