### ISSUE TITLE
Downloading error 

### ISSUE THREAD

**Issue by harshkai** [libre-tube/LibreTube#6437] opened 2024-09-03 01:58 UTC
### Steps to reproduce

Example:- when I want to download the any video and I clicked on download button that show me no any result to download the video 
![Screenshot_20240903_072636](https://github.com/user-attachments/assets/70e90a13-d117-4b67-b07b-344b01ba7659)
![Screenshot_20240903_072630](https://github.com/user-attachments/assets/f79400dc-1b3a-43df-9dd3-a8801e95a653)

### Expected behavior

Downloading function may not be working 

### Actual behavior

Download 

### LibreTube version

0.25.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-09-03 08:07
Duplicate of https://github.com/libre-tube/LibreTube/issues/6402

**Closed by Bnyro** 2024-09-03 08:07 UTC
Labels: bug
