### ISSUE TITLE
New APKs don't seem to be compiled correctly

### ISSUE THREAD

**Issue by chemicalzen** [libre-tube/LibreTube#5406] opened 2023-12-30 17:11 UTC
### Steps to reproduce

1. Downloaded universal apk posted today.
2. Attempt to either update previous installation or install fresh.
3. Package installer either crashes or completes without installing/updating.

### Expected behavior

App should install/update correctly.

### Actual behavior

App does not install or update when apk is launched.

### LibreTube version

0.21.0

### Android version

Android 13

### Other details

Running on CalyxOS, hasn't been a problem before tho

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-12-31 20:20
Closing as it's not LibreTube specific then.

**Closed by Bnyro** 2023-12-31 20:20 UTC
Labels: bug, can't reproduce

**Comment by darkenedcolossal** [comment] 2024-02-11 01:53
> Closing as it's not LibreTube specific then.

To me, it seems the problem is LibreTube + Pixel 6 - 7 specific. All the mentioned issues involve these phones.
Maybe this `adb logcat`-output of from the failed install helps:
```
02-11 02:41:07.367 25469 25469 E AndroidRuntime: FATAL EXCEPTION: main
02-11 02:41:07.367 25469 25469 E AndroidRuntime: Process: com.google.android.packageinstaller, PID: 25469
02-11 02:41:07.367 25469 25469 E AndroidRuntime: java.lang.RuntimeException: Could not copy bitmap to parcel blob.
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.graphics.Bitmap.writeToParcel(Bitmap.java:2271)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeParcelable(Parcel.java:2584)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.packageinstaller.PackageUtil$AppSnippet.writeToParcel(PackageUtil.java:151)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeParcelable(Parcel.java:2584)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeValue(Parcel.java:2485)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeValue(Parcel.java:2362)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeArrayMapInternal(Parcel.java:1298)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Bundle.writeToParcel(Bundle.java:1389)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeBundle(Parcel.java:1367)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.content.Intent.writeToParcel(Intent.java:11807)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Parcel.writeTypedObject(Parcel.java:2203)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2077)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5615)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5573)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:6071)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:6038)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.packageinstaller.PackageInstallerActivity.startInstall(PackageInstallerActivity.java:701)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.packageinstaller.PackageInstallerActivity.lambda$bindUi$0(PackageInstallerActivity.java:479)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.packageinstaller.PackageInstallerActivity.$r8$lambda$RCIm8wl1VPqdfQgkgmrBIDbuvOQ(PackageInstallerActivity.java:0)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.packageinstaller.PackageInstallerActivity$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.packageinstaller.AlertController$ButtonHandler.handleMessage(AlertController.java:144)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:294)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8248)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-11 02:41:07.367 25469 25469 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
Installing via adb works indeed, too.

**Comment by rose-reaper** [comment] 2024-02-22 10:38
I have this exact same issue on a Pixel 8 pro.
