### ISSUE TITLE
Exception When Playing Multiple Videos Continuously

### ISSUE THREAD

**Issue by dhananroy** [libre-tube/LibreTube#6299] opened 2024-07-29 03:07 UTC
### Steps to reproduce

- Start video playback.
- Switch to another video before the current video finishes.
- Repeat the process with a few more videos (3-4 times).
- Observe the exception/error.

### Expected behavior

The application should handle multiple video transitions smoothly without throwing exceptions or disrupting playback.

### Actual behavior

An exception occurs after switching between 3-4 videos. This exception prevents further playback and may require restarting the application.
![Screenshot_2024-07-29-08-25-26-231_com github libretube](https://github.com/user-attachments/assets/34beb5ea-d7d6-4529-9828-6b3901863975)

### LibreTube version

0.24.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Loklann** [comment] 2024-07-29 08:46
Hi, I get the exact same error whenever I try to play any video, wether or not I've watched other videos before. This started happening about 12hrs ago. I had never seen that error before.
![Screenshot_20240729-104631_LibreTube](https://github.com/user-attachments/assets/28202850-03c2-4ac4-bd2d-922176caa5c7)

**Comment by Bnyro** [comment] 2024-07-29 08:48
Duplicate of https://github.com/TeamPiped/Piped/issues/3739

**Closed by Bnyro** 2024-07-29 08:48 UTC
Labels: bug, can't reproduce
