### ISSUE TITLE
Adding a channel to channel group duplicates it

### ISSUE THREAD

**Issue by Fxsch** [libre-tube/LibreTube#5072] opened 2023-10-31 08:24 UTC
### Steps to reproduce

1. Edit channel group
2. Add a channel

### Expected behavior

Channel group should just get edited

### Actual behavior

Channel group gets duplicated. Restarting the app fixes it and the channel group will only be there once again with the added channel. This doesn't happen when removing a channel from the group.

### LibreTube version

0.19.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-10-31 10:04
Duplicate of https://github.com/libre-tube/LibreTube/issues/4914 and fixed in https://github.com/libre-tube/LibreTube/pull/5010

**Closed** 2023-10-31 10:03 UTC
Labels: bug, duplicate
