### ISSUE TITLE
Temporarily Disable Sponsor Block Button Missing

### ISSUE THREAD

**Issue by KaiserCalm** [libre-tube/LibreTube#3355] opened 2023-03-23 11:09 UTC
### Steps to reproduce

1. Open a video that contains sponsor block segments.
2. Button does not show up.

### Expected behavior

The button would show up and allow pausing add skipping for the length of the video

### Actual behavior

The button is replaced by what I can only imagine is the autoplay button.

### LibreTube version

0.12.1

### Android version

DivestOS 20.0 Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-23 14:29
duplicate of #3288

**Comment by Bnyro** [comment] 2023-03-23 14:29
duplicate of #3288

**Closed by Bnyro** 2023-03-23 14:29 UTC
Labels: bug
