### ISSUE TITLE
Error Deleting History

### ISSUE THREAD

**Issue by mcplayeraz** [libre-tube/LibreTube#2994] opened 2023-02-08 05:28 UTC
### Steps to reproduce

1.Open the history. 
2.Click the icon of bin. 
3.The program exits itself. 

### Expected behavior

An error should not occur. 

### Actual behavior

java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.github.libretube.ui.adapters.WatchHistoryAdapter.onBindViewHolder(WatchHistoryAdapter.kt:5)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:24915)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:39)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24915)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1045)
	at android.view.View.measure(View.java:24915)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3458)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2500)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1994)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8479)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1256)
	at android.view.Choreographer.doCallbacks(Choreographer.java:995)
	at android.view.Choreographer.doFrame(Choreographer.java:887)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1224)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1087)
    

### LibreTube version

0.11.1

### Android version

Android 10

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-08 06:21
Duplicate of #2860

**Closed by Bnyro** 2023-02-08 06:21 UTC
Labels: bug
