### ISSUE TITLE
Add Libretube to the Accrescent app store.

### ISSUE THREAD

**Issue by guilamoff** [libre-tube/LibreTube#3782] opened 2023-05-15 16:46 UTC
### Describe your suggested feature

Could you add your LibreTube application to the new Accrescent application store. 
Accrescent is an open-source, next generation application store and is very easy to use. Here is the link https://accrescent.app/features

Sincerely

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2023-05-15 16:50
Duplicate of #2756

**Closed by FireMasterK** 2023-05-15 16:50 UTC
Labels: enhancement
