### ISSUE TITLE
Incorrect font size in Russian in the menu under the video

### ISSUE THREAD

**Issue by farline99** [libre-tube/LibreTube#2953] opened 2023-02-03 09:28 UTC
### Steps to reproduce

1. Open LibreTube
2. Enable Russian interface language
3. Start some video
4. See incorrect Russian fonts in menu under video

### Expected behavior

Correct fonts

### Actual behavior

Incorrect fonts

### LibreTube version

0.11.1

### Android version

ArrowOS Android 12.1

### Other details

Some text is too big, something is small.

![Screenshot_20230203-122054_LibreTube_1](https://user-images.githubusercontent.com/100877226/216563110-e315d251-66b4-4191-bf05-55a9c8a34ad1.png)
![Screenshot_20230203-122032_LibreTube_1](https://user-images.githubusercontent.com/100877226/216563114-bdb286a7-50db-4ea8-b73a-084d537fa6f8.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-03 11:20
Duplicate of #2275

**Closed by Bnyro** 2023-02-03 11:20 UTC
Labels: bug
