### ISSUE TITLE
Missing font since v0.26.0

### ISSUE THREAD

**Issue by cooolgamer** [libre-tube/LibreTube#6877] opened 2024-12-14 14:04 UTC
### Steps to reproduce

Open the app, the font is missing

### Expected behavior

The text should be readable with actual characters

### Actual behavior

All characters are replaced with [], the app itself works, but it's very hard to navigate

### LibreTube version

0.26.0

### Android version

Android 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-12-14 16:59
Can't reproduce, thus Android 6 specific. There are no plans for explicit support for legacy Android versions, thus that's out of scope.

**Closed by Bnyro** 2024-12-14 16:59 UTC
Labels: bug

**Comment by cooolgamer** [comment] 2024-12-20 17:35
While I understand that Android is pretty old, is there at least a way to know which font is used now?
My phone is rooted so I can add the missing font so I can continue watching youtube on it, since libretube was a great way to watch youtube on old devices like this

**Comment by cooolgamer** [comment] 2024-12-20 18:23
Update: after messing around, I noticed that the [] characters issue only apply in the English language, I switched to French and it displays correctly, as I'm French, I can still use the app as nothing happened, but that's a weird issue

**Comment by FatVenom** [comment] 2025-01-17 13:26
Hello Sir
I faced a similar issue on my Android 5 device 
I able to resolve to it 
After creating a separate translation string for English in 
Android Studio.
Please add a translation string for English language
