### ISSUE TITLE
Split shorts to own tab in subscription feed

### ISSUE THREAD

**Issue by llloom** [libre-tube/LibreTube#2983] opened 2023-02-06 19:23 UTC
### Describe your suggested feature

It would be nice to split shorts into a separate tab in the subscription feed, similar to how they are presented on the channel page where the non-short tab is default. Shorts otherwise have a tendency to bury "actual" videos / makes it harder to see when you've got an "actual" new video in your feed.

Optionally there could be 3 tabs ("all", "videos", "shorts") and a settings option for choosing which of them should be default.

### Other details

Similar to issue #2325 / PR #2533, but for the subscription feed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2023-02-06 19:42
Dupe of ...

**Comment by Bnyro** [comment] 2023-02-06 19:48
Isn't that what's already added since #2533?

**Comment by xIUPITERx** [comment] 2023-02-06 19:51
I think they want a separate tab for shorts.

**Comment by llloom** [comment] 2023-02-06 19:51
Yes, sorry. It's a dupe of #2325, got confused by it being marked as done by PR #2533 and me not having the functionality even though there has been a release since then.

Turns out the version in F-Droid just hasn't been updated. Sorry.

**Comment by Bnyro** [comment] 2023-02-06 19:53
No worries, happens

**Closed** 2023-02-06 19:52 UTC
Labels: enhancement
