### ISSUE TITLE
Watch Later list

### ISSUE THREAD

**Issue by HomemadeAdvanced** [libre-tube/LibreTube#2496] opened 2022-12-25 12:41 UTC
### Describe your suggested feature

Possibility to add a Video to 'Watch Later' (predefined)

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-25 12:58
Dupe of #1710

**Closed by Bnyro** 2022-12-25 12:58 UTC
Labels: enhancement
