### ISSUE TITLE
Audio mode won't play ("source error")

### ISSUE THREAD

**Issue by DarkLord76865** [libre-tube/LibreTube#3942] opened 2023-06-07 09:56 UTC
### Steps to reproduce

1. open app
2. search for and open this video: [video](https://www.youtube.com/watch?v=PUlQNsl4Qvk)
3. switch to audio mode

### Expected behavior

After switching to audio mode, the audio playback should start/continue.

### Actual behavior

After switching to audio mode, nothing happens for a few seconds (slider stays at 0). Then the "Source error" popup message appears.

### LibreTube version

0.15.0

### Android version

Android 9 (EMUI 9.1.0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-07 10:02
Duplicate of #3808

**Closed by Bnyro** 2023-06-07 10:02 UTC
Labels: bug
