### ISSUE TITLE
[FEATURE] Add custom instance

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#66] opened 2022-03-15 10:57 UTC
Will there be an option for adding a custom selfhosted instance?

**Comment by rimthekid** [comment] 2022-03-15 11:00
Yes I'll add it duplicate of #52

**Comment by IceDBorn** [comment] 2022-03-15 11:04
I can look into it, you accept PRs right?

**Comment by rimthekid** [comment] 2022-03-15 11:06
Yes I appreciate it thanks!

**Closed** 2022-03-15 11:07 UTC
Labels: enhancement
