### ISSUE TITLE
Instance tester

### ISSUE THREAD

**Issue by Elkellympia** [libre-tube/LibreTube#3457] opened 2023-03-30 19:10 UTC
### Describe your suggested feature

Since sometimes for some users finding a good instance for them is hard, im thinking of a button inside the instance sections inside of config, that would attempt to download a 2mb video with every instance avaliable and compare the time results, so the user can choose which instance is faster at the given time and location, this is a problem i encounter myself sometimes, and that would be a really fast way to know which instance is the best for me. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-31 05:45
Duplicate of #3152

**Closed by Bnyro** 2023-03-31 05:45 UTC
Labels: enhancement
