### ISSUE TITLE
Toggleable Trending. 

### ISSUE THREAD

**Issue by Katkittykatt** [libre-tube/LibreTube#2911] opened 2023-01-30 12:02 UTC
### Describe your suggested feature

Please add a button for toggling the trending videos on or off. 
The empty space can be replaced with videos from creators that are being followed or suggestions for similar ones. 

### Other details

In addition the suggestions can also be be toggled on or off. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-30 12:09
Duplicate of #2612

**Closed as not planned by Bnyro** 2023-01-30 12:09 UTC
Labels: enhancement
