### ISSUE TITLE
Autoplay only in playlist.

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#2082] opened 2022-11-26 14:27 UTC
### Describe your suggested feature

I know of #610
If you select ``play all`` in the playlist section it should override the global autoplay setting (or add an third option in the settings: ``off`` - ``only in playlists`` - ``on``) and allow it to autoplay until the playlist is at an end. To accomplish this you would have to add an marker in the queue to save which videos are from the playlist and which are feature videos based on the playlist. 
If you you manually add an video to the queue it either: resolve the playlist in the queue or even better treat the added video as if it were part of the playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-11-26 15:54
![Screenshot_20221126-165256_Spotify.jpg](https://user-images.githubusercontent.com/97352673/204097448-57447799-6a57-4ef3-92d5-5277c950bd77.jpg)
 
The implementation from Spotify is pretty neat.

**Comment by Bnyro** [comment] 2022-11-26 17:33
dupe of #1810 I guess

**Closed by Bnyro** 2022-11-26 17:33 UTC
Labels: enhancement
