### ISSUE TITLE
Audio mode video name and image don't change

### ISSUE THREAD

**Issue by DarkLord76865** [libre-tube/LibreTube#3941] opened 2023-06-07 09:49 UTC
### Steps to reproduce

1. open app
2. open any video
3. click on audio mode
4. wait for the video to finish
5. autoplay starts the next video
6. its' audio starts

### Expected behavior

When the second video starts (its' audio), the title and image in the player should change to match the ones of the new video.

### Actual behavior

When the second video starts (its' audio), the title and image don't change. So the audio of the second video is playing, but the player is displaying the title and image of the first video.

### LibreTube version

0.15.0

### Android version

Android 9 (EMUI 9.1.0)

### Other details

I apologize if this is a duplicate of the existing issue. I searched and couldn't find it in the list of issues.
From my testing it happens on any video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-07 10:03
Duplicate of #3874

**Closed by Bnyro** 2023-06-07 10:03 UTC
Labels: bug
