### ISSUE TITLE
playing notification bar doesn't work

### ISSUE THREAD

**Issue by Butterfly585411** [libre-tube/LibreTube#6233] opened 2024-07-14 09:35 UTC
### Steps to reproduce

Notification bar doesn't work the video/audio pause/resume and next /previous playing option also skip functions. 

### Expected behavior

To work the video/audio pause/resume and next /previous playing option also skip functions. 

### Actual behavior

Notification bar doesn't work the video/audio pause/resume and next /previous playing option also skip functions. 

### LibreTube version

0.24.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-07-14 09:52
Duplicate of https://github.com/libre-tube/LibreTube/issues/6100

**Closed by Bnyro** 2024-07-14 09:52 UTC
Labels: bug
