### ISSUE TITLE
Accents fix

### ISSUE THREAD

**Issue by Broniy** [libre-tube/LibreTube#789] opened 2022-07-15 06:31 UTC
### Steps to reproduce

Accent color error.

### Expected behavior

.

### Actual behavior

https://user-images.githubusercontent.com/109084455/179164750-1305dd1c-97e2-4736-bf48-2a7195cb5213.mp4

### LibreTube version

0.3.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-07-15 06:57
What's the problem?

**Comment by Broniy** [comment] 2022-07-15 06:58
The colors do not match.

**Comment by Broniy** [comment] 2022-07-15 06:59
Watch the video carefully.

**Comment by Bnyro** [comment] 2022-07-15 07:02
1. You should fill out all the information asked for in the issue template
2. The title and description should be informative
3. Your screen recording doesn't help in any way, making it 2x or higher speed doesn't help either
4. Not able to reproduce, can probably just be fixed by using CI builds or restarting the app

**Closed by Bnyro** 2022-07-15 07:02 UTC
Labels: bug
