### ISSUE TITLE
Close the video player after moving the video player to bottom like in newpipe

### ISSUE THREAD

**Issue by Gamer750** [libre-tube/LibreTube#4676] opened 2023-08-31 16:22 UTC
### Describe your suggested feature

Close the video player after moving the video player to bottom like in newpipe

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-31 16:27
Duplicate of #2020

**Closed by Bnyro** 2023-08-31 16:27 UTC
Labels: enhancement

**Comment by Gamer750** [comment] 2023-08-31 16:35
Like this 


https://github.com/libre-tube/LibreTube/assets/141329708/60127b21-30f3-474c-b990-9f6367f8b492
