### ISSUE TITLE
Playback Progress Carried Over to Next Video in Queue

### ISSUE THREAD

**Issue by E0697** [libre-tube/LibreTube#4007] opened 2023-06-14 12:48 UTC
### Steps to reproduce

1. Play a video, then add a couple of videos to the queue.
2. Enable autoplay (also happens when manually playing the next video sometimes)
3. The progress from the first video is carried over to the next (if it was 00:49 for example, the next video will start at 00:49)

### Expected behavior

The next video should start from beginning

### Actual behavior

The next video starts playing at the timeframe matching the previous video's progress

### LibreTube version

0.15.1

### Android version

Android 12

### Other details

It's inteittent, doesn't always happen.
It sometimes happens when switching from video to audio mode. (If I switch to audio mode before the playback starts)
Also when the final part of a video is a SponsorBlock segment and you skip it.
I believe the latest alpha also has this issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-14 14:57
Duplicate of #3985

**Closed by Bnyro** 2023-06-14 14:57 UTC
Labels: bug

**Comment by E0697** [comment] 2023-06-15 11:36
This is still happening in the alpha, after the fix PR was merged.

**Comment by E0697** [comment] 2023-06-15 15:44
Latest alpha:
https://github.com/libre-tube/LibreTube/assets/66939100/fb1755b6-546f-4c8e-9955-a4889ca01e16
