### ISSUE TITLE
Unable to open and clone long playlists.

### ISSUE THREAD

**Issue by Ilhamiii** [libre-tube/LibreTube#2561] opened 2023-01-02 13:53 UTC
### Steps to reproduce

1.Enter the long playlist on the channel.
2.Application does not work during upward movement.
3.It is often not possible to clone a playlist.
4.Unable to open cloned playlist.

### Expected behavior

There should be no such problem.

### Actual behavior

https://user-images.githubusercontent.com/121803062/210296153-154dea07-dd6e-4c64-9e91-729cfa87e60e.mp4

### LibreTube version

0.9.1 Debug

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-02 15:51
Are you logged in with a Piped account?

**Comment by xIUPITERx** [comment] 2023-01-03 14:30
For such large playlists the bookmark function was implemented.

**Comment by Bnyro** [comment] 2023-01-03 14:33
Dupe of #2289

**Closed** 2023-01-03 14:33 UTC
Labels: bug

**Comment by Gabs-Unk** [comment] 2023-01-03 14:37
Smart people does really exists 💪🤝
