### ISSUE TITLE
App crashes when opening some videos from subconscious page. 

### ISSUE THREAD

**Issue by ramendraa** [libre-tube/LibreTube#4225] opened 2023-07-13 17:01 UTC
### Steps to reproduce

Open the app on subconscious
Click on a video to play one that crashes are:
https://www.youtube.com/watch?v=Ef8VwyL1zG8&t=0
https://www.youtube.com/watch?v=BDbkNQ_flsI&t=0

Other videos from subconscious page works normally like this one
https://www.youtube.com/watch?v=jr4bZxIi2d0&t=0

### Expected behavior

Normal play of the video

### Actual behavior

The app crashed and closed. When I open the app again it shows this error log 

### LibreTube version

0.16.0

### Android version

Android 13 divestos with root 

### Other details

java.lang.IllegalArgumentException: unexpected host: 
	at okhttp3.HttpUrl$Builder.host(SourceFile:29)
	at okio.Path$Companion.unwrapUrl(SourceFile:43)
	at okio.Path$Companion.shouldDisableProxy(SourceFile:31)
	at com.github.libretube.ui.fragments.PlayerFragment.access$setStreamSource(SourceFile:411)
	at com.github.libretube.ui.fragments.PlayerFragment$setResolutionAndSubtitles$2.invokeSuspend(SourceFile:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c8f0562, Dispatchers.IO]
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ramendraa** [comment] 2023-07-13 17:05
```
type: crash
osVersion: OnePlus/OnePlus8T/OnePlus8T:13/TQ1A.230105.001.A2/eng.emy.20230123.072605:user/release-keys
package: com.github.libretube:37
process: com.github.libretube

java.lang.IllegalArgumentException: unexpected host: 
	at okhttp3.HttpUrl$Builder.host(SourceFile:29)
	at okio.Path$Companion.unwrapUrl(SourceFile:43)
	at okio.Path$Companion.shouldDisableProxy(SourceFile:31)
	at com.github.libretube.ui.fragments.PlayerFragment.access$setStreamSource(SourceFile:411)
	at com.github.libretube.ui.fragments.PlayerFragment$setResolutionAndSubtitles$2.invokeSuspend(SourceFile:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at androidx.work.Worker$2.run(SourceFile:53)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9aa89a4, Dispatchers.IO]

```

**Comment by Bnyro** [comment] 2023-07-13 17:28
Duplicate of #4192

**Closed by Bnyro** 2023-07-13 17:29 UTC
Labels: bug
