### ISSUE TITLE
Navigation Order doesnt affect start screen

### ISSUE THREAD

**Issue by KrychuTM** [libre-tube/LibreTube#3383] opened 2023-03-25 10:04 UTC
### Steps to reproduce

1. Go to settings, then Apppearance.
2. Change the order of the navigation bar replacing the first default option "Home" with any other option. For example "Subscriptions".
3. Close and relaunch LibreTube.

### Expected behavior

In my opinion, changing the order of this navigation bar should change the app's start-up screen to which ever screeen is the first option in the naviagtion bar.

### Actual behavior

Instead, it just starts up on the default home screen which shows a "Featured" list and a "Trending" grid whilst thr navigation bar clearly shows that its supposed to be showing the "Subscriptions" screen.

### LibreTube version

"13.0.0"

### Android version

Android 11

### Other details

![Screenshot_20230325-055415](https://user-images.githubusercontent.com/79592592/227710639-05e23333-1d5b-49c6-9433-99ed2d1749c4.png)
![Screenshot_20230325-055432](https://user-images.githubusercontent.com/79592592/227710640-bd96b327-57b8-439c-87fd-1631c704bfdd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-25 10:27
The start tab can be selected via the small house icon.
Duplicate of #3121

**Closed by Bnyro** 2023-03-25 10:27 UTC
Labels: bug
