### ISSUE TITLE
Search screen improvements

### ISSUE THREAD

**Issue by NeeRaj-2401** [libre-tube/LibreTube#3074] opened 2023-02-14 12:35 UTC
### Describe your suggested feature

There are two suggestions
1. [BUG] app logo starts appearing in search screen 

<img src="https://user-images.githubusercontent.com/88180887/218740049-989ad8ad-b939-4e8d-a858-83ce51823ca5.jpg" width="50%">

2. [FEATURE] pill shaped outline for non active search filter 

<img src="https://user-images.githubusercontent.com/88180887/218739932-9e2b2fd3-d610-47be-8e71-a7cd95451449.jpg" width="50%">

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2023-02-14 16:14
What's the problem with the current search bar?

**Comment by NeeRaj-2401** [comment] 2023-02-14 17:18
> 1. [BUG] app logo starts appearing in search screen

After few minutes When played video from search results 

> 2. [FEATURE] pill shaped outline for non active search filter

Will look good as u can see in YT app

**Comment by Bnyro** [comment] 2023-02-14 17:58
The bug is either not a bug or a duplicate of #1965

**Closed** 2023-02-14 18:09 UTC
Labels: enhancement
