### ISSUE TITLE
[FEATURE] Dark AMOLED theme

### ISSUE THREAD

**Issue by m-koushan** [libre-tube/LibreTube#145] opened 2022-04-26 09:46 UTC
**Describe the feature you'd like to see added**
Dark AMOLED theme would be great.

**Additional context**

**Comment by martin-desktops** [comment] 2022-05-07 11:13
Duplicate of https://github.com/libre-tube/LibreTube/issues/88
The issue can be closed

**Closed** 2022-05-07 11:23 UTC

**Comment by Bnyro** [comment] 2022-05-20 12:33
added with #253
