### ISSUE TITLE
Comments acting weird

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2603] opened 2023-01-05 23:35 UTC
### Steps to reproduce

1. Open comment section while playing a video
2. Load replies to a comment
3. Close replies to the comment
4. Experience the bug

### Expected behavior

Speaks for itself

### Actual behavior

Speaks for itself

### LibreTube version

0.10.0

### Android version

13

### Other details

https://user-images.githubusercontent.com/76624594/210900223-d7005964-7292-4cfa-81de-c89799b2e9d3.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gabs-Unk** [comment] 2023-01-06 00:13
Same for me
won't affect daily use but it is really acting strange

**Comment by Bnyro** [comment] 2023-01-06 11:07
Dupe of #2425

**Closed by Bnyro** 2023-01-06 11:07 UTC
Labels: bug
