### ISSUE TITLE
PIP play and pause buttons do not work. 

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#4804] opened 2023-09-17 18:52 UTC
### Steps to reproduce

PIP play and pause buttons do not work. 

### Expected behavior

Play and pause. 

### Actual behavior

PIP play and pause buttons do not work. 
The buttons do not respond.

### LibreTube version

0.18.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-09-17 19:14
Can't reproduce, works well on both stable and debug

**Comment by nanedi** [comment] 2023-09-17 19:16
0.17.x is fine.
My Google pixel also has the same problem.

**Comment by Bnyro** [comment] 2023-09-17 19:23
Duplicate of #4794.

The logic for it hasn't been touched with the most recent update.

**Closed by Bnyro** 2023-09-17 19:23 UTC
Labels: bug
