### ISSUE TITLE
App doesn't download videos and music

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#1844] opened 2022-11-14 02:26 UTC
### Steps to reproduce

The app only has Network and Notifications permissions but Storage permissions are missing/not available.

This is most likely the reason why the app cannot download videos/music.

### Expected behavior

The app should download videos and music.

### Actual behavior

Downloading of videos and audio doesn't start or progress.

### LibreTube version

0.7.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment] 2022-11-14 04:19
> The app only has Network and Notifications permissions but Storage permissions are missing/not available.

> This is most likely the reason why the app cannot download videos/music.

- LT uses SAF, see [here.](https://github.com/libre-tube/LibreTube/discussions/1130)

- LT is able to download media, I've downloaded few videos :)

- The problem is, it doesn't show the progress of the download, which could be worked on as the downloader is not stable yet.

**Comment by HonestAbe7** [comment] 2022-11-14 04:27
I was going to ask about this. It looks like I need to register to download?

**Comment by VedxP** [comment] 2022-11-14 10:20
> Thanks - are you logged in by a chance? I wonder if the app requires us to login in order to download things? I tried to download a small file (4mb) but it didn't download it even after 4 hours, so something is certainly wrong - the download manager does show a notification but only spins without showing any percentage nor progress. And never downloads the file.
- I am able to download without logging in too :)
> Also, what folder it downloads the file to? The app doesn't offer to select a desired folder. Thanks.

- LT downloads the video in `Android/data/com.github.libretube/files/video` directory.
- The video is playable through LT only :)

**Comment by HonestAbe7** [comment] 2022-11-14 15:39
Well, this app seems different. The save to on the right asks us to login but there is also a down arrow near the left that tries to download but fails.

**Comment by Bnyro** [comment] 2022-12-21 14:03
Closing this as there are already some other open issues concerning downloads.

**Closed by Bnyro** 2022-12-21 14:03 UTC
Labels: bug
