### ISSUE TITLE
Can't login into lunar.icu

### ISSUE THREAD

**Issue by k1gen** [libre-tube/LibreTube#4796] opened 2023-09-17 09:19 UTC
### Steps to reproduce

1. Go to "Settings -> Instance -> Log in/register"
2. Input your piped.lunar.icu credentials
3. Get "The username or password you have entered is incorrent" toast
4. Log in on website works fine

### Expected behavior

LibreTube should accept my credentials for the lunar.icu instance

### Actual behavior

I get "The username or password you have entered is incorrent" toast

### LibreTube version

0.18.0

### Android version

Android 13

### Other details

I have checked my credentials, they are correct

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-09-17 13:20
The only thing I can imagine is that you have a different authentication instance set, and therefore attempt to log in into an other instance than lunar.icu actually.

Since logins work fine for me on the official instance and the one I use, I'm closing this as not reproducible.

**Closed by Bnyro** 2023-09-17 13:20 UTC
Labels: bug, can't reproduce

**Comment by k1gen** [comment] 2023-09-17 15:51
@Bnyro When I set the Authentication istance to lunar.icu and try to log in, I have the same issue. Please, at least try to reproduce the issue before closing it. The fact that you made a Piped Instance switcher, chose the default instance and apparently haven't tested it since makes me sad.

**Comment by akano12** [comment] 2023-09-17 16:12
> The fact that you made a Piped Instance switcher, chose the default instance and apparently haven't tested it since makes me sad.


1. Code of Conduct explicitly and clearly asks users not to ping LibreTube members

2. Works fine in my side, both account creation and logging in

**Comment by Bnyro** [comment] 2023-09-17 16:13
I tried to reproduce the issue...

Nevertheless I won't create an account on an instance I don't trust.

Clear the cache, make sure you use the right api url by using the custom instance option or whatever, but don't blame me for not testing whether an issue is reproducible while I can confirm it's not on several instances.
