### ISSUE TITLE
Audio cannot be saved

### ISSUE THREAD

**Issue by jbwfu** [libre-tube/LibreTube#1943] opened 2022-11-20 15:55 UTC
### Steps to reproduce

1. Select and download audio
2. Go to `/storage/emulated/0/Android/data/com.github.libretube/files/audio/` directory
3. You can see that the file size gradually increases, indicating that the audio is being downloaded.
4. Eventually this file disappeared.

### Expected behavior

Get an audio file.

### Actual behavior

Nothing at all.

### LibreTube version

0.8.0

### Android version

Android 12 

### Other details

As far as I know, this problem has existed since version 0.7.1.
In addition, the downloaded audio and video does not have a suffix, can you add it?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jbwfu** [comment] 2022-11-20 16:12
Videos can be downloaded and saved normally.But there is no sound for playback (because it is downloaded but not saved).
When I put an audio file with the same name as the video into the `/storage/emulated/0/Android/data/com.github.libretube/files/audio/` directory, the downloaded video in the app can play with sound.

**Comment by ISchwarz23** [comment] 2022-11-26 09:47
I did some investigations. It is working for some videos, but for other videos the audio is gone in "DOWNLOAD_COMPLETE". In these cases, the download status is "STATUS_FAILED".
I keep on investigating why the audio download for some videos fails.

**Comment by ISchwarz23** [comment] 2022-11-26 10:19
The error returned by the download manager is a "ERROR_CANNOT_RESUME". 
I was able to verify this behavior using curl to download the audio from the same URL as the app is doing and got an identical error:
`curl: (18) transfer closed with outstanding read data remaining`
So it seems to be an issue with the Piped API.

**Comment by jbwfu** [comment] 2022-11-30 06:50
I downloaded the same audeo successfully using [NewPipe](https://github.com/TeamNewPipe/NewPipe).

**Comment by amadoumx** [comment] 2022-12-02 12:40
Nearly same issue, but:

3. File get downloaded
4. Go to /0/Android/data/com.github.libretube/files/audio
5. File is there, but not was not saved as an audio file -can't open file

**Comment by jbwfu** [comment] 2022-12-02 13:50
> Nearly same issue, but:
> 
> 3. File get downloaded
> 4. Go to /0/Android/data/com.github.libretube/files/audio
> 5. File is there, but was not saved as an audio file -can't open file

If the video/audio can be played by opening the downloaded video in the app, then the file in the '0/Android/data/com.github.libretube/files/audio' folder should be opened as an audio file, or the suffix can be changed to .mp3 are opened with other players.  If when you download the file you name it example.mp3 then it will be the audio file with the suffix, but this creates new problems...

**Comment by amadoumx** [comment] 2022-12-03 10:43
I took your advice. It worked. It's a pity it doesn't work as easily as with newpipe. Many thanks

**Comment by Bnyro** [comment] 2022-12-03 14:54
So from your testings, in the end the issue is that the player doesn't recognize the file type and doesn't "realize" it should play it as an audio file?

**Comment by jbwfu** [comment] 2022-12-03 16:49
> So from your testings, in the end the issue is that the player doesn't recognize the file type and doesn't "realize" it should play it as an audio file? 

No, the player can recognize audio and video without a suffix, but the audio doesn't seem to save after the download is complete?  After starting to download the audio and video, it can be observed that the file is being downloaded, but the audio disappears after the download is complete.  This phenomenon can be seen in the following gif.  (In fact, I accidentally successfully downloaded and saved the audio once in the test just now, so it seems that this is my problem? Or is it accidental. . )
![1000006871_CuteGIF_20221204_003925.gif](https://user-images.githubusercontent.com/75001777/205452010-dc1d6412-b370-4c94-926d-5212480dbe2c.gif)

**Comment by Bnyro** [comment] 2022-12-09 12:18
@asklow Your comments about that aren't helpful in any way, complaining doesn't make it better.
We won't add in-app muxing, downloads are not meant to be used outside the app.

**Comment by Bnyro** [comment] 2023-01-14 17:22
resolved by #2469

**Closed by Bnyro** 2023-01-14 17:22 UTC
Labels: bug
