### ISSUE TITLE
Can you please make the app able to play in the background  like drawing over other apps and picture-in-picture it eill enable us to use play media when not in the app making it more use ful for music .[FEATURE] <description of feature>

### ISSUE THREAD

**Issue by Clovisca** [libre-tube/LibreTube#111] opened 2022-03-30 14:49 UTC
**Describe the feature you'd like to see added**
A short description of the feature, and what it would accomplish.

**Additional context**

**Comment by lilcheti** [comment] 2022-03-30 15:35
Yes please don't put all those in the title or the issue will be closed. It already plays in background for some devices but I'm working on it to create a media notification as well.

**Comment by Bnyro** [comment] 2022-05-14 18:50
Dupe of #59

**Closed by Bnyro** 2022-05-14 18:50 UTC
Labels: enhancement
