### ISSUE TITLE
App crashes when deleting a song from the playlist that is currently playing

### ISSUE THREAD

**Issue by cintek** [libre-tube/LibreTube#2772] opened 2023-01-20 08:57 UTC
### Steps to reproduce

1.  Open Playlist
2. Play a song from playlist
3. Go to the playlist (don't stop the song)
4. Remove the song that is currently playing

### Expected behavior

I would expect it to continue to play the song but to delete it from the playlist

### Actual behavior

The app deletes the song from the playlist but it crashes

### LibreTube version

0.10.0

### Android version

Lineage OS 20.0 (Android 13)

### Other details

This is the error that is shown after the app starts again:
<img src="https://user-images.githubusercontent.com/100708552/213655398-aa5b0e9b-f588-4127-9d07-b1d573121e9c.png" width=40% height=40%>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2023-01-20 12:28
Can't reproduce, but if I delete a video and click on ``play all`` it still plays the deleted video.

**Comment by Bnyro** [comment] 2023-01-20 14:36
Dupe of #2601

**Closed by Bnyro** 2023-01-20 14:36 UTC
Labels: bug

**Comment by cintek** [comment] 2023-01-20 15:45
Sorry, didn't search in closed issues. But great that it was fixed already. Thanks!
