### ISSUE TITLE
Video stops playing in landscape mode

### ISSUE THREAD

**Issue by Dragonfly-30** [libre-tube/LibreTube#5458] opened 2024-01-07 17:36 UTC
### Steps to reproduce

1. open Libretube
2. play a video
3. Go to landscape mode
4. Video stops with a blank screen

### Expected behavior

Video should switch to landscape mode

### Actual behavior

Blank screen and doesn't play

### LibreTube version

21.1

### Android version

7.0

### Other details

Actually if I cut the video and start it again, it works well for rest of the time I'm using the app. However, if I open it again after killing it, it does the same thing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 09karankr** [comment] 2024-01-08 00:00
Hi, I want to work on this issue, please assign me

**Comment by liviucerchez** [comment] 2024-01-08 08:19
I can confirm this issue also happens to me: the video stops playing with a blank black screen when I rotate the device (Auto-fullscreen turned on, doesn't matter if it's mobile of WiFi). I found a weird workaround to close the video and reload it, which seems to work most of the time. Is it cache/buffer related, quality/resolution related, or is it the instance connectivity? I'm not sure. Wifi Video: Auto, No-Fullscreen resolution: Same as fullscreen. Android v7.0.

**Comment by IndusAryan** [comment] 2024-01-08 09:05
It's working here, not able to reproduce

**Comment by liviucerchez** [comment] 2024-01-08 09:28
I have tried setting Audio/Video quality settings to 720p (video) + Worst (audio) and this seems to "fix" it (instead of Auto for both video and audio). So in my case, the black screen seems to be related to the quality settings.

**Comment by liviucerchez** [comment] 2024-01-08 09:35
I have tried with Video quality explicitly set to 720p (for both normal and HD) and this seems to "fix" it (instead of Auto). So in my case, the black screen seems to be related to the quality settings.

**Comment by IndusAryan** [comment] 2024-01-09 07:10
> Hi, I want to work on this issue, please assign me

you should PR directly if you have found any solution

**Comment by abGit9** [comment] 2024-01-16 00:21
Cannot reproduce on Android version 14

**Comment by Dragonfly-30** [comment] 2024-01-23 18:01
Should I close this issue, as the devs are unable to reproduce it??

**Comment by Bnyro** [comment] 2024-02-11 10:20
Closing in favor of https://github.com/libre-tube/LibreTube/issues/5538

**Closed by Bnyro** 2024-02-11 10:20 UTC
Labels: bug, can't reproduce
