### ISSUE TITLE
Separate YouTube videos from shorts

### ISSUE THREAD

**Issue by MirkoDL** [libre-tube/LibreTube#2517] opened 2022-12-27 18:06 UTC
### Describe your suggested feature

I would like it if the possibility to separate the shorts from the normal videos was implemented.
In the "subscriptions" tab, for example, I'd like to see a row at the top of the page with horizontal scrolling with all the shorts, while below displaying all the videos (non-shorts only) as already happens now. This can also be implemented for the other tabs as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-27 18:15
Duplicate of #2325

**Closed by Bnyro** 2022-12-27 18:15 UTC
Labels: enhancement
