### ISSUE TITLE
Pause/Play in media notification turns into replay

### ISSUE THREAD

**Issue by foxjaw** [libre-tube/LibreTube#6097] opened 2024-06-02 08:07 UTC
### Steps to reproduce

It's very random. When I leave the player in background, pause through my headphone buttons and when I resume, the player doesn't.

### Expected behavior

The notification player pause/play button shouldn't turn into reset button.

### Actual behavior

The notification player pause/play button turns into reset button.

### LibreTube version

0.23.2

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-06-02 11:39
Duplicate of https://github.com/libre-tube/LibreTube/issues/4470

**Closed by Bnyro** 2024-06-02 11:39 UTC
Labels: bug
