### ISSUE TITLE
App crashes when trying to load a video

### ISSUE THREAD

**Issue by chupamelapolla** [libre-tube/LibreTube#4816] opened 2023-09-18 20:25 UTC
### Steps to reproduce

1. Open Libretube
2. Try to play any video

### Expected behavior

The video should load

### Actual behavior

Libretube tries to open the video, but it crashes before loading any metadata (like, the comments and the description) and the video.

### LibreTube version

0.18.1

### Android version

Android 11

### Other details

I'm using Miui 12.5 (which is based on Android 11)
And this is the backtrace left by the program when opened again after crashing:

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@15fbc56, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at _COROUTINE._BOUNDARY.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:735)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	... 9 more
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by devbytemehedi** [comment] 2023-09-18 20:39
is it the same bug ?

kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@539e59f, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at _COROUTINE._BOUNDARY.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:735)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	... 9 more

**Comment by chupamelapolla** [comment] 2023-09-18 20:45
> is it the same bug ?
> 
> kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $ at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124) at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26) at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33) at retrofit2.OkHttpCall.parseResponse(SourceFile:57) at retrofit2.OkHttpCall$1.onResponse(SourceFile:5) at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34) at androidx.work.Worker$2.run(SourceFile:131) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at java.lang.Thread.run(Thread.java:1012) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@539e59f, Dispatchers.IO] Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at _COROUTINE._BOUNDARY.throwMissingFieldException(SourceFile:115) at com.github.libretube.api.obj.Streams.(SourceFile:3) at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:735) at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68) ... 9 more

yeah it is

**Comment by akano12** [comment] 2023-09-18 20:54
Which instance are you using?

**Comment by chupamelapolla** [comment] 2023-09-18 21:07
@akano12 I disabled the piped proxy, but I still get that error when using any instance

**Comment by akano12** [comment] 2023-09-18 21:07
Anyway this is a duplicate of multiple closed issues, make sure you're using an up to date piped instance.


Also https://github.com/libre-tube/LibreTube/issues/4543#issuecomment-1684864992

**Closed by akano12** 2023-09-18 21:07 UTC
Labels: bug

**Comment by akano12** [comment] 2023-09-18 21:11
> @akano12 I disabled the piped proxy, but I still get that error when using any instance

It seems that we replied at same time, didn't see your reply before closing, sorry about this.


Are you using any custom instances? Also can you check on kavin.rocks if the issue is reproducible?

**Comment by chupamelapolla** [comment] 2023-09-18 21:15
no, I wasn't using any custom instances, and the issue is not reproducible on kavin.rocks. And I guess I just tried with instances that had the old Piped version

**Comment by akano12** [comment] 2023-09-18 21:16
> no, I wasn't using any custom instances, and the issue is not reproducible on kavin.rocks. And I guess I just tried with instances that had the old Piped version

No problem, glad it's fixed.

**Comment by Eliya-Manoj** [comment] 2023-09-21 07:48
Same Problem
 kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:124)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@95ab4ad, Dispatchers.IO]
Caused by: kotlinx.serialization.MissingFieldException: Fields [license, visibility, tags, metaInfo] are required for type with serial name 'com.github.libretube.api.obj.Streams', but they were missing
	at _COROUTINE._BOUNDARY.throwMissingFieldException(SourceFile:115)
	at com.github.libretube.api.obj.Streams.<init>(SourceFile:3)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:735)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	... 9 more
