### ISSUE TITLE
Unable to short videos by Latest / Oldest / Popular.

### ISSUE THREAD

**Issue by KSinghPro** [libre-tube/LibreTube#4933] opened 2023-10-08 14:44 UTC
### Describe your suggested feature

![Screenshot_20231008-200602~2](https://github.com/libre-tube/LibreTube/assets/96082996/c083a12f-2924-4e19-ba79-b73a9c18d469)

I have provided screenshot for reference.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-10-08 15:02
Not possible at the moment + duplicate of multiple closed issues

**Closed by akano12** 2023-10-08 15:02 UTC
Labels: enhancement
