### ISSUE TITLE
Bluetooth controls partially broken

### ISSUE THREAD

**Issue by M00NJ** [libre-tube/LibreTube#5000] opened 2023-10-18 08:13 UTC
### Steps to reproduce

1. Watch a video with a bluetooth device connected (I use Pixel Buds)
2. Press the device control to pause the video over Bluetooth (works)
3. Press the device control to resume playing the video over bluetooth (doesn't work)

This was working when I started using LT, but has been broken for a while now. It's not the headphones, since it works in other apps. Maybe it has somehing to do with background playback?

### Expected behavior

It should be possible to resume playing a video over bluetooth.

### Actual behavior

It is possible to pause over bluetooth, but not to start playing again. 

### LibreTube version

0.19.0

### Android version

Android 14 (GrapheneOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-10-18 08:44
Possiblyvl a duplicate of https://github.com/libre-tube/LibreTube/issues/4996. Can you wait for the video to load at least 10-20 seconds before attempting to play after pausing?

**Comment by M00NJ** [comment] 2023-10-18 08:56
I tested it. Seems to be the same problem as #4996 :)
But I can't be 100%. It happens the most in audio only mode, where you can't see how much was loaded.

**Comment by M00NJ** [comment] 2023-10-18 08:57
I gonna close this and reopen, if #4996 was fixed and the issue persists.

**Comment by M00NJ** [comment] 2023-11-19 15:00
Sadly #5151 didn't fix this issue, so it's probably a different  problem after all.

**Comment by Bnyro** [comment] 2024-01-03 16:37
#5427

**Closed by Bnyro** 2024-01-03 16:37 UTC
Labels: bug, help wanted
