### ISSUE TITLE
Open New video, recieve error.

### ISSUE THREAD

**Issue by jvan1234** [libre-tube/LibreTube#3390] opened 2023-03-25 18:49 UTC
### Steps to reproduce

1. Use LibreTube
2. Tap on a video you want to launch.

### Expected behavior

The video I clicked on will play

### Actual behavior

The app crashes, leading to an error code. (See additional details for the error)

### LibreTube version

0.13.0

### Android version

Android 13

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:17)
	at androidx.room.MultiInstanceInvalidationClient$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:91)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-25 19:06
duplicate of #3389

**Closed by Bnyro** 2023-03-25 19:06 UTC
Labels: bug
