### ISSUE TITLE
No permissions and stops playing after 2 minutes

### ISSUE THREAD

**Issue by blade10101** [libre-tube/LibreTube#5745] opened 2024-03-16 11:48 UTC
### Steps to reproduce

I have changed dns, instances, changed battery settings and even changed a permission to have unlimited network access. But it just stops for no reason after about 2 minutes. I have a samsung s24 ultra, so phone limits should certainly not be a issue. But the app does install with no permissions what so ever

### Expected behavior

It should be able to playa video without stopping

### Actual behavior

It seems to stop working after 2 minutes of being ran in the background 

### LibreTube version

0.21.1

### Android version

Android 14

### Other details

Samsung s24 ultra

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-16 12:05
Duplicate of https://github.com/libre-tube/LibreTube/issues/5141

**Closed by Bnyro** 2024-03-16 12:05 UTC
Labels: bug
