### ISSUE TITLE
Tapping on notification doesnt open the player

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#2192] opened 2022-12-02 23:05 UTC
### Steps to reproduce

First of all, big Thank You for such a great release!

Now, the issue:

1. Play a video
2. Minimise the app - it will play in background (if no picture in picture is selected) and show the playback progress in Android notification
3. Tap anywhere in that playback notification window - it should open the video in LibreTube but nothing happens instead

Can you please fix it? Thanks.

### Expected behavior

Tapping to player in notification area should open the video in LibreTube

### Actual behavior

Nothing happens

### LibreTube version

0.9.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-03 07:20
Dupe of #1931

**Closed by Bnyro** 2022-12-03 07:20 UTC
Labels: bug
