### ISSUE TITLE
[FR] FCast: Ability to cast videos

### ISSUE THREAD

**Issue by SandResidence** [libre-tube/LibreTube#5035] opened 2023-10-24 08:48 UTC
### Describe your suggested feature

Hi, I don't know much about programming android apps, but it would be awesome if you would add a video casting option.

There is an open source project named FCast: https://fcast.org/, so you don't have to play with the proprietary protocols made by giant corporations with literally no documentation.

How feasible is it to add such an option?

### Other details

There are clients and receivers.
Here a link to an example of a client implementation: https://gitlab.futo.org/videostreaming/fcast/-/tree/master/clients

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-10-24 10:28
Duplicate of #799

**Closed by Bnyro** 2023-10-24 10:28 UTC
Labels: enhancement

**Comment by PacoBell** [comment] 2024-11-03 02:46
FCast is not the same protocol as Google Cast. Not duplicate.
