### ISSUE TITLE
Video Overlay Positioning and Menu Visibility Conflict

### ISSUE THREAD

**Issue by Khawarmehfooz** [libre-tube/LibreTube#3986] opened 2023-06-12 02:28 UTC
### Steps to reproduce

1. Open the mobile app.
2. Navigate to the video playback screen.
3. Play a video.
4. Minimize the video.
5. Observe the positioning of the video overlay in relation to the navigation menu.

### Expected behavior

When the video is minimized, the video overlay should be above the bottom navigation menu, revealing the navigation menu in its entirety, enabling users to interact with menu options seamlessly.

### Actual behavior

When the video is minimized, the video overlay remains, hiding the navigation menu completely.

### LibreTube version

0.15.1

### Android version

Android 11

### Other details

Screenshot
![WhatsApp Image 2023-06-12 at 07 27 05](https://github.com/libre-tube/LibreTube/assets/80300513/7c2c5acd-ec8e-43c3-a586-dcd8a467d13a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FireMasterK** [comment] 2023-06-12 02:57
Duplicate of #3861

**Closed by FireMasterK** 2023-06-12 02:57 UTC
Labels: bug
