### ISSUE TITLE
Download indicators

### ISSUE THREAD

**Issue by Joni8829** [libre-tube/LibreTube#6896] opened 2024-12-20 12:01 UTC
### Describe your suggested feature

It would be nice to have the option to see what songs have been downloaded when you're in a playlist. For example with a download icon next to the name.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-12-20 18:29
Duplicate of https://github.com/libre-tube/LibreTube/issues/6710

**Closed by Bnyro** 2024-12-20 18:29 UTC
Labels: enhancement
