### ISSUE TITLE
VOLUME BOOST

### ISSUE THREAD

**Issue by sairam119914** [libre-tube/LibreTube#4194] opened 2023-07-08 16:45 UTC
### Describe your suggested feature

i have an idea of having audio boost or volume boost just like an extension used in windows for maximizing the volume because whenever i watch lecture videos/online classes the audio level is too low it would be phenomenal if there is an audio boost 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-08 16:48
duplicate of #2186

**Closed by Bnyro** 2023-07-08 16:48 UTC
Labels: enhancement

**Comment by sairam119914** [comment] 2023-07-08 16:51
> duplicate of #2186

well i dont know i just saw #2186 because i have been listening to some lectures and found out to have volume booster
