### ISSUE TITLE
Search Text Controller Disposed When Playing/Dismissing A Video

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#1965] opened 2022-11-21 16:09 UTC
### Steps to reproduce

1. Search for something
2. Play the video (playing and clicking back btn would cause the issue) 
3. Close the video (dismissing a video cause the same issue) 

### Expected behavior

Nothing should affect the text controller 

### Actual behavior

Search controller is disposed  

### LibreTube version

0.8.0

### Android version

12

### Other details

Playing or dismissing a video would clear the search text controller and close the search bar. 

https://user-images.githubusercontent.com/50032603/203103233-63f6f03b-839c-487b-a089-f749ca494a20.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SajalRG** [comment] 2023-05-23 08:44
Hi, I'm able to reproduce this issue in version 0.14.1, Pixel 2 API 32 emulator with GMS.
I've also analysed this issue. Below are two different root cause I've found so far:

Issue#1
1. Search for something
2. Play the video (playing and clicking back btn would cause the issue)

Issue#2
1. Search for something
2. Play the video 
3. Close the video (dismissing a video cause the same issue)

I'm able to fix, Issue#1, but not sure of regressions, still checking. I'm just returning false in MainActivity [onMenuItemActionCollapse](https://developer.android.com/reference/android/view/MenuItem.OnActionExpandListener#onMenuItemActionCollapse(android.view.MenuItem))

For Issue#2, looks like onCreateOptionsMenu getting called when PlayerFragment is closed. Still debugging.

**Comment by akano12** [comment] 2023-05-23 20:16
> I've also analysed this issue. Below are two different root cause I've found so far:

You've found? You literally copied what I've already said up above. 

You can also reproduce it by playing a different a video (search -> play video -> minimize video -> play a different video)

**Comment by SajalRG** [comment] 2023-05-23 20:35
Hi @akano12 ,

You're correct, I've literally copy pasted your issue statement from description. I've just listed them separately based on root cause as per my analysis of the code. This seggeration is basically to help me (and hopefully others) understand and debug the issue.

My statement in previous comment was not to claim I've found the issue itself. I hope it's clarified now.

I was also able to reproduce playing different video as well but I'm assuming that root cause is same as Issue#2 but haven't thoroughly checked that part. Thanks for pointing it out.

**Comment by Bnyro** [comment] 2023-05-23 20:58
Hey @SajalRG,
no worries, everything you did is just fine. I'm happy to see you trying to debug the issues and sharing what you figured out so far is a good idea. 
There's nothing specifically you need to worry about here, the only limitation is our code of conduct (can be found in the project's root dir) but I doubt you would have done anything differently there anyways.
If you're able to fix one or two of the issues (e.g. with what you mentioned above) feel free to create a pull request, so it can be tested by others too to check if it's working and there are no major regressions / drawbacks.

**Comment by akano12** [comment] 2023-05-23 21:34
> Edit: I'm new to contributing in open source code. So if there is any specific lingo I need to use to convey certain updates, then any help or pointers in that direction is appreciated. My intention here is not to offend anyone or claim other's contribution as my own.

No worries mate, wasn't trying to be rude anyway. 

Well, the main pillars of open source code are to give credit where it's due (doesn't matter, small opinions or big contributions), and to contribute by whichever things you can do (donations/bug reports/testing and reporting/pull requests..).

**Comment by SajalRG** [comment] 2023-05-25 06:47
Hi,

For second issue, looks like android issue it got fixed in "androidx.fragment:fragment:1.6.0-alpha07".
Source: https://issuetracker.google.com/issues/244336571

Currently I'm trying a workaround, will update PR soon. Also found one regression issue with previous PR, trying to fix both issues together.

Regression Issue:
1. Search for something
2. Navigate to another page using bottom navigation

Here, the navigation bar looks wrong.

**Closed** 2023-05-26 05:19 UTC
Labels: bug, help wanted
