### ISSUE TITLE
Libretube reloads video upon returning to app, if video was originally opened via link

### ISSUE THREAD

**Issue by distbit0** [libre-tube/LibreTube#1712] opened 2022-10-30 16:08 UTC
### Steps to reproduce

Share a YouTube video url to the app via the share menu
Play video in libre tube
Leave libre tube (while video plays in background) (I haven't tested PiP, only background play)
Come back to libre tube
Find that video has been minimised to bottom of screen, app has reloaded and speed has been reset to default speed

### Expected behavior

App doesn't reload when returning to it, while video has been playing in background 

### Actual behavior

App does reload when returning to it, while video had been playing in background.

### LibreTube version

0.6.0 and 0.7.0

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Donkey-Doug** [comment] 2022-10-30 21:49
Same issue here. I am on Android 12.

**Comment by karachikorai** [comment] 2022-10-30 23:41
Hell Team,

Same issue here. In my case all the videos have this problem. Here is the full error stack.

java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:27129)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2348)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.widget.ScrollView.onMeasure(ScrollView.java:699)
	at android.view.View.measure(View.java:27129)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
	at android.view.View.measure(View.java:27129)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4536)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3228)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3533)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2919)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by Bnyro** [comment] 2022-10-31 20:50
@karachikorai
1. How's that related to the issue of the OP?
2. I'd recommend updating the app to 0.7.0!

**Comment by Bnyro** [comment] 2022-10-31 20:50
@distbit0 
You probably meant 0.7.0 and not 0.6.0 as version, right?

**Comment by distbit0** [comment] 2022-10-31 22:14
@Bnyro at the time of posting I was using 0.6.0, but have since upgraded to 0.7.0. am yet to test if issue persists is 0.7.0

**Comment by rozari0** [comment] 2022-11-01 04:40
Same, It's so annoying. :(

**Comment by VedxP** [comment] 2022-11-01 05:27
> @Bnyro Update: I just checked and it also affects 0.7.0 in exactly the same manner as 0.6.0. the link I shared to libretube from brave is: https://m.youtube.com/watch?v=mOm47gBMfg8

It's not limited for specific videos, rather it handles the link the same way you've reported in the issue :)

**Comment by distbit0** [comment] 2022-11-01 06:00
Yeah ik, just provided it in case anyone was suspicious of it being due to a particular link I was using.

**Comment by xIUPITERx** [comment] 2022-11-04 21:57
I think this issue an dupe of#

**Comment by distbit0** [comment] 2022-11-05 00:20
@xIUPITERx possibly, although that issue makes no mention of opening a video via sharing of a link being the cause. I haven't am very sure this is the cause, as it only occurs for me when I open a video via a link, very reliably.

**Comment by Bnyro** [comment] 2022-11-05 19:04
Could anyone please retry the latest debug version?

**Comment by rozari0** [comment] 2022-11-05 19:12
> Could anyone please retry the latest debug version?

Old bug fixed, new one introduced. 😂

Now video start in mini player.

**Comment by distbit0** [comment] 2022-11-05 19:56
@Bnyro where can I download the latest debug version? Thx

**Comment by Bnyro** [comment] 2022-11-05 19:58
> @Bnyro where can I download the latest debug version? Thx
>
Under the GitHub actions tab:
https://github.com/libre-tube/LibreTube/actions/runs/3401371226

**Comment by distbit0** [comment] 2022-11-05 20:06
Can confirm @rozari0's finding. Original big fixed, but now video starts off in the mini player viewer at bottom of screen as shown in attached screenshot.
![Screenshot_2022-11-06-07-03-22-570](https://user-images.githubusercontent.com/10890247/200138964-ae797c38-12d8-4974-8586-05018a0ad52c.jpg)

**Comment by Bnyro** [comment] 2022-11-05 20:14
Well, better than nothing x)

**Comment by distbit0** [comment] 2022-11-05 20:15
Yeah it is an easier to love with bug than the original. That is true.

**Closed** 2022-11-11 16:58 UTC
Labels: bug

**Comment by rozari0** [comment] 2022-11-11 17:57
> Found the issue and fixed now (at least for me), if anyone wants to test it :)

Minimize issue? It's still there. Tested with [86a1a7c](https://github.com/libre-tube/LibreTube/commit/86a1a7c3dfc6a528ab3bad5f1f7636fcbb40413b)

**Comment by Bnyro** [comment] 2022-11-11 18:07
Damn, it actually worked fine for me after my potential fix :/
