### ISSUE TITLE
I don't know what error this is 

### ISSUE THREAD

**Issue by Gauravchaubey66** [libre-tube/LibreTube#6647] opened 2024-10-21 14:37 UTC
### Steps to reproduce

1. Open app
2. Search for something
3. Play any video 
![Screenshot_20241021_200154](https://github.com/user-attachments/assets/d6fa6eb4-c8b4-4f91-ab3a-0ead207a53c0)

### Expected behavior

![Screenshot_20241021_200133](https://github.com/user-attachments/assets/59a7e8d6-280d-4d36-8c71-084845af5e24)
Video should play

### Actual behavior

Video is not playing getting a error of sing in but I am already signed in.

### LibreTube version

 0.25.2

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-10-21 16:46
Duplicate of https://github.com/libre-tube/LibreTube/issues/6389

**Closed by Bnyro** 2024-10-21 16:46 UTC
Labels: bug
