### ISSUE TITLE
double tap on comment text required to view replies

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#3676] opened 2023-04-30 20:42 UTC
### Steps to reproduce

Click on comments to see replies

### Expected behavior

Be able to click on it with one tap

### Actual behavior

It takes two taps

### LibreTube version

0.14.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2023-05-01 00:26
Known issue, more info here
https://github.com/libre-tube/LibreTube/pull/3660

**Comment by itsmmt305** [comment] 2023-05-05 07:47
is this an issue though? i see it as a feature. prevents accidental touches. also if u need instant access to the replies of a comment click the replies icon precisely. i vote Not A Bug.

**Comment by malik0011** [comment] 2023-10-12 05:57
Hi @Bnyro, can you assign this to me? I'd like to work on it. will raise a PR on this.

**Comment by Pamilg8** [comment] 2023-11-01 13:30
https://github.com/libre-tube/LibreTube/pull/4963

**Closed** 2023-11-01 14:39 UTC
Labels: bug, help wanted
