### ISSUE TITLE
Add Feed Option which recommends  Videos in Home Tab

### ISSUE THREAD

**Issue by muhammad-ans** [libre-tube/LibreTube#4497] opened 2023-08-15 18:35 UTC
### Describe your suggested feature

We could add a feature like featured videos in home tab that would display some random videos from subscriptions that are not watched.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-15 19:04
Duplicate of #2612.

**Closed by Bnyro** 2023-08-15 19:04 UTC
Labels: enhancement
