### ISSUE TITLE
server problem

### ISSUE THREAD

**Issue by kazekawa2** [libre-tube/LibreTube#5980] opened 2024-05-06 08:40 UTC
### Steps to reproduce

1.unable to open any video at all 
2.picture in picture make the application crash

### Expected behavior

video playing

### Actual behavior

either the video is loading infinitely or the application crash

### LibreTube version

0.23.0

### Android version

Android12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DanielProg39** [comment] 2024-05-06 10:40
This seems to be a duplicate of #5855 (TLDR: switch to HLS, but be aware that in some instances it is not set up), but the `picture-in-picture make the application crash` thing seems to be something new. It would be helpful if you could post the crash log here (the one that appears when you open the app after it crashes, if it does), as well as tell more on how to reproduce it.

**Closed** 2024-05-06 19:06 UTC
Labels: bug, invalid, can't reproduce
