### ISSUE TITLE
Error during download.

### ISSUE THREAD

**Issue by Fidannyan** [libre-tube/LibreTube#2394] opened 2022-12-16 11:58 UTC
### Steps to reproduce

1.Download the video.
2.Quit the app and remove it from your recent screens.
3.An error occurs

### Expected behavior

There should be no error.

### Actual behavior

java.lang.RuntimeException: Unable to start service com.github.libretube.services.DownloadService@71ee4be with null: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
	at android.app.ActivityThread.access$2100(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.NullPointerException
	at com.github.libretube.services.DownloadService.onStartCommand(DownloadService.kt:39)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
	... 9 more
    

### LibreTube version

0.9.0 Debug

### Android version

Android 12

### Other details

?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-16 12:10
Duplicate of #2191

**Closed** 2022-12-16 12:10 UTC
Labels: bug
