### ISSUE TITLE
Download feature doesn't work

### ISSUE THREAD

**Issue by heberjeur** [libre-tube/LibreTube#2087] opened 2022-11-26 17:20 UTC
### Steps to reproduce

1- I tried to download video
2- I selected all items on the navigation bar
3- I have changed the navigation bar items to have only Home and library

### Expected behavior

Normally, I can download videos and audios

### Actual behavior

I received this error

java.lang.RuntimeException: Unable to start service com.github.libretube.services.DownloadService@48549f8 with null: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4813)
	at android.app.ActivityThread.access$2000(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException
	at com.github.libretube.services.DownloadService.onStartCommand(DownloadService.kt:24)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4795)
	... 8 more
    

### LibreTube version

LT 0.8.0

### Android version

Android 11

### Other details

I have Samsung A50 
I don't have a storage permission
![Screenshot_20221126-181755_Permission controller](https://user-images.githubusercontent.com/11852634/204101022-1adff648-0954-431a-a729-60e9151dc4f6.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-26 17:30
dupe of #2059

**Closed by Bnyro** 2022-11-26 17:30 UTC
Labels: bug
