### ISSUE TITLE
🔥 YouTube channel blocking features and components blocking features 🔥

### ISSUE THREAD

**Issue by Priyanshuyad** [libre-tube/LibreTube#3328] opened 2023-03-19 17:59 UTC
### Describe your suggested feature

When a perticular **channel block** then never show that channel video again .eg.(search results and trending section)

Please, it's Important for me.

### Other details

Components block features are available some chrome extension app and brave app in YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-19 21:29
Duplicate of #1173, still not planned.

**Closed by Bnyro** 2023-03-19 21:29 UTC
Labels: enhancement
