### ISSUE TITLE
The backup cannot be restored—An error code has occurred

### ISSUE THREAD

**Issue by jiaoniwoke** [libre-tube/LibreTube#2446] opened 2022-12-20 14:29 UTC
### Steps to reproduce

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:622)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	... 1 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.github.libretube.db.obj.LocalPlaylistWithVideos` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (StringReader); line: 1, column: 42] (through reference chain: com.github.libretube.obj.BackupFile["localPlaylists"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:5)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:5)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:74)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:90)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:773)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:6)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:10)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:27)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:3)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:171)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:86)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:15)
	at com.github.libretube.ui.preferences.BackupRestoreSettings$$ExternalSyntheticLambda7.onActivityResult(R8$$SyntheticClass:94)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:66)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:329)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:51)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:10)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:69)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:58)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
	at android.app.Activity.performStart(Activity.java:8170)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3748)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:232)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:212)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:184)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8273)
	... 3 more

### Expected behavior

After the backup, the previous, subscription, viewing history, search, etc. cannot be restored,

### Actual behavior

After clicking Restore Backup, an error code appears.

### LibreTube version

0.9.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-20 14:38
Dupe of #2429

**Closed by Bnyro** 2022-12-20 14:38 UTC
Labels: bug

**Comment by jiaoniwoke** [comment] 2022-12-20 16:39
可以解决这个问题吗？

**Comment by jiaoniwoke** [comment] 2022-12-20 16:39
> #2429的欺骗[](https://github.com/libre-tube/LibreTube/issues/2429)

Can you solve this problem?

**Comment by jiaoniwoke** [comment] 2022-12-20 16:39
Can solve this problem....

**Comment by jiaoniwoke** [comment] 2022-12-20 16:40
We can solve this....
