### ISSUE TITLE
Feat: blocking channels and seeing only videos in my language

### ISSUE THREAD

**Issue by JoseAngel-MAD** [libre-tube/LibreTube#4931] opened 2023-10-08 12:40 UTC
### Describe your suggested feature

1. I'd like to have an option to block some channels. That way, I wouldn't get video recommendations for those channels.
2. Option to tell LibreTube that I only want to watch videos in my language. Therefore, the app shouldn't show videos in other languages, neither when I search for a video nor when the app recommends similar videos.

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-10-08 15:30
1. Duplicate of #1173
2. YouTube doesn't provide info about which language is being spoken in a video, hence LibreTube doesn't know either...

**Closed by Bnyro** 2023-10-08 15:30 UTC
Labels: enhancement
