### ISSUE TITLE
[Bug] Changing brightness and volume using swipe gesture on fullscreen is not seemless

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#2541] opened 2022-12-29 09:00 UTC
### Describe your bug

**Android Version**
Android 12, CalyxOS

**LibreTube Version**
0.9.1

**Current Scenario**
To change brightness using swipe gestures on fullscreen :-

![1Screenshot_20221229-135412](https://user-images.githubusercontent.com/103326242/209925057-4cec4eb8-fd1d-4049-b55d-bd003899b0ea.png)

Step 1 : Click on fullscreen (above).
You get this screen (below)

![2Screenshot_20221229-135419](https://user-images.githubusercontent.com/103326242/209925417-fb1f9d13-e189-4e1f-bc16-8254c3d0f445.png)

Step 2 : Change brightness using swipe gestures.
![3Screenshot_20221229-135424](https://user-images.githubusercontent.com/103326242/209925455-fd476184-ea88-440e-8743-ef10f98b7657.png)

Step 3 : To go back to full screen, click again on this screen.
You get this screen. (below)
![4Screenshot_20221229-135429](https://user-images.githubusercontent.com/103326242/209925609-7a70c4de-c8d8-4a61-a0f9-f1729f2389a0.png)

Step 4 : Click again on this screen to enjoy your fullscreen video experience.
![5Screenshot_20221229-135437](https://user-images.githubusercontent.com/103326242/209925724-d72ce118-79b9-4698-9426-49f41063ab5f.png)

**Caution**

There should be some delay between above mentioned Step 3 and Step 4.
Otherwise it can trigger "Double tap to seek" option.
![Screenshot_20221229-141257](https://user-images.githubusercontent.com/103326242/209926842-30c9b5b7-f823-4e6a-ab83-08409ed24f76.png)

Same goes for volume.

### Other details

**Suggested scenario**
Can we do it the way [NewPipe](https://github.com/TeamNewPipe/NewPipe) does.
No tapping anywhere.
Just swipe up/down on left/right side for changing brightness/volume.

![Screenshot_20221229-135629](https://user-images.githubusercontent.com/103326242/209926922-ea2c767b-3abc-4760-b49c-04aebc3d1a09.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tampos4** [comment] 2022-12-30 06:54
Same goes for "Double tap to seek" option.
You need to first tap on the fullscreen, then double tap to seek forward and backward, then 2 taps with some delay to go back to original position (full screen).

**Comment by tampos4** [comment] 2022-12-30 07:00
Can we eliminate this extra redundant screen we have to deal with (below)
![h209925417-fb1f9d13-e189-4e1f-bc16-8254c3d0f445](https://user-images.githubusercontent.com/103326242/210043072-ceb3a551-e239-4fe9-a859-031b4235feb7.png)


So we can easily swipe for brightness & volume and double tap go seek forward and backward on this screen only(below).
![f209925724-d72ce118-79b9-4698-9426-49f41063ab5f](https://user-images.githubusercontent.com/103326242/210043268-2697268a-5c7a-4a3c-a3af-105631293725.png)
Btw that's how things in NewPipe work.

**Comment by Archeix7** [comment] 2022-12-30 08:55
Bryno had once "fixed" this bug, hahaha https://github.com/libre-tube/LibreTube/issues/1947

**Comment by AR-Home** [comment] 2022-12-30 10:18
Bryno, please can u remove the first tap to use the proposed controls, so we just swipe and touch for the controls.

**Comment by akano12** [comment] 2022-12-30 13:12
> Bryno had once "fixed" this bug, hahaha https://github.com/libre-tube/LibreTube/issues/1947

Hahaha?

Feel free to show us your great programming and problem solving skills and submit a pull request to fix this issue.

**Comment by akano12** [comment] 2022-12-30 13:13
> Bryno, please can u remove the first tap to use the proposed controls, so we just swipe and touch for the controls.

Can't reproduce, work's properly on ny s20

**Comment by Bnyro** [comment] 2022-12-30 13:16
Can't reproduce either, but that's funny for some people apparently.

**Comment by Archeix7** [comment] 2022-12-31 05:48
> > Bryno had once "fixed" this bug, hahaha #1947
> 
> Hahaha?
> 
> Feel free to show us your great programming and problem solving skills and submit a pull request to fix this issue.

Did I say somewhere that I'm a programmer for solving problems? No, but Bryno closed the issue marked "fixed" and didn't fix this shit, and apparently didn't even check it. I've written about this bug a couple of times already(I'm sure I'm not the only one), and he was closing it marked "not planеd" and after a few updates (hello - it's a bug from version 0.6 or even earlier) he finally decided to turn his whole programming eye to it. My ass is on fire for how many months this bug has been in use and it's either not planned or fixed without fixed, nothing personal but go fuck yourself

**Comment by tampos4** [comment] 2022-12-31 06:54
Hey @Archeix7 ,  there is no need of that. Now we are not being solution oriented here.
I also really want it to get fixed as this bug is VERY irritating.

> > Bryno, please can u remove the first tap to use the proposed controls, so we just swipe and touch for the controls.
> 
> Can't reproduce, works properly on ny s20

> Can't reproduce either.

Really..! Is your experience in using swiping gestures on full screen similar to and as seemless as [NewPipe](https://github.com/TeamNewPipe/NewPipe).

I think I am unable to explain this bug correctly.

If you don't use NewPipe could you please install it once and compare it.
Changing brightness/volume on LibreTube on fullscreen using swipe gestures takes almost or sometimes more than 5 seconds, while on NewPipe it takes less than a second.

**Comment by Bnyro** [comment] 2022-12-31 07:00
> Did I say somewhere that I'm a programmer for solving problems? No, but Bryno closed the issue marked "fixed" and didn't fix this shit, and apparently didn't even check it. I've written about this bug a couple of times already(I'm sure I'm not the only one), and he was closing it marked "not planеd" and after a few updates (hello - it's a bug from version 0.6 or even earlier) he finally decided to turn his whole programming eye to it. My ass is on fire for how many months this bug has been in use and it's either not planned or fixed without fixed, nothing personal but go fuck yourself
>
Nobody asked you to use the app. If you can't live with bugs and don't get how open source works, you should consider moving away from this project honestly.

**Comment by AR-Home** [comment] 2022-12-31 07:02
Ur right Bryno, keep up the good work.😁

**Comment by Archeix7** [comment] 2022-12-31 09:31
> Nobody asked you to use the app. If you can't live with bugs and don't get how open source works, you should consider moving away from this project honestly.

I love your app, newpipe sucks. Don't get me wrong, the bug goes through several updates, it's the most obvious and the most infuriating, and you close issues with the tag that you don't plan to fix it or that you've already "fixed" it. Imagine you go to the doctor, he checks you out the door and says "not planned" or gives you prescriptions that don't fix anything. 

I apologize if I write very toxic, happy new year

**Comment by akano12** [comment] 2022-12-31 14:31
In case you didn't notice (i know it might be surprising to you) this project is open source.
Open source means the developer works on the project during his free time, he's not obliged to fix bugs or add new features unless he wants to.

Moving on to 

> the bug goes through several updates, it's the most obvious and the most infuriating, and you close issues with the tag that you don't plan to fix it or that you've already "fixed" it

This isn't a high priority issue/bug, it's better to spend the limited free time the developers have on stabilizing the app (fixing compatibility issues and crashes) since you know, LT is relatively new app it's getting more stable and rich in features after each update. So again, this issue is **LOW PRIORITY** because not everyone is affected by it (works well on a lot of devices) and there aren't any useful information to help track the cause of this issue except a couple of screenshots and video recordings (https://github.com/libre-tube/LibreTube/issues/2206#issuecomment-1336193310).

And here's a list of things you could do:

1- Fix the issue yourself (i know you can't)

Alternatively, you can be patient till it's fixed.

**Comment by akano12** [comment] 2022-12-31 14:38
> Really..! Is your experience in using swiping gestures on full screen similar to and as seemless as [NewPipe](https://github.com/TeamNewPipe/NewPipe).
> 
> I think I am unable to explain this bug correctly.
> 
> If you don't use NewPipe could you please install it once and compare it. Changing brightness/volume on LibreTube on fullscreen using swipe gestures takes almost or sometimes more than 5 seconds, while on NewPipe it takes less than a second.

Ye that's what can't reproduce means, swipe gestures works properly. 
if you think you didn't explain the issue properly, upload a recording

**Comment by tampos4** [comment] 2022-12-31 18:42
LibreTube


https://user-images.githubusercontent.com/103326242/210152904-e1a403c9-a219-4ad3-9ab4-80ba090a7ed9.mp4




NewPipe


https://user-images.githubusercontent.com/103326242/210152910-3eccf619-ee50-43f0-8144-0ae1e1e877cc.mp4

**Comment by akano12** [comment] 2023-01-01 01:57
@tampos4 


https://user-images.githubusercontent.com/50032603/210159073-13414504-0566-4a8b-b472-f4ff56efb378.mp4

**Comment by tampos4** [comment] 2023-01-01 04:27
Thanks @akano12

**Comment by xIUPITERx** [comment] 2023-01-02 10:24
What is supposed to be the bug now?

**Comment by Archeix7** [comment] 2023-01-05 22:57
https://user-images.githubusercontent.com/51048550/210895808-c41561f3-5adf-4527-a733-08e41c75a25d.mp4

In shorts swipes work well, but not in normal videos

**Comment by tampos4** [comment] 2023-01-06 13:17
> VID_20230106_005443_995.mp4 
> In shorts swipes work well

Actually it doesn't, even in shorts.

**Comment by tampos4** [comment] 2023-01-06 13:20
Swiping works well when status bar is visible in videos (including in shorts), it does not when video is playing in full screen.

The status bar is always visible in shorts, and therefore it works well in shorts.

**Comment by akano12** [comment] 2023-01-18 23:42
Well I've faced this issue multiple times so far and I've noticed i only encounter it when using volume/brightness swipe gestures from an area close to the screen edge (approximately 3/4 screen size and above). 
Adjusting from near the center works without any issues.

**Comment by akano12** [comment] 2023-01-19 15:39
@Bnyro is this intended? Everything to the right of the marker (including the marker) is a dead area, volume swipe gesture doesn't work. 


![Screenshot_20230119-173411_LibreTube.jpg](https://user-images.githubusercontent.com/50032603/213485204-3b6e256f-d3a2-47fa-95fd-c6d50efa7248.jpg)

**Comment by Bnyro** [comment] 2023-01-19 16:28
1. Please don't tag me, I'll read it fast enough anyways (I also added that to our Code of conduct to not tag team members).
2. That's not intended, though I don't know what it is being caused by.

**Comment by xIUPITERx** [comment] 2023-01-20 11:26
> Everything to the right of the marker (including the marker) is a dead area, volume swipe gesture doesn't work.

Do you use gesture control on your phone? 
Deactivate it and try again, I think it's caused by how the manufacturer implements the back gesture.
I also have a dead zone, but it's way smaller.

**Comment by akano12** [comment] 2023-01-20 22:42
> > Everything to the right of the marker (including the marker) is a dead area, volume swipe gesture doesn't work.
> 
> Do you use gesture control on your phone? 
> Deactivate it and try again, I think it's caused by how the manufacturer implements the back gesture.
> I also have a dead zone, but it's way smaller.

Don't have them enabled as i don't like them

**Comment by Archeix7** [comment] 2023-01-22 10:56
I tested the version 0.10 on A12 yesterday, there was Gesture Bar Length at the bottom of the screen, although this bar itself is hidden in the system. Returning to A11 again shows a bar with time, a battery charge, and that's all. It is very interesting, because the person who made this bugreport sits on A12, and he also has a problem with a bar and seems to be, judging by the photo, and with Gesture Bar Length

**Comment by Archeix7** [comment] 2023-01-31 18:30
> This isn't a high priority issue/bug

I don’t agree, you just can’t imagine how it infuriates to pause 2 clicks, but to smear the video sometimes 4 clicks, if you miss and did not get on the timecode, and sometimes it happens 6 times. Change the volume of 2 clicks, start/pause 2, settings 2 and rewind video 2 - 6+. The whole pleasure

**Comment by Bnyro** [comment] 2023-03-10 17:14
Closing in favor of #3069

**Closed by Bnyro** 2023-03-10 17:14 UTC
Labels: enhancement
