### ISSUE TITLE
Download on SD card

### ISSUE THREAD

**Issue by MAAB-FW** [libre-tube/LibreTube#4656] opened 2023-08-29 00:52 UTC
### Describe your suggested feature

Please add download on SD card option. Downloading files to internal storage on a low config phone puts a lot of pressure on the phone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-29 07:00
Duplicate of #2041

**Closed by Bnyro** 2023-08-29 07:00 UTC
Labels: enhancement
