### ISSUE TITLE
LibreTube Alpha 26a521e: bug report

### ISSUE THREAD

**Issue by BrilliantlyEducated** [libre-tube/LibreTube#4600] opened 2023-08-23 11:03 UTC
### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

java.lang.ArrayIndexOutOfBoundsException: length=4; index=12
	at com.github.libretube.ui.base.BasePreferenceFragment.onDisplayPreferenceDialog$lambda$0(BasePreferenceFragment.kt:36)
	at com.github.libretube.ui.base.BasePreferenceFragment.$r8$lambda$C3IFb1OuUuQw1gqEfncJIFWQcJA(Unknown Source:0)
	at com.github.libretube.ui.base.BasePreferenceFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
	at android.widget.AdapterView.performItemClick(AdapterView.java:352)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1234)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4265)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3986)
	at android.view.View.dispatchTouchEvent(View.java:14668)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2853)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2867)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:567)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1917)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:914)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:515)
	at android.view.View.dispatchPointerEvent(View.java:14940)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6992)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6763)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6228)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6290)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6251)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6425)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6482)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6232)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6290)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6251)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6259)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6232)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9372)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9312)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9258)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9526)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:265)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

### LibreTube version

0.17.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-23 11:04
duplicate of #4595

**Closed by Bnyro** 2023-08-23 11:04 UTC
Labels: bug
