### ISSUE TITLE
Autoplay keeps previous video position

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#3079] opened 2023-02-14 19:23 UTC
### Steps to reproduce

1. Click on the first video of a new playlist that you haven't watched yet.
2. Activate autoplay
3. When the next video starts automatically, it will not start at the beginning, but in the middle.

### Expected behavior

The next video should begin at the start.

### Actual behavior

The next Video starts at a random position.

### LibreTube version

0.12.0 Debug

### Android version

Android 13 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rozari0** [comment] 2023-02-15 16:14
Can confirm that. Next video start at the time where last video was stopped.

**Comment by Bnyro** [comment] 2023-02-19 18:54
Is that only the case with the debug version or also with the 0.12.0 release?

**Comment by rozari0** [comment] 2023-02-19 18:57
> Is that only the case with the debug version or also with the 0.12.0 release?

Both.

**Comment by RickyM7** [comment] 2023-02-21 13:57
Duplicate of #2566, but this one is more specific. I can confirm it, btw.
Infos:
LT 0.12.0
Android 11 (ArrowOS)

**Comment by Bnyro** [comment] 2023-02-22 10:29
Could you please retry it with the latest debug build to make sure it's gone now? I wasn't able to reproduce it anymore after the change (I was able to before), but maybe it was just random.

**Closed** 2023-02-22 10:28 UTC
Labels: bug

**Comment by xIUPITERx** [comment] 2023-02-22 11:07
👍🏻It seems to be fixed.

**Comment by doonoo** [comment] 2023-06-06 06:08
This bug happens with me. It'll start the first video at the beginning then next video start in the middle

**Comment by rozari0** [comment] 2023-06-06 06:16
It was gone for a long time, but I too recently faced this issue for two or three time.
