### ISSUE TITLE
Memory residents apps (video player)

### ISSUE THREAD

**Issue by Pamilg8** [libre-tube/LibreTube#5333] opened 2023-12-15 14:35 UTC
### Describe your suggested feature

https://github.com/libre-tube/LibreTube/assets/149590337/270a1136-86a4-467d-a0c3-598335ddecac

### Other details

"Memory resident apps" are based on running continuously in the background. LibreTube does not support this and does not appear in this list when playing in the background.Background playback can solve problems.LibreTube appears in this list when you press the background button.Apply the same to the video player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-12-15 15:17
duplicate of https://github.com/libre-tube/LibreTube/issues/3794

**Closed by Bnyro** 2023-12-15 15:17 UTC
Labels: enhancement
