### ISSUE TITLE
Add option to share/save to gallary for DOWNLOADED video 

### ISSUE THREAD

**Issue by heartlog** [libre-tube/LibreTube#4036] opened 2023-06-18 17:10 UTC
### Describe your suggested feature

As per we all know Libretube don't save download video in file manager(/gallery). It'll be better, if option to save or share Downloaded video is added. 
As for me, i downloaded 5 video of livestream making my device storage full.(1 stream = 6.5-11.0 GB) and i can't delete(they're imp !) or change location of download like chrome.

## What am i requesting ?
1. An option to save downloaded video which needlessly increase app size.
2. An option to choose video download location  (if possible)
3. Or a setting where User can give permission to save video in file manager without hiding it. (If possible)
4. If `2.` & `3.` are not possible then, atleast option to share Downloaded video(not URL) as media in LT.

Thanks !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-18 17:53
Duplicate of #3572

**Closed by Bnyro** 2023-06-18 17:53 UTC
Labels: enhancement
