### ISSUE TITLE
The date of publication in the watch history is 1970

### ISSUE THREAD

**Issue by Notesure** [libre-tube/LibreTube#6420] opened 2024-08-28 11:36 UTC
### Steps to reproduce

![Screenshot_20240828-153431_LibreTube Debug](https://github.com/user-attachments/assets/153c2190-05e8-46ad-ae2b-870f94c6f72a)

### Expected behavior

Correct date

### Actual behavior

Wrong date

### LibreTube version

0.25.1 beta

### Android version

Misc

### Other details

It doesn't fix when I turn off the local extractor. If you can play the video when Extactor is off, the public date is correct

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-08-28 13:25
Duplicate of https://github.com/libre-tube/LibreTube/issues/6401

**Closed by Bnyro** 2024-08-28 13:25 UTC
Labels: bug
