### ISSUE TITLE
Cannot switch to video mode from audio mode

### ISSUE THREAD

**Issue by yhm4ps1jfp67nkv** [libre-tube/LibreTube#1361] opened 2022-09-24 06:59 UTC
### Steps to reproduce

1. Long press a video thumbnail
2. Choose "Play in the background"

### Expected behavior

The video starts playing in the background and the bottom player appears in the app, from there you can continue watching in the video mode

### Actual behavior

The video starts playing in the background but the bottom player does not appear in the app so you can't switch to the video mode (tapping the notification just takes you to the app without opening anything)

### LibreTube version

Latest debug build from GitHub actions 

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-24 07:07
1. The mini player is not meant to appear when playing in the background because playing in the background is meant to be audio only!
2. The notification thing is a dupe of #1113

**Closed** 2022-09-24 07:07 UTC
Labels: bug

**Comment by yhm4ps1jfp67nkv** [comment] 2022-09-24 07:16
1. Ok, got it
2. That's right, sorry, also closing my other related issue
