### ISSUE TITLE
Tapping on video does not work properly when browsing comments

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#3403] opened 2023-03-26 12:33 UTC
### Steps to reproduce

Hi All,

Thanks for fixing crashing issue and changing comments layout (its much more better now).

However, I noticed the following issue:

1. Play any video
2. Expand comments section
3. Now tap on the video - it will not pause/show on-screen control buttons. They will only appear if we close comments section.

### Expected behavior

On-screen control buttons should appear /video should pause/play on tap when comments are expanded

### Actual behavior

As described in the issue

### LibreTube version

0.13.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-26 12:36
duplicate of #2922

**Closed by Bnyro** 2023-03-26 12:36 UTC
Labels: bug
