### ISSUE TITLE
Instance Error: but only for `Subscription` tab

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#1670] opened 2022-10-28 12:38 UTC
### Steps to reproduce

- Open LT 
- Search for any video and play, it'll play normally 
- But, open subscription page 
- It shows instance error and won't load the sub as expected
- Now, expand subscription list and open a channel page from there 
- Play any video 
- LT crashes 

### Expected behavior

Instance error should not occur as I'm able to play any video from **search results** and **explore/home** tab and can **login** too without any error.

### Actual behavior

Instance error occurs only in subscription tab and videos can't be played from the channels I'm subscribed to, either from the sub tab or even from the search :(

<details><summary>Show error log</summary>

```
java.lang.NullPointerException
	at androidx.appcompat.R$string.formatShort(Unknown Source:1)
	at com.github.libretube.ui.adapters.TrendingAdapter.onBindViewHolder(TrendingAdapter.kt:12)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:179)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:122)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:11)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:13)
	at android.view.View.measure(View.java:26164)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26164)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1449)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:462)
	at android.view.View.measure(View.java:26164)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:51)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:103)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:11)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:204)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26164)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:77)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:18)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:175)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:80)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:16)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7148)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:826)
	at android.view.View.measure(View.java:26164)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4037)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2704)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2989)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2416)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9478)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
	at android.view.Choreographer.doCallbacks(Choreographer.java:996)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:383)
	at android.view.Choreographer.doFrame(Choreographer.java:865)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1227)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
    
```
</details>

### LibreTube version

0.6.1

### Android version

Android 12

### Other details

Screenshots:

<details><summary>Instance error on sub page</summary>

![Screenshot_20221027-170701](https://user-images.githubusercontent.com/87353286/198587407-19b1afb3-c7ee-4ae2-8525-b89916de2b08.png)

</details><details><summary>But, video can be played from search or home tab</summary>

![Screenshot_20221027-170655~2](https://user-images.githubusercontent.com/87353286/198587581-d662cdec-3637-43c4-8a59-19329af062c4.png)

</details><details><summary>Can login too without any error</summary>

![Screenshot_20221028-180333~2](https://user-images.githubusercontent.com/87353286/198587860-0b8da16d-91fa-44b9-9941-4c1f24525783.png)

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by komals1** [comment] 2022-10-28 13:22
![Screenshot_2022-10-28-18-49-09-34_54f92cd6866f5233ab0db4392b806878.jpg](https://user-images.githubusercontent.com/73154889/198606505-14c93c86-dcb7-49d2-8ba8-67da22821dc0.jpg)

same bug can be couldn't able to load subscribed channels

**Comment by Bnyro** [comment] 2022-10-28 13:38
The instance error is due to a database outage on the official instance, the crash is a dupe of #1667.

**Closed by Bnyro** 2022-10-28 13:38 UTC
Labels: bug
