### ISSUE TITLE
crash while going background

### ISSUE THREAD

**Issue by archi-X-beliderscene** [libre-tube/LibreTube#6331] opened 2024-08-08 13:20 UTC
### Steps to reproduce

1 Changed some instances after troubles with loading video
2 turned on podcast, 2 hours video
3 swiped to home
4 app crashes, background not playing

### Expected behavior

Background play

### Actual behavior

Crash, no background play

### LibreTube version

0.24.0

### Android version

android 14

### Other details

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 575440 bytes
Bundle stats:
  android:viewHierarchyState [size=2788]
    android:views [size=2524]
  androidx.lifecycle.BundlableSavedStateRegistry.key [size=571788]
    android:support:activity-result [size=3192]
      KEY_COMPONENT_ACTIVITY_REGISTERED_KEYS [size=2676]
    android:support:fragments [size=568220]
      fragment_0ed925ea-bd8e-4ff2-8138-c051ddff7f54 [size=12572]
        viewState [size=11644]
      fragment_64d810dc-95e1-461c-8b60-a4af02cbc946 [size=554972]
        childFragmentManager [size=552412]
          fragment_a932a6fc-ec54-4186-8682-c058512e05a6 [size=3396]
            viewState [size=2660]
          state [size=1076]
          fragment_44e3cfa3-1dfc-4d9e-8681-a62b826dcebe [size=547716]
            viewState [size=3452]
            childFragmentManager [size=543320]
              fragment_0d43f5f4-9997-4f97-9226-e1fe171ea5b5 [size=542900]
                arguments [size=541724]
                  videoList [size=536440]
                  nextPage [size=4996]
        registryState [size=1996]
          androidx.lifecycle.BundlableSavedStateRegistry.key [size=1872]
            android-support-nav:fragment:navControllerState [size=1548]
              android-support-nav:controller:backStack [size=1444]
PersistableBundle stats:
  [null]
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
	at android.os.Handler.handleCallback(Handler.java:996)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9652)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: android.os.TransactionTooLargeException: data parcel size 575440 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:606)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1439)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:103)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
	... 8 more
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-08-09 15:03
Duplicate of https://github.com/libre-tube/LibreTube/issues/6259

**Closed by Bnyro** 2024-08-09 15:03 UTC
Labels: bug
