### ISSUE TITLE
Drag and Drop on Queue Don't Work Proprerty

### ISSUE THREAD

**Issue by RickyM7** [libre-tube/LibreTube#2620] opened 2023-01-06 21:30 UTC
### Steps to reproduce

1. Put some videos on the queue
2. Try to drag and drop up and down

### Expected behavior

You can put the dragged video on whatever place you want, ahead or behind anything else on the queue.

### Actual behavior

You can't drag a video behind any other in the queue, that is, you can't drag it back properly, and sometimes you can only drop a video forward if you skip one.

Note: I'm sorry for any mistakes, English isn't my first language.

### LibreTube version

0.10.0

### Android version

 Android 11 (ArrowOS)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tampos4** [comment] 2023-01-07 12:09
It looks like you can rearrange those videos only, which are below in queue of the video which is currently playing.
And the video which is currently playing can't be moved upward in queue, it can only be moved downwards.

## Steps to reproduce

1. Play any video.
2. Open its queue (top right corner).
3. Move the currently playing video below to 4-5 videos in queue.

Now, try to rearrange those videos, which are above the currently playing video or
try to move the currently playing video above in queue.

It becomes a problem when you play any mid video of a playlist.

**Comment by Bnyro** [comment] 2023-01-07 15:19
That's the intended behavior, I've been discussing that with @GilesMunn and it seemed the best to us to not allow users to modify the queue above the current video (so the already watched videos), just because it doesn't really make sense to move videos above your current (as it'll never play) and changing the list of already watched videos, as that is rather a history of what you've seen so far.

**Comment by Bnyro** [comment] 2023-01-07 15:20
Closing as it's not a bug

**Closed** 2023-01-07 15:19 UTC
Labels: bug

**Comment by RickyM7** [comment] 2023-01-07 16:07
> ...seemed the best to us to not allow users to modify the queue above the current video (so the already watched videos)...

If you won't be able to move up, wouldn't it be better to not allow moving the current video at all (and be able to move the rest freely)?  Because it doesn't make sense not to be able to move up but to be able to move down, since you can unintentionally move the video and want to return it to position, etc. Current behavior is somewhat limiting.

**Comment by Bnyro** [comment] 2023-01-07 16:14
Fair enough, we can remove that limitation although it doesn't really make sense to me to modify the previous videos. Anyways LT is probably the only app doing like so, we should probably stick to what other music and video players do.

**Comment by tampos4** [comment] 2023-01-07 16:29
> it doesn't really make sense to me to modify the previous videos

It doesn't really make sense **in some (or most) scenarios**.
But in some scenarios it does.

As in the case of playing any video of any playlist (local playlist created by user or channel's playlist created by youtuber).
