### ISSUE TITLE
The music player is placed below the navigation

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3401] opened 2023-03-26 10:25 UTC
### Steps to reproduce

1.Play background music.
2.Scroll down the player.
3.Read the title.

### Expected behavior

The mini player should be above the navigation

### Actual behavior

https://user-images.githubusercontent.com/124310688/227769471-3f6e4608-8148-4a47-a74d-006b4b8a34a4.mp4

### LibreTube version

0.13.1

### Android version

Android 12

### Other details

It's not completely at the bottom.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-26 10:31
duplicate of #594

**Closed by Bnyro** 2023-03-26 10:31 UTC
Labels: bug
