### ISSUE TITLE
Bring Back Old Chapters UI

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4603] opened 2023-08-23 20:36 UTC
### Describe your suggested feature

As the title say.

### Other details

With all due respect and i don't want to sound rude, the new chapters UI is extremely hideous and impractical in fullscreen.

Here's a list of why it's bad:

1- When in fullscreen and the user taps on chapters, a pop up appears that the user have to drag up, select a chapter and drag it down to minimize it then drag it down again to finally dismiss it

2- It occupies the entire screen unlike the previous one.
3- When selecting a chapter, there's no indicator that the chapter was tapped

https://github.com/libre-tube/LibreTube/assets/50032603/f1fe21aa-0b24-44b7-9e2f-17f7a2897baa

Look how simple it was before 

https://github.com/libre-tube/LibreTube/assets/50032603/a454a1f4-c4e4-4dee-84bb-51f07b1e046c

Also there's a bug in the portrait mode, if you tap on chapters multiple times, multiple sheets are opened and stacked on top of each other (will open an issue later after i test on debug to check if it's fixed)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-23 20:54
1. The same issues existed with the previous layout too, except for auto scrolling to the current chapter: #4566
2. that's already been addressed - it now behaves like the comments
3. duplicate of #4566

**Closed by Bnyro** 2023-08-23 20:54 UTC
Labels: enhancement
