### ISSUE TITLE
Option to select which navigation tab to use on startup

### ISSUE THREAD

**Issue by ewokuk** [libre-tube/LibreTube#4465] opened 2023-08-14 09:22 UTC
### Describe your suggested feature

Currently you can change the order of the tabs/buttons on the navigation bar, add and remove tabs, and customise which items appear on the home screen.  But you cannot select which tab is open by default when loading the app.  The only content I am interested in are my subscriptions, and I have customised the home screen to effectively only show my subscriptions, however this results in a mostly blank screen with 1 row of horizontally scrollable content showing the latest content from my subscriptions, and I can only see 1 and a bit items without scrolling over.  The layout for the actual subscriptions navigation tab has a vertical scrolling list of content which looks and works much better as I can see the last 5 videos with no scrolling at all.  So to get around the issue it would be nice to be able to set that tab as the default tab when opening the app, rather than it always start on the home tab.

Also since you can change the order of the navigation tabs, in an attempt to get it to use the subscriptions tab by default, I set that as the first item on the left of the navigation tab, but that has no effect and I have now just ended up with it opening on the home screen anyway (odd behaviour, you would expect the first tab to be the one it starts on).

### Other details

![1](https://github.com/libre-tube/LibreTube/assets/45271861/df875e73-c333-4cd2-9135-605c9b07eb74) ![2](https://github.com/libre-tube/LibreTube/assets/45271861/a422b40d-2660-478b-bb2f-82675edbe597)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-14 09:34
The start tab can be selected via the small house icon under settings -> navigation bar -> order.
Duplicate of #3121

**Closed by Bnyro** 2023-08-14 09:34 UTC
Labels: enhancement
