### ISSUE TITLE
App crashes on specific video

### ISSUE THREAD

**Issue by NeuroException** [libre-tube/LibreTube#4889] opened 2023-10-04 06:47 UTC
### Steps to reproduce

1. Open LibreTube
2. Search for networkchuck
3. Open the video "Building my new server room"
https://piped.video/watch?v=083-46NVMd8

### Expected behavior

The video should be played.

### Actual behavior

The app crashes everytime due to an error related to the upload time, which in this case is "Yesterday".
![signal-2023-10-04-08-46-49-792](https://github.com/libre-tube/LibreTube/assets/118199015/e9421d7c-4030-4983-b0fa-e582da954ec0)

```
kotlinx.datetime.DateTimeFormatException: j$.time.format.DateTimeParseException: Text '2023-10-02T09:58:16-07:00' could not be parsed, unparsed text found at index 10
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:20)
	at kotlinx.datetime.serializers.LocalDateIso8601Serializer.deserialize(SourceFile:15)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at okio._UtilKt.decodeSerializableElement(SourceFile:11)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:50)
	at com.github.libretube.api.obj.Streams$$serializer.deserialize(SourceFile:555)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:68)
	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:26)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(SourceFile:33)
	at retrofit2.OkHttpCall.parseResponse(SourceFile:57)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:5)
	at androidx.appcompat.app.AlertController$2.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8d2b76c, Dispatchers.IO]
Caused by: j$.time.format.DateTimeParseException: Text '2023-10-02T09:58:16-07:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(Unknown Source:160)
	at j$.time.format.DateTimeFormatter.parse(Unknown Source:11)
	at j$.time.LocalDate.parse(Unknown Source:10)
	at j$.time.LocalDate.parse(Unknown Source:2)
	at kotlinx.datetime.LocalDate$Companion.parse(SourceFile:6)
	... 15 more
    
```

### LibreTube version

0.18.1

### Android version

Android 13 / GrapheneOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-10-04 06:52
Duplicate of #4884

**Closed by Bnyro** 2023-10-04 06:52 UTC
Labels: bug
