### ISSUE TITLE
User Playlist normalization and local video/channel filtering

### ISSUE THREAD

**Issue by LovingNumbers** [libre-tube/LibreTube#5721] opened 2024-03-10 09:49 UTC
### Describe your suggested feature

First would like to thank everyone for this awesome project you don't see it everyday that a more privacy focused alternative looks slick and works fairly good.

1. Playlist normalization
-Making it possible to edit user playlist retroactively like easily changing in what order videos are listed like in youtube.

-Being able to share your own user playlist with other people (here is the only request that im not sure if feasible)

2. Local video/channel filtering

-Being able to blacklist youtube channels/video titles with a local filter.

Filters in my opinion are the most important vital lacking feature due to their ability of removing misinformation and sparing the user of wasting his time searching. science, tech and political news search querys are prominent with useless bloat and it only gets worse with more and more AI Channels landing on youtube every user would benefit now and even more in the future if such feature is implemented. Im aware of current restrictions of adding search filters that filter upload time etc. that's why im asking if something like a local blacklist for words would be possible? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-12 09:45
1. https://github.com/libre-tube/LibreTube/issues/4331#issuecomment-1657130143
2. Duplicate of https://github.com/libre-tube/LibreTube/issues/1173

Sharing playlists with other people is not supported by Piped, you could export your playlists to a JSON file, edit it to only contain a certain playlist, and dhare that file.

**Closed by Bnyro** 2024-03-12 09:45 UTC
Labels: enhancement
