### ISSUE TITLE
Confirm delete/Undo option for playlist items

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5013] opened 2023-10-20 17:19 UTC
### Describe your suggested feature

Sometimes using gesture navigation deletes the video from my playlist while using LibreTube. Undo option or Confirm delete option helps to retain data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-10-21 07:33
Duplicate of #2531

**Comment by Bnyro** [comment] 2023-10-21 11:19
How can you accidentally swipe a video to the right? And what's the issue if a video is "lost forever" in your watch history? It's just a video you've already seen ... We have a search function so that you can find the video again - surprise...

**Comment by Eliya-Manoj** [comment] 2023-10-21 12:43
> How can you accidentally swipe a video to the right? And what's the issue if a video is "lost forever" in your watch history? It's just a video you've already seen ... We have a search function so that you can find the video again - surprise...

If I accidentally remove a video from playlist, It does not notify which video is removed. It's not about watch history.

**Closed** 2023-10-26 13:56 UTC
Labels: enhancement
