### ISSUE TITLE
There is a chance that the music of YOUTUBE music cannot be played

### ISSUE THREAD

**Issue by Ryan0886** [libre-tube/LibreTube#3935] opened 2023-06-05 14:30 UTC
### Steps to reproduce

1. Search for song title
2. Select YOUTUBE music
3. Click the song to start playing

### Expected behavior

play music

### Actual behavior

Every time the BUG situation is different
1. When you click to play music, the music picture, progress bar, and music duration cannot be displayed normally (black screen).
2. When clicking the next song, the music picture is still the picture of the previous song, the duration of the previous song on the progress bar, and it cannot be played normally.
3. There is a song title, it seems that the song is being loaded, but s____ errors will appear below (it disappeared too quickly and I didn’t see what the previous word was, and I didn’t have time to take a screenshot).

### LibreTube version

0.15.0

### Android version

android9

### Other details

![Screenshot_20230602-183945](https://github.com/libre-tube/LibreTube/assets/112433952/0a78ff3a-4a87-463f-b26c-82ce6dc58daf)

In addition, I actually encountered some problems, such as the playback history list that has not been continuously updated since the previous versions (the data has been cleared and the new version has been reinstalled), and there is also a problem of searching for music after installing the latest version of the app When you press the back button during playback, there may be a problem that the search icon and the icon of the setting menu overlap (but it will return to normal after restarting). These two items currently have little impact. The main reason is to correct the stability of playing music.

Attached are some adjusted settings:
1. Originally, the built-in entity was selected, but because it cannot be played from time to time, after reinstalling, no entity is selected, but it still occasionally cannot be played.
2. There is a mode to open the pure audio player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-05 19:19
All the issues you mentioned were already addressed in recent commits, feel free to browse the closed issues.
Next time, please search the closed issues first before opening a new issue (also to save yourself some time). Though I appreciate the efforts you spent into describing the issue as helpful for reproducing as possible!

**Comment by Bnyro** [comment] 2023-06-05 19:21
And since you mentioned some of the issues seem to be YouTube music only, that potentially could be a Piped / NewPipe Extractor issue too in some points, feel free to test the latest nightly build at our NightlyBuilds repo.

**Closed by Bnyro** 2023-06-05 19:21 UTC
Labels: bug
