### ISSUE TITLE
Video repeatedly randomly skipping ahead less than a second

### ISSUE THREAD

**Issue by solimm4sks** [libre-tube/LibreTube#5351] opened 2023-12-18 19:09 UTC
### Steps to reproduce

Happens irregardless of instance. Happens even if piped proxy is disabled/enabled. Happens both with and without HSL. It is more prominent on some videos than others. It happens deterministically for a given video. I can notice it multiple times in the first two minutes of this video: https://youtu.be/Wg39IUZMSFg .

### Expected behavior

There should be no skipping ahead.

### Actual behavior

It exists. 

### LibreTube version

0.20.1

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-12-18 20:13
Duplicate of https://github.com/TeamPiped/Piped/issues/2517

**Closed by Bnyro** 2023-12-18 20:13 UTC
Labels: bug

**Comment by solimm4sks** [comment] 2023-12-18 22:11
Is there currently a way around this? People in the piped issue mention that reloading the page works on the webapp, but I havent been able to figure out a workaround on the LibreTube app.
