### ISSUE TITLE
Crash while switching resolution

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#1974] opened 2022-11-22 04:49 UTC
### Steps to reproduce

It was random

### Expected behavior

Should play fine

### Actual behavior

Crashed this time

### LibreTube version

0.8.0

### Android version

Android 12

### Other details

<details close>
<summary> Logs </summary>

```
java.lang.NumberFormatException: For input string: "LBRY"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.github.libretube.ui.fragments.PlayerFragment.qualityToInt(PlayerFragment.kt:21)
	at com.github.libretube.ui.fragments.PlayerFragment.onQualityClicked(PlayerFragment.kt:142)
	at com.github.libretube.ui.views.CustomExoPlayerView$initializeAdvancedOptions$1$2.invoke(CustomExoPlayerView.kt:7)
	at com.github.libretube.ui.adapters.BottomSheetAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:21)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-22 07:10
Dupe of #1934

**Closed by Bnyro** 2022-11-22 07:10 UTC
Labels: bug
