### ISSUE TITLE
Videos not appearing in Subscriptions view

### ISSUE THREAD

**Issue by ms866** [libre-tube/LibreTube#6520] opened 2024-09-21 06:44 UTC
### Steps to reproduce

1. Subscribe to multiple channels
2. Create more than 2 subscription groups
3. Select one of the groups (optional, bug is reproducable on All group as well)
4. Refresh to get latest videos
5. Not all latest videos from all channels belonging to selected group would appear
6. Navigate to a channel you know has a later video released but not visible in subscriptions view
7. You'll find the latest videos and play them just fine
One more note, the same channel that is missing latest video(s) still has some older videos in the subscriptions view. So it's not a bug with a whole channels content not appearing in the subscriptions view

Device info:
Manufacturer: Google
Board: husky
Arch: arm64-v8a
Android SDK: 34
OS: Android 14
Display: 1344x2769
Font scale: 1.0

App version: 0.25.2 (57)

### Expected behavior

When refreshing subscriptions view (whether on All group or a custom group) I expect to see the latest videos from all channels within the selected group

### Actual behavior

Missing videos from channels that still show older content but not latest videos even when manually refreshing. Navigating to that same channel shows the latest videos just fine

### LibreTube version

0.25.2 (57)

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-09-21 12:12
Duplicate of https://github.com/TeamPiped/Piped/issues/1130

**Closed by Bnyro** 2024-09-21 12:12 UTC
Labels: bug
