### ISSUE TITLE
[ Video / Audio ] not working

### ISSUE THREAD

**Issue by DracX3** [libre-tube/LibreTube#6235] opened 2024-07-14 10:52 UTC
### Steps to reproduce

• Play any video 
• It not working 80% of time but even if it is playing then it stops after a minute or so.

### Expected behavior

Video & audio use to work flawlessly in the past.

### Actual behavior

Video is not working, it's stopping in between the video or in the audio player, or buffering too much, or Stops to work suddenly.

### LibreTube version

0.24.0

### Android version

Android 14

### Other details

• If I am playing any video it's not working many times, even if it's working it stopped after 1 video or in between video.
• It sometimes fixed if i change "instance" but it's very annoying to change it again & again and still not working many times
• If I open a video which is geolocked in my country its also not playing i tried all the instances

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-07-14 11:27
Duplicate of https://github.com/TeamNewPipe/NewPipe/issues/11191

**Closed by Bnyro** 2024-07-14 11:27 UTC
Labels: bug
