### ISSUE TITLE
Some GUI suggestions 

### ISSUE THREAD

**Issue by SameenAhnaf** [libre-tube/LibreTube#4426] opened 2023-08-11 14:31 UTC
### Describe your suggested feature

- [x] Keep deep accent colour for playlist video number similar to selected channel group. IMO, keeping same accent colour for video number and list of playlists might be an overkill. So, as a solution, apply deep accent colour only behind headlines `Watch History`, `Bookmarks` and `Playlists`. White background should be applied for lists below them.

![Screenshot_20230811-185324](https://github.com/libre-tube/LibreTube/assets/79245641/9f565396-a6d2-42c7-a711-3a384019b327)
![Screenshot_20230811-185249](https://github.com/libre-tube/LibreTube/assets/79245641/cd1519d3-e118-4c70-bea5-da39e34ff2ef)

- [x] Show only one `RESET` button to quickly adjust both speed and pitch and close speed menu too on a single click. Keep it as in the same line of `Skip Silence` option. No need for two `RESET` buttons.
- [x] Move `Skip Silence` checkbox of playback speed menu on the left instead of a switch button on right corner.
- Show remaining time adjusted with playback speed. // not planned
- On landscape full screen player, stick all options on the left half of the screen, no need to cover entire screen.
![Screenshot_20230813-042825~2](https://github.com/libre-tube/LibreTube/assets/79245641/c1b9ed81-e26c-4406-bbf1-6a5d37a441f9)  // not planned

- [x] I don't understand the utility of three dots menu on audio player. Just include `Download` button on bottom row.
![Screenshot_20230811-204830](https://github.com/libre-tube/LibreTube/assets/79245641/7ba9bb54-016e-433d-99db-3a12bf20f558)
- [ ] Make all scrollers grabbable to easily reach top of the page. Also, move position holders of videos in play queue to left of thumbnail.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-12 07:16
Changing the autoplay icon has already been discussed in an other issue and I currently think that our icon is good enough to stay in the app.

Always showing the progress bar has already been rejected in previous issues and still is not planned, also because it doesn't fit the overall app UI.

I don't see the point of a playback speed/pitch reset button, since you can just reset the individual options for it which is only a single click more. There's no reason to bloat the UI with that.

> Embed orderly, shuffled and reverse playback into the same icon.
>
Could you please explain what you mean exactly?

>  In order to access playback speed, audio tracks, captions and resolution, show detailed menu right below the selected option for both main & full screen players and don't cover the entire screen in case of full screen player. Much more easier to access.
> 
That's how the app behaved once, however I changed it for UI reasons - and still think it's the right decision to keep it as is. There's also an other open issue on accessing them quicker.

> Also, move position holders of videos in play queue to left of thumbnail.
> Why?

**Comment by Bnyro** [comment] 2023-08-12 07:18
Please separate such suggestions into a separate issues next time - it makes it much easier to track them.

**Comment by Bnyro** [comment] 2023-08-12 18:06
> Now there are separate icons from Reverse and Shuffle queue action. Instead of two separate icons, embed these actions into a single icon with three states: Orderly (as usual), Shuffled and Reverse.
>
The actions can't be undone. For instance, if you shuffle the queue, you can't restore the previous order.

I'm not sure if you tested the latest debug builds, but recently I added an option to sort the queue by upload date, views, and uploader name. The sort options are being listed in a dialog.

So I think it would make sense to remove the `reverse` and `shuffle` action and add them to the new sort dialog instead as options. What do you think?

**Comment by Bnyro** [comment] 2023-08-13 09:07
>  Show remaining time adjusted with playback speed.
>
I don't think any other app behaves like that when it comes to the calculation of the remaining time, so I honestly doubt that'd be a good idea that's self-explaining to users.

**Comment by Bnyro** [comment] 2023-08-13 09:08
> On landscape full screen player, stick all options on the left half of the screen, no need to cover entire screen.
>
Doing that will require creating a different layout for landscape than for the portrait mode - which is not planned, or a duplicate of #3198.

**Comment by Bnyro** [comment] 2023-08-13 09:24
> Show only one RESET button to quickly adjust both speed and pitch and close speed menu too on a single click. Keep it as in the same line of Skip Silence option. No need for two RESET buttons.
>
I don't think it would be self-explaining what they actually do. I think we could remove the reset buttons in general, since we now have shortcuts to choose certain speeds above the slider, so the user can just choose "1.0" instead of clicking the reset button.

**Comment by Bnyro** [comment] 2023-08-13 10:10
Yes, but that would be the same problematic.

**Comment by Bnyro** [comment] 2023-08-19 08:39
> Make all scrollers grabbable to easily reach top of the page. Also, move position holders of videos in play queue to left of thumbnail.
>
Please make a list with all parts of the app where scrollbars are missing in a new issue.

**Comment by Bnyro** [comment] 2023-08-19 08:40
Concerning moving the position holders to the left, I don't agree because I think that makes it harder to grab them.

**Closed** 2023-08-19 08:42 UTC
Labels: enhancement
