### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by noClaps** [libre-tube/LibreTube#2825] opened 2023-01-22 13:56 UTC
### Steps to reproduce

1. search for a video
2. play video from search results

### Expected behavior

video should play

### Actual behavior

app crashed. on reopening, the below crash report was generated.

### LibreTube version

0.11.0

### Android version

Android 13

### Other details

```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 215: Expected string literal but 'null' literal was found at path: $.bannerUrl
Use 'coerceInputValues = true' in 'Json {}` builder to coerce nulls to default values.
JSON input: .....eusercontent.com","bannerUrl":null,"description":"","nextpag.....
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:1)
	at kotlinx.coroutines.SupervisorKt.JsonDecodingException(Supervisor.kt:2)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:64)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:34)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:7)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeKeyString(StringJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeString(AbstractJsonLexer.kt:3)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeString(StreamingJsonDecoder.kt:14)
	at org.chromium.net.UploadDataSink.decodeStringElement(UploadDataSink.java:6)
	at com.github.libretube.api.obj.Channel$$serializer.deserialize(Channel.kt:119)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(StreamingJsonDecoder.kt:67)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:25)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:52)
	at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:12)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:57)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:5)
	at com.google.net.cronet.okhttptransport.CronetCallFactory$CronetCall$2.onSuccess(CronetCallFactory.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ddcc3d2, Dispatchers.Main.immediate]
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-22 14:17
Duplicate of #2813

**Closed by Bnyro** 2023-01-22 14:17 UTC
Labels: bug
