### ISSUE TITLE
The app  can't play 4K Videos

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#5468] opened 2024-01-09 22:08 UTC
### Steps to reproduce

Open a video containing this(4K) quality, then select it, it is not possible to play it, and it will play only in 1080-Limited quality at most.
![Screenshot_2024-01-10-01-31-44-713_com github libretube](https://github.com/libre-tube/LibreTube/assets/74877307/5e14560e-db05-4b75-b904-6b2c32b50750)

### Expected behavior

It is quite clear.

### Actual behavior

It is quite clear.

### LibreTube version

the last version

### Android version

Android 10

### Other details

It is quite clear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-01-09 22:33
Duplicate of #4255

**Closed by Bnyro** 2024-01-09 22:33 UTC
Labels: bug
