### ISSUE TITLE
Error opening channel link in LibreTube.

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3387] opened 2023-03-25 14:19 UTC
### Steps to reproduce

1.Go to YouTube
2.Open any channel link in LibreTube.
4.ERROR

### Expected behavior

The channel should appear in LibreTube without errors

### Actual behavior

java.lang.NullPointerException: Can't toast on a thread that has not called Looper.prepare()
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:167)
	at android.widget.Toast.getLooper(Toast.java:265)
	at android.widget.Toast.<init>(Toast.java:250)
	at android.widget.Toast.makeText(Toast.java:865)
	at android.widget.Toast.makeText(Toast.java:853)
	at com.github.libretube.ui.fragments.PlayerFragment$playVideo$1.invokeSuspend(PlayerFragment.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@921c833, Dispatchers.IO]
    

### LibreTube version

0.13.0 Latest debug

### Android version

Android 12

### Other details

https://user-images.githubusercontent.com/124310688/227722795-a2808675-b3d6-4613-90d2-5ed73ec19c3c.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-25 16:51
duplicate of #3378

**Closed by Bnyro** 2023-03-25 16:51 UTC
Labels: bug
