### ISSUE TITLE
Allow to select download folder

### ISSUE THREAD

**Issue by popogomo** [libre-tube/LibreTube#3683] opened 2023-05-01 01:37 UTC
### Describe your suggested feature

Hi all,

Can you please add an option for us to choose which folder LibreTube should download videos/audio into? It is very inconvenient to browse to LibreTube's root folder every time to open downloaded content with 3rd party player (not LibreTube).

Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-01 06:47
Duplicate of #2041 and #3570

**Closed by Bnyro** 2023-05-01 06:47 UTC
Labels: enhancement
