### ISSUE TITLE
illegal argument? 

### ISSUE THREAD

**Issue by Wildeyed2** [libre-tube/LibreTube#5302] opened 2023-12-06 14:33 UTC
### Steps to reproduce

Hello
I used to very much like libretube but lately it would stop fonctionning and the error message reads as bellow.

Then it would start working again 

java.lang.IllegalArgumentException
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:80)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:164)
	at com.github.libretube.util.OfflineTimeFrameReceiver.<init>(SourceFile:18)
	at com.github.libretube.ui.activities.OfflinePlayerActivity$playVideo$1.invokeSuspend(SourceFile:553)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c7d1d72, Dispatchers.Main.immediate]
    

### Expected behavior

It should let me watch videos

### Actual behavior

But I cant
I cant watch downloaded videos either 

### LibreTube version

0.19.0

### Android version

android 9

### Other details

It seems to happen mainly when I am home. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-12-06 14:35
duplicate of #5237

**Closed by Bnyro** 2023-12-06 14:35 UTC
Labels: bug
