### ISSUE TITLE
Issue Report for LibreTube Nightly Version 0.23.2

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#6178] opened 2024-06-23 19:39 UTC
### Steps to reproduce

1. Use LibreTube with an authenticated instance to avoid frequent logouts.
2. Observe that the app automatically selects the server without choosing the proper instance, but somehow it's set in the right instance.
3. Navigate to the subscription page and notice that it only loads data from the past week.
4. Change the instance and try again, but the issue persists.
5. Use the app without an account, and it works fine.
6. Experience several crashes during use.

### Expected behavior

- The app should allow users to manually select the instance and authenticate properly.
- The subscription page should load all data, not just data from the past week.
- The app should function without crashes.
- A mechanism to export or store crash reports should be available.

### Actual behavior

- The app automatically selects the server, sometimes without choosing the proper instance.
- The subscription page only loads data from the past week.
- Changing the instance does not resolve the issue.
- The app works fine without an account.
- Multiple crashes occur during use.
- There is no way to export or store crash reports, only a bubble notification.

### LibreTube version

0.23.2

### Android version

android 13

### Other details

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{587e1bf u0 com.github.libretube.debug/com.github.libretube.services.OnlinePlayerService}
    at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(Unknown Source:16)
    at android.app.ActivityThread.throwRemoteServiceException(Unknown Source:62)
    at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(Unknown Source:443)
    at android.os.Handler.dispatchMessage(Unknown Source:19)
    at android.os.Looper.loopOnce(Unknown Source:182)
    at android.os.Looper.loop(Unknown Source:82)
    at android.app.ActivityThread.main(Unknown Source:123)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
    at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
    at android.app.ContextImpl.startServiceCommon(Unknown Source:219)
    at android.app.ContextImpl.startForegroundService(Unknown Source:6)
    at android.content.ContextWrapper.startForegroundService(Unknown Source:2)
    at android.content.ContextWrapper.startForegroundService(Unknown Source:2)
    at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1128)
    at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:700)
    at com.github.libretube.helpers.BackgroundHelper.playOnBackground(BackgroundHelper.kt:47)
    at com.github.libretube.helpers.BackgroundHelper.playOnBackground$default(BackgroundHelper.kt:24)
    at com.github.libretube.helpers.NavigationHelper.navigateVideo(NavigationHelper.kt:62)
    at com.github.libretube.helpers.NavigationHelper.navigateVideo$default(NavigationHelper.kt:49)
    at com.github.libretube.ui.adapters.PlaylistAdapter.onBindViewHolder$lambda$4$lambda$0(PlaylistAdapter.kt:91)
    at com.github.libretube.ui.adapters.PlaylistAdapter.$r8$lambda$r1boGDH3SvgPUcr1AhMY51B0yOU(Unknown Source:0)
    at com.github.libretube.ui.adapters.PlaylistAdapter$$ExternalSyntheticLambda2.onClick(D8$$SyntheticClass:0)
    at android.view.View.performClick(Unknown Source:17)
    at android.view.View.performClickInternal(Unknown Source:3)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(Unknown Source:8)
    at android.os.Handler.handleCallback(Unknown Source:2)
    at android.os.Handler.dispatchMessage(Unknown Source:4)
    ... 6 more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-06-30 15:21
> The app should allow users to manually select the instance and authenticate properly.
>
That's the case, and I can't reproduce what you described above.
> The subscription page should load all data, not just data from the past week.
>
That's controlled by the Piped instance and configured by its admin. Self-host Piped to get more control / more videos.
> The app should function without crashes.
>
It's impossible to create a app with the amount of features as LibreTube has completely bugfree. If you don't think so, you've never actually participated in any larger software project.
> A mechanism to export or store crash reports should be available.
>
You can use 3rd party apps like MatLog for that, it's out of scope for LibreTube directly.

**Closed by Bnyro** 2024-06-30 15:21 UTC
Labels: bug
