### ISSUE TITLE
App does not return to previous state properly

### ISSUE THREAD

**Issue by rancidfrog** [libre-tube/LibreTube#1558] opened 2022-10-14 13:31 UTC
# Steps to reproduce
1. Start playing or pausing a video in Libretube
1. Click on Home button or recents button

![](https://i.imgur.com/iPLOBin.png)
1. Select Libretube app from recents, or double click recents button to take you back to app, or select libretube from home
![](https://i.imgur.com/yNBn0Hw.png)
![](https://i.imgur.com/wop8xFW.png)
1. Libretube will start playing video again, even if video was paused, and even if video was already playing which causes video to stop and play again.

# Expected behavior
App should return to previous state, without forcing Play.

# Actual behavior
App re Plays whatever video was playing, causing a stop and play if video was playing, and causing a paused video to resume playback

# LibreTube version
0.6.1

# Android version
Android 11

# Other details

# Acknowledgements
- [x]  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
- [x]  I have written a short but informative title.
- [x]  I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2022-10-14 15:06
Can't reproduce. https://user-images.githubusercontent.com/50032603/195879935-517b4290-c277-425d-b7b5-fb5a7e825fb8.mp4

**Comment by akano12** [comment] 2022-10-14 15:07
Can't reproduce.

https://user-images.githubusercontent.com/50032603/195880198-f24ed96f-ddaf-4fd8-a93c-236b1212b151.mp4

**Comment by Bnyro** [comment] 2022-10-15 13:47
Can't reproduce either, gonna close it therefore.

**Closed by Bnyro** 2022-10-15 13:47 UTC

**Comment by rancidfrog** [comment] 2022-10-28 13:12
It keeps happening to me.
I am watching a video, press pause, double tap recents to go to previous app, double tap recents to return to libretube, and paused video is minimised but Played

**Comment by rancidfrog** [comment] 2022-10-28 13:47
https://user-images.githubusercontent.com/6155036/198620777-ad4ee62d-2ba0-47b1-a39a-1aa7a350ce52.mp4

Here you can cleasly see, that when I switch back to libretube, a previous video gets played, even when I start playing a new video, on return it restarts the previous video.
Each time I swigch to libretube, the video that is playing in the background, gets restarted.
No idea what is triggering it.
