### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by JimitSoni18** [libre-tube/LibreTube#6211] opened 2024-07-11 15:48 UTC
### Steps to reproduce

open libretube -> play video -> toast pops - "Watch on latest version of youtube"

### Expected behavior

play video

### Actual behavior

does not play video

### LibreTube version

0.23.1

### Android version

14

### Other details

Libretube, along with newpipe and revanced have stopped working, it shows a toast when video is played saying "Watch on latest version of youtube"
however, p!ped still appears to be working.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-07-11 15:58
Duplicate of https://github.com/libre-tube/LibreTube/issues/6208

**Closed by Bnyro** 2024-07-11 15:58 UTC
Labels: bug
