### ISSUE TITLE
Notification playback controls don't work on Android 10

### ISSUE THREAD

**Issue by DanielProg39** [libre-tube/LibreTube#6100] opened 2024-06-03 15:36 UTC
### Steps to reproduce

1. Open the video
2. Open the notification bar
3. Tap on any button in the playback notification

### Expected behavior

All buttons perform their respective actions

### Actual behavior

Tapping on buttons doesn't change anything, only the progress bar works

### LibreTube version

0.23.2

### Android version

Android 10

### Other details

Recording:

https://github.com/libre-tube/LibreTube/assets/63293432/9524f9ee-8d2f-4dba-8144-955725dce12f

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by DanielProg39** [comment] 2024-06-03 20:49
Rebooting, reinstalling either F-droid, GitHub, Debug versions doesn't help

**Comment by DanielProg39** [comment] 2024-06-03 20:59
I just discovered #6050, so this seems to be a duplicate. I didn't search in closed issues. However, the proposed solution doesn't work in this case for some reason.

**Comment by fernzi** [comment] 2024-06-09 15:51
Doesn't work for me either with a just-flashed LineageOS 17.1 (also Android 10). Had nothing but the base system installed prior, so don't think it was caused by updating.

**Comment by DanielProg39** [comment] 2024-06-12 07:57
Upd: this issue was also discovered on the Android 12 (OneUI) Samsung tablet.

**Comment by slimshady045** [comment] 2024-08-26 18:56
25.1

**Comment by Bnyro** [comment] 2024-11-17 17:35
Fixed by https://github.com/libre-tube/LibreTube/pull/6732 (not yet released)

**Closed by Bnyro** 2024-11-17 17:35 UTC
Labels: bug, help wanted
