### ISSUE TITLE
App freezes to full screen

### ISSUE THREAD

**Issue by dhishkyaon** [libre-tube/LibreTube#28] opened 2022-02-14 18:05 UTC
After playing a video in full screen, the app itself freezes to full screen mode.
![Screenshot_20220214-233523.png](https://user-images.githubusercontent.com/88529066/153921098-925819b1-7759-48ec-9d61-fb234ddb8382.png)

**Comment by rimthekid** [comment] 2022-02-14 18:24
Can I know the android version?

**Comment by saurabhinabys** [comment] 2022-02-14 18:36
it seems after returning from fullscreen, app doesn't avoid notched area.

**Comment by BrightDV** [comment] 2022-02-14 18:42
Yes, even in latest version

**Comment by rimthekid** [comment] 2022-02-14 19:00
could you all tell me your android versions?

**Comment by saurabhinabys** [comment] 2022-02-14 19:24
Android 11
ROM: CARBON ROM
Device: Xiaomi Redmi note 10 pro

**Comment by BrightDV** [comment] 2022-02-14 20:19
Android 11

ROM: Stock ROM (Official) 

Device: Samsung A21s

**Comment by dhishkyaon** [comment] 2022-02-15 01:59
@rimthekid Android 12, Pixel 4a

**Comment by dhishkyaon** [comment] 2022-02-15 05:08
also the mini-player is not in right position after playing a video in full-screen mode.

![Screenshot_20220215-101333.jpg](https://user-images.githubusercontent.com/88529066/153996398-a0fdc598-7290-4a8e-813d-b0d28d8b687e.jpg)

**Comment by rimthekid** [comment] 2022-02-15 05:25
I'm already testing the app on android 10 and 5 and these are fine for them. I'll start testing on more versions.

**Comment by saurabhinabys** [comment] 2022-02-15 06:56
maybe these are due to notched displays and type n height of navigation drawer.

**Comment by rimthekid** [comment] 2022-02-15 07:20
hmm mini player is really tricky there is some android framework issues too that I can't do anything about it.

**Comment by saurabhinabys** [comment] 2022-02-15 08:02
it's your project, and i know zero coding. wouldn't prioritising implementing very basic features that you list be better, then ironing out these ui bugs? or is it better to figure out these issues first? Maybe some more knowledgeable people will join as you move forward towards a feature rich application.

**Comment by rimthekid** [comment] 2022-02-15 08:54
I think it's best to do both so the app gets better and better by time

**Comment by rimthekid** [comment] 2022-03-05 06:50
tried to fix this in this [commit](https://github.com/libre-tube/LibreTube/commit/ccca80656b8b7cf66cc7711e5493a349b98f9422)

**Comment by dhishkyaon** [comment] 2022-03-05 13:05
@rimthekid works fine for now

**Comment by rimthekid** [comment] 2022-03-05 13:06
Cool should I close this issue?

**Comment by dhishkyaon** [comment] 2022-03-05 13:07
yes. i will report if anything happens

**Closed** 2022-03-05 13:11 UTC

**Comment by ManuLinares** [comment] 2022-03-15 19:24
I'm on Android 12 and it doesn't work.

How to reproduce:

- Play any video and click to go fullscreen (it fulls the screen in vertical mode)
- Rotate device to horizontal.
- Player stops, and minimizes to the bottom. (No fullscreen playback)
