### ISSUE TITLE
Crash When Playing in Background

### ISSUE THREAD

**Issue by vedxp** [libre-tube/LibreTube#1623] opened 2022-10-20 13:21 UTC
### Steps to reproduce

Played a video and tapped on audio button.

### Expected behavior

It should play normally.

### Actual behavior

It crashed.

Here's the error log:

```
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{12d81 u0 com.github.libretube/.services.BackgroundMode}
 at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2078)
 at android.app.ActivityThread.access$2800(ActivityThread.java:259)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:233)
 at android.os.Looper.loop(Looper.java:344)
 at android.app.ActivityThread.main(ActivityThread.java:8248)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

### LibreTube version

0.6.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-10-21 16:33
Hmm, can't reproduce and in theory `startForeground()` is being called directly in the beginning. Does that happen every time or only sometimes?

**Comment by VedxP** [comment] 2022-10-22 04:58
> Hmm, can't reproduce and in theory `startForeground()` is being called directly in the beginning. Does that happen every time or only sometimes?

Encountered 2 times till now.

Will report if I encouter again :)

**Comment by Bnyro** [comment] 2022-12-16 14:15
Does the issue still occur?

**Comment by vedxp** [comment] 2022-12-16 15:40
> Does the issue still occur?

Not yet in `0.9.0` :)

**Comment by Bnyro** [comment] 2022-12-16 15:42
Then we'll just close it for now ;)

**Closed by Bnyro** 2022-12-16 15:42 UTC
Labels: bug
