### ISSUE TITLE
Libretube crashed

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#3373] opened 2023-03-24 18:13 UTC
### Steps to reproduce

After playing this video with autofullscreen in shorts enabled, when video finished and × button on the player is presded,libretube crashed. 

https://www.youtube.com/watch?v=6sTnF9ockMg

### Expected behavior

It shouldn't crash. 

### Actual behavior

It crashed.

### LibreTube version

0.13.0

### Android version

Android 7.1.1

### Other details

java.lang.NullPointerException
	at com.github.libretube.ui.fragments.PlayerFragment$initializeTransitionLayout$1.onTransitionChange(PlayerFragment.kt:14)
	at com.github.libretube.ui.views.SingleViewTouchableMotionLayout$2.onTransitionChange(SingleViewTouchableMotionLayout.kt:25)
	at androidx.constraintlayout.motion.widget.MotionLayout.fireTransitionChange(MotionLayout.java:73)
	at androidx.constraintlayout.motion.widget.MotionLayout.setState(MotionLayout.java:5)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluate(MotionLayout.java:276)
	at androidx.constraintlayout.motion.widget.MotionLayout.onLayout(MotionLayout.java:28)
	at android.view.View.layout(View.java:19065)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19065)
	at android.view.ViewGroup.layout(ViewGroup.java:5935)
	at androidx.constraintlayout.motion.widget.MotionController.interpolate(MotionController.java:630)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:363)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:916)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2644)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2386)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-24 18:14
Duplicate of #3372

**Closed by Bnyro** 2023-03-24 18:14 UTC
Labels: bug
