### ISSUE TITLE
App crash after div by 0

### ISSUE THREAD

**Issue by wiryfuture** [libre-tube/LibreTube#1212] opened 2022-09-03 22:50 UTC
### Steps to reproduce

1. Be watching any video, more likely on streams.
2. App crashes
3. Will not open for an arbitrary time

### Expected behavior

Anything but that; no crash?

### Actual behavior

java.lang.ArithmeticException: divide by zero
	at com.github.libretube.util.SetWatchProgressLengthKt$setWatchProgressLength$2.onGlobalLayout(SetWatchProgressLength.kt:5)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1061)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3260)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2180)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8814)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
	at android.view.Choreographer.doCallbacks(Choreographer.java:926)
	at android.view.Choreographer.doFrame(Choreographer.java:859)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
    

### LibreTube version

0.5.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-09-04 06:36
Dupe of #1092

**Closed by Bnyro** 2022-09-04 06:36 UTC
Labels: bug

**Comment by wiryfuture** [comment] 2022-09-04 22:55
> Dupe of #1092

That issue says specific channels, this also occurs at any time on any page, such as as soon as the app opens into the subscriptions tab or home tab and you have pressed nothing.

**Comment by Bnyro** [comment] 2022-09-05 06:50
Turn off WiFi, go to settings, disable watch positions and clear them. That fixes it until the next update.

**Comment by sleeply4cat** [comment] 2022-09-10 00:31
> That fixes it until the next update.
The bug is like 27d old; is there any chance it'll be fixed?
