### ISSUE TITLE
Show LibreTube in list of apps when attempting to open YouTube link

### ISSUE THREAD

**Issue by jaswinder77** [libre-tube/LibreTube#3463] opened 2023-03-31 15:00 UTC
### Describe your suggested feature

The app should show up in the list of apps when a YouTube link is clicked. Currently, the app is shown when we **share** a YouTube link but not when we attempt to **open** a YouTube link.
Sample YouTube link: https://www.youtube.com/watch?v=_tpB-B8BXk0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2023-03-31 21:11
Have you configured the ```set as default``` settings?

**Comment by Bnyro** [comment] 2023-04-01 06:02
That's interesting, however that seems to be an issue to Android's share system and not the app itself as for example I can't seem to reproduce the issue. Anyways link opening is already supported, so I close this as done.

**Closed by Bnyro** 2023-04-01 06:02 UTC
Labels: enhancement
