### ISSUE TITLE
Video doesn't play if piped proxy is disabled

### ISSUE THREAD

**Issue by MF-Debug** [libre-tube/LibreTube#5524] opened 2024-01-21 17:05 UTC
### Steps to reproduce

1. Enable disable piped proxy
2. Click on any video
3. Video doesn't load or play

### Expected behavior

Videos should load and play normally

### Actual behavior

Videos doesn't load or play, just shows blank screen

### LibreTube version

0.21.1

### Android version

LOS 18.1

### Other details

https://github.com/libre-tube/LibreTube/assets/6173607/cd6f91ce-6cf4-4f07-a476-3461007b4336

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by robcle** [comment] 2024-01-22 02:26
My phone does this as well. GrapheneOS Pixel 8 Pro 
UQ1A.240105.004.2024011600

**Comment by clicky6** [comment] 2024-01-26 04:37
The "disable proxy" option only works when you enable HLS in the audio and video settings due to YouTube changes.

**Comment by person10301** [comment] 2024-01-28 11:10
If I understand correctly, the developer has already replied that the problem has been "fixed":
https://github.com/libre-tube/LibreTube/issues/5391

**Comment by robcle** [comment] 2024-02-01 16:53
Can confirm "NOT FIXED"

**Comment by robcle** [comment] 2024-02-01 16:55
![Screenshot_20240201-105452](https://github.com/libre-tube/LibreTube/assets/135041335/d34e3eea-6317-4296-af19-64d674dcd41e)

**Comment by Bnyro** [comment] 2024-02-04 09:47
> If I understand correctly, the developer has already replied that the problem has been "fixed": #5391
>
It had been fixed until YouTube broke it again...

**Comment by Pamilg8** [comment] 2024-02-06 18:05
I don't know why, already kavin.rocks works fine. Maybe you applied IPV6? 
Sometimes there are not many problems due to traffic. 
I don't care about YT proxy.
Thank you very much☺️

**Comment by Undisputed00x** [comment] 2024-03-20 16:17
> The "disable proxy" option only works when you enable HLS in the audio and video settings due to YouTube changes.

I can confirm that this works! 
Piped servers dont provide accurate subs timeline specially for livestreams and the only fix for this is by disabling the piped proxies.

Hope this issue gets resolved soon.

**Closed** 2024-03-28 15:36 UTC
Labels: bug
