### ISSUE TITLE
Only Videos section present in channel page

### ISSUE THREAD

**Issue by au28** [libre-tube/LibreTube#1894] opened 2022-11-18 14:46 UTC
### Steps to reproduce

1.Go to any channel on app
2.Try to see different sections

### Expected behavior

LibreTube should show all the sections including Playlists,Livestreams,Channels etc

### Actual behavior

Only Videos section is visible.

### LibreTube version

0.7.1

### Android version

Android 13

### Other details

![Screenshot_20221118-195618](https://user-images.githubusercontent.com/49833783/202731101-a6378f74-aaa0-4cb8-ba94-55a9ad9d2cc0.png)

Same channel as viewed on piped.video
https://piped.video/channel/UCjCwcQUtZeyj5_NoNaUoKtQ

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-18 14:52
dupe of #1869, #1855, #1846 and #1830

**Closed by Bnyro** 2022-11-18 14:52 UTC
Labels: bug

**Comment by ARBoyGo** [comment] 2022-11-19 05:34
Oru malayali haha machu..
