### ISSUE TITLE
The Controls Fade transition is broken

### ISSUE THREAD

**Issue by electr1fy0** [libre-tube/LibreTube#2782] opened 2023-01-21 02:47 UTC
### Steps to reproduce

1. Play a video.
2. Tap to see the player controls
3. Wait until it starts to disappear automatically.
4. See them half cut at the screen edge.
![Screenshot_20230121-080959](https://user-images.githubusercontent.com/87616300/213840498-92ad04a5-c4b0-4082-a7fc-8c18e7f75a11.png)

### Expected behavior

Controls should smoothly fade out as one animation 

### Actual behavior

Controls fade out halfway and then get stuck half cut by screen borders and then glitch into nothingness after a few seconds.

### LibreTube version

0.10.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-21 07:37
Duplicate of #2770

**Closed by Bnyro** 2023-01-21 07:37 UTC
Labels: bug
