### ISSUE TITLE
Playback pauses while switching back & forth between background playback

### ISSUE THREAD

**Issue by asklow** [libre-tube/LibreTube#1792] opened 2022-11-07 21:32 UTC
### Steps to reproduce

1. Install libretube
2. Start playing something
3. Put it in bg (press home)
4. 4. Come back to app from notifications

### Expected behavior

Playback should continue without hiccups & any watchtime resets.

### Actual behavior

Video pauses everytime I open app from background state.

### LibreTube version

0.7.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-11 16:26
Can't reproduce, it just continues playing fine for me.
@VedxP @rozari0 @akano12, can anyone of you reproduce the issue?

**Comment by rozari0** [comment] 2022-11-11 18:02
> Can't reproduce, it just continues playing fine for me. @VedxP @rozari0 @akano12, can anyone of you reproduce the issue?

Can confirm this issue exists. Tested with [86a1a7c](https://github.com/libre-tube/LibreTube/commit/86a1a7c3dfc6a528ab3bad5f1f7636fcbb40413b) and 0.7.0 .

**Comment by Vitalya-code** [comment] 2022-11-11 18:45
I have the same issue. Android 13

**Comment by akano12** [comment] 2022-11-11 22:38
Can't reproduce.
Android 12

**Comment by akano12** [comment] 2022-11-11 22:42
> Hmm, could anyone please share a screen recording? Thanks in advance!

https://user-images.githubusercontent.com/50032603/201440621-9403309c-efe8-40f8-a7b2-f4eca1cb8708.mp4

**Comment by akano12** [comment] 2022-11-11 22:43
Can't reproduce.
Android 12
https://user-images.githubusercontent.com/50032603/201440678-e31c2325-a0c0-4fc2-bf3b-a8c72903f548.mp4

**Comment by akano12** [comment] 2022-11-11 22:44
Can't reproduce, works properly

https://user-images.githubusercontent.com/50032603/201440718-e6badc9f-a7f3-4f0e-9f57-f19e5b70fc46.mp4

**Comment by akano12** [comment] 2022-11-11 22:50
Can't reproduce, works properly


https://user-images.githubusercontent.com/50032603/201441237-b38450ac-2446-413b-97ce-4cf7961ed137.mp4

**Comment by rozari0** [comment] 2022-11-12 03:41
> Can't reproduce, works properly (Android 12)
> Screen_Recording_20221112_004957_LibreTube.mp4

I misunderstood issue, I thought background playback = audio mode.

**Comment by VedxP** [comment] 2022-11-12 12:53
> Can't reproduce, it just continues playing fine for me. @VedxP @rozari0 @akano12, can anyone of you reproduce the issue?

Can't reproduce, seems fine to me :)
LT  [b9451e0](https://github.com/libre-tube/LibreTube/actions/runs/3450418044)

**Comment by Bnyro** [comment] 2022-11-12 13:42
Thank you all for testing <3
Gonna close this as it seems to be device specific, maybe changing some battery restrictions will help solving the issue for you @asklow

**Closed by Bnyro** 2022-11-12 13:42 UTC
Labels: bug

**Comment by VedxP** [comment] 2022-11-13 18:08
> Did you guys disable PiP & checking true background playback ?

Tried both, PIP enabled & disabled
No issue here :)

Steps:
- Play a video 
- Tap on home button 
- Tap on LT Player from notifications 
- Video doesn't interrupt upon coming either from background playback or popup mode.

**Comment by VedxP** [comment] 2022-11-13 18:14
Okay, the player reloads upon returning from notifications if you use `audio` mode.

[as @rozari0 already told here](https://github.com/libre-tube/LibreTube/issues/1792#issuecomment-1312347623)
@Bnyro

**Comment by rozari0** [comment] 2022-11-13 18:32
I tried to reproduce this again, still the same. Is it still in 0.7.1?

**Comment by rozari0** [comment] 2022-11-13 18:38
> Nop. `0.7.0`. I've just re-installed it via fdroid repo.

Can you test 0.7.1 from GitHub release? Seems like f-droid still providing old version.

**Comment by Bnyro** [comment] 2022-11-13 19:12
> @rozari0 0.7.1 fixed it.
> I've read the changelog but it did not mention about this fix in it. Strange.
>
Well, I don't sometimes make a PR with multiple different fixes and am sorta too lazy to include them all in the changelog, not sure what could have fixed yours.

**Comment by Bnyro** [comment] 2022-11-13 19:13
> (offtopic) is there a libretube fdroid repo ?
>
No, there's none, I don't own any server or something which would be required in order to host an F-Droid repo. However, we're on IzzyOnDroid which updates way faster than F-Droid usually.

**Comment by Bnyro** [comment] 2022-11-13 19:22
> Welp, that's okay but... You're not utilizing git's full potential then 😌
> I think commit messages are intended to point out such key fixes, bugs & improvements.
>
Well, I use them properly ;)
The issue is that GitHub generates changelogs bases on the title of pull request, not commit messages!

**Comment by Bnyro** [comment] 2022-11-13 19:23
> Isn't there anyway to just mirror github's release APKs as host for the repo ?
>
No, we would need to host an F-Droid server, see 
https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/

**Comment by VedxP** [comment] 2022-11-14 04:09
> Okay, the player reloads upon returning from notifications if you use `audio` mode.
> 
> [as @rozari0 already told here](https://github.com/libre-tube/LibreTube/issues/1792#issuecomment-1312347623) @Bnyro

@Bnyro Should I open a new issue ticket for this ☝️?

**Comment by Bnyro** [comment] 2022-11-14 12:41
> @Bnyro Should I open a new issue ticket for this ☝️?
>
Feel free to do so, however it's not a priority.
