### ISSUE TITLE
When I open the comments section, the player freezes

### ISSUE THREAD

**Issue by Qaz-7** [libre-tube/LibreTube#3029] opened 2023-02-12 07:27 UTC
### Steps to reproduce

1.Play the video
2.See comments.
3.Tap the player.
4.There are no buttons and notification panel indicators.

### Expected behavior

When you touch the player, it should work and the notification bar should appear.

### Actual behavior

https://user-images.githubusercontent.com/124310688/218298481-75d229bb-3c4c-4b43-9de4-43f28e831b5c.mp4

### LibreTube version

0.11.1 Debug

### Android version

Android 12

### Other details

😔

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-12 07:36
Duplicate of #2922

**Closed by Bnyro** 2023-02-12 07:36 UTC
Labels: bug
