### ISSUE TITLE
Fullscreen / Fullscreen exit button issue

### ISSUE THREAD

**Issue by Eliya-Manoj** [libre-tube/LibreTube#5842] opened 2024-03-29 17:48 UTC
### Steps to reproduce

1. Fullscreen Orientaion : Video aspect ratio
2. play video
3. enter fullscreen using button
4. exit fullscreen using button
5. Buffering

https://github.com/libre-tube/LibreTube/assets/90308888/d6d2104e-09cd-4efd-a93b-8fc52cfa3141

Auto rotation ( no issues)

https://github.com/libre-tube/LibreTube/assets/90308888/457683c2-a879-44a2-b8a6-8f0e10aa2576

### Expected behavior

The video never stops and only change the orientation of the video. Only buffer when the network is slow.

### Actual behavior

Buffering after change the orientation using Fullscreen/Fullscreen Exit button. There is no issue if i using auto-rotation.

### LibreTube version

0.22.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-30 15:33
Duplicate of https://github.com/libre-tube/LibreTube/issues/5754

**Closed by Bnyro** 2024-03-30 15:33 UTC
Labels: bug
