### ISSUE TITLE
[BUG] Subscribe button does not follow materia you color scheme

### ISSUE THREAD

**Issue by IceDBorn** [libre-tube/LibreTube#199] opened 2022-05-12 10:46 UTC
### Steps to reproduce

1. Open a video

### Expected behavior

The subscribe button should follow the accent colors of android.

### Actual behavior

The subscribe button is red and white.

### LibreTube version

Up to date with Git

### Android version

12

### Other details

![image](https://user-images.githubusercontent.com/51162078/168053908-fe5acd7f-4d36-4ecc-9f1c-32c0707e0d6f.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-05-12 10:59
It’s not a bug since it’s meant to be red like that, so it’s rather a feature request than a bug

**Comment by IceDBorn** [comment] 2022-05-12 11:33
I think that material colors would look better.

**Comment by archroid** [comment] 2022-05-12 16:10
I personally think fixed red color is better. It just needs a poll in telegram to figure it out.

**Comment by archroid** [comment] 2022-05-12 16:59
You were right. This button will support app theme.

**Comment by Bnyro** [comment] 2022-05-13 09:28
@IceDBorn You can close the issue, added in #200

**Closed** 2022-05-13 12:17 UTC
Labels: bug
