### ISSUE TITLE
Video re-starts loading on orientation change

### ISSUE THREAD

**Issue by cosmoo7** [libre-tube/LibreTube#5538] opened 2024-01-22 18:33 UTC
### Steps to reproduce

1. Set "Screen Orientation" setting in LibreTube to "auto-rotation"
2. Disable "auto-fullscreen" setting in LibreTube, any "Fullscreen orientation" option recreates the issue
3. Enable auto-rotation in your phone
4. Run any video inside of Libretube and change orientation from landscape to portrait or vice versa by rotating your phone

### Expected behavior

The video should keep playing as normal, without loading unnecessarily

### Actual behavior

The video starts loading and possibly rebuffering (?)

### LibreTube version

0.21.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FineFindus** [comment] 2024-01-23 21:49
This may be caused by the resolution change from full screen to portrait mode. When this happens, all buffered data of the old resolution is dropped and the new resolution is loaded, caused buffering, see https://github.com/google/ExoPlayer/issues/2250.

**Comment by Bnyro** [comment] 2024-01-26 13:10
I think this is rather due to the fact that the activity is being re-created when the phone is being rotated.

That's because we use a different layout for the portrait player screen than the landscape player screen.

It could be fixed by storing the player instance in the view model and not re-creating it when the orientation changes.

**Comment by ItzRajvirSingh** [comment] 2024-01-28 03:56
https://github.com/libre-tube/LibreTube/assets/116725577/4a1fe3f5-1c9e-4477-b30c-7d46bc5a6c21

**Comment by Kalytis** [comment] 2024-02-04 09:15
![Screenshot_20240204-003833_LibreTube](https://github.com/libre-tube/LibreTube/assets/31107370/5fa278c7-54c7-4916-a201-5a51be07f9c6)

Not exactly sure how, but sometimes when I open a video then quickly switch to full screen mode, a lateral panel opens, I have no idea how to close it, and when I switch to portrait, video reloads. Then full screen again, it works fine.

**Closed** 2024-02-18 16:00 UTC
Labels: bug, priority: low

**Comment by imwints** [comment] 2024-03-11 20:37
Is this resolved? I can still reproduce something similar on nightly.

https://github.com/libre-tube/LibreTube/assets/76256484/e97883c8-2ea6-476f-820b-7e54b1d1b94d

_I had to start the video manually after rotating_

Also, sometimes the video starts at another time stamp as before the rotate but I can't produce that reliably and I'm pretty sure that happens in combination with using the exit full screen gesture

**Comment by Bnyro** [comment] 2024-03-11 20:51
Hmm, that's likely an unwanted side effect of https://github.com/libre-tube/LibreTube/pull/5697, but not related to this issue really, so please create a new one.
