### ISSUE TITLE
Audio pauses while playing in background

### ISSUE THREAD

**Issue by W1zardK1ng** [libre-tube/LibreTube#5846] opened 2024-03-30 22:49 UTC
### Steps to reproduce

Play a video, minimize the app and continue playing. The audio will stop in less tan 30 seconds.

### Expected behavior

Audio continues to play in the background.

### Actual behavior

The audio stopped when the app is minimized in less than 30 seconds, even kept the battery to unrestricted still same issue. (the app gets closed completely when battery is set to optimized.)

### LibreTube version

0.22.2

### Android version

Android 14

### Other details

There is no issue if selected the audio option and then minimize the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-31 08:26
Duplicate of https://github.com/libre-tube/LibreTube/issues/5141

**Closed by Bnyro** 2024-03-31 08:26 UTC
Labels: bug
