### ISSUE TITLE
Player page fills only half of the screen after put to rest

### ISSUE THREAD

**Issue by MatsG23** [libre-tube/LibreTube#5350] opened 2023-12-18 19:03 UTC
### Steps to reproduce

1. Start playing any video
2. Put device to rest (unsure if you need to go the the home screen)
3. Come back later and open the mini player shown above the bottom nav bar 

### Expected behavior

There should be no issues.

### Actual behavior

The whole UI suddendly only fills ~a quarter of the phone's screen anymore.

### LibreTube version

0.20.1

### Android version

Android 14

### Other details

Only the regular player page is affected, not fullscreen mode or other parts of the app.
The phone is running GrapheneOS 2023121200.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-12-18 20:14
Please share a recording.

**Comment by IndusAryan** [comment] 2023-12-19 06:53
I think , this pushes app to deep sleep whiler running that causes some issue, try setting battery optimization of LT to unrestricted.

**Comment by M00NJ** [comment] 2024-01-21 21:36
@MatsG23 Did it look like the recording in #5401 ?

**Comment by M00NJ** [comment] 2024-01-31 19:47
I don't now how I got there, but this is how it looks I guess...

![Screenshot_20240131-162754.png](https://github.com/libre-tube/LibreTube/assets/82398591/2fa271a5-fb83-4d1a-94c3-fc8cd2cb4c2a)

**Comment by Bnyro** [comment] 2024-02-11 10:17
Closing in favor of #5401, the issue is the same.

**Closed by Bnyro** 2024-02-11 10:17 UTC
Labels: bug, can't reproduce
