### ISSUE TITLE
Libretube crashes

### ISSUE THREAD

**Issue by GET100PERCENT** [libre-tube/LibreTube#2621] opened 2023-01-07 03:19 UTC
### Steps to reproduce

java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.github.libretube.ui.adapters.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.kt:5)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:21317)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2186)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.widget.ScrollView.onMeasure(ScrollView.java:542)
	at android.view.View.measure(View.java:21317)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21317)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:916)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2644)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1697)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
    

### Expected behavior

It should not crash.

### Actual behavior

It crashes.

### LibreTube version

0.10.0

### Android version

Android 7.1 Nougat

### Other details

When I reopen libretube after the crash it shows the errors:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.github.libretube.ui.adapters.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.kt:5)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:21317)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2186)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.widget.ScrollView.onMeasure(ScrollView.java:542)
	at android.view.View.measure(View.java:21317)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21317)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6443)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:916)
	at android.view.View.measure(View.java:21317)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2644)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1697)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1952)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:640)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-07 08:38
Dupe of #2601

**Closed by Bnyro** 2023-01-07 08:38 UTC
Labels: bug
