### ISSUE TITLE
Video doesnt Play when on call

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3856] opened 2023-05-30 17:53 UTC
### Steps to reproduce

connect to someone or random customer care bot(to reproduce)
play any video
the video remains stopped

### Expected behavior

the video should play maybe with or without audio(depends on implementaion)
although original YT plays with Audio even on calls

### Actual behavior

the video keeps loading on the seekbar but doesnt Play even if we press Play button.

### LibreTube version

Latest Alpha(All)

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-30 18:20
duplicate of #2931

**Closed as completed by Bnyro** 2023-05-30 18:20 UTC
Labels: bug
