### ISSUE TITLE
Display more descriptive error messages to users when failing to register new accounts 

### ISSUE THREAD

**Issue by timkur** [libre-tube/LibreTube#2919] opened 2023-01-30 20:41 UTC
### Describe your suggested feature

Under Settings->Instance->Login/Register you have the option to create a new account (put in a username/password and hit "register").

However, if you put in a username already in use, or if the password doesn't meet the complexity requirements, the register fails with a toasted reporting a "HTTP 400" error.

It would be good to display what the actual error is registering the new account.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-30 21:37
Duplicate of #2056

**Closed by Bnyro** 2023-01-30 21:37 UTC
Labels: enhancement
