### ISSUE TITLE
Got Error: sign in to confirm that you're not a bot

### ISSUE THREAD

**Issue by OshekharO** [libre-tube/LibreTube#6470] opened 2024-09-08 09:37 UTC
### Steps to reproduce

![Screenshot_20240908-150423_LibreTube](https://github.com/user-attachments/assets/a4748418-53f3-45e0-bfeb-4f5c73d7ef99)

### Expected behavior

Should have played the video

### Actual behavior

Error

### LibreTube version

0.25.2

### Android version

Android 14

### Other details

Have already logged in to my pipped account. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-09-08 09:38
Duplicate of https://github.com/libre-tube/LibreTube/issues/6389

**Closed by Bnyro** 2024-09-08 09:38 UTC
Labels: bug
