### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#1494] opened 2022-10-04 18:30 UTC
### Describe your suggested feature

Libretube don't sort playlist in library in any common style. It's just random every time.

Should have option to sort by A-Z / Z-A or at least one of them by default. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2022-10-04 21:12
Dude, it's called "Sorting". Misleading title

**Comment by akano12** [comment] 2022-10-04 21:13
You mean "Sorting"

**Comment by rozari0** [comment] 2022-10-05 02:05
> You mean "Sorting"

Fixed. :)

**Comment by Bnyro** [comment] 2022-10-05 07:39
Dupe of #1466

**Closed by Bnyro** 2022-10-05 07:39 UTC
Labels: enhancement
