### ISSUE TITLE
Opening video links should open the whole video, not the mini-player

### ISSUE THREAD

**Issue by RobbyCBennett** [libre-tube/LibreTube#3461] opened 2023-03-31 13:11 UTC
### Describe your suggested feature

How it works currently:
1. Open link to video from outside the app or inside the app
2. The video shows up on the mini-player, which is slightly difficult to click on because of the size, with the majority of the screen dedicated to suggestions that are irrelevant to the link
3. Click on the mini-player to open the video
4. Actually watch the intended video

How I think that it should work:
1. Open link to video from outside the app or inside the app
2. Actually watch the intended video

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RobbyCBennett** [comment] 2023-03-31 13:12
Thank you for making this app. It's the best one that I've tried, and the attention to detail to most of the UX is great.

**Comment by Bnyro** [comment] 2023-04-01 05:59
Duplicate of #3260

**Closed by Bnyro** 2023-04-01 05:59 UTC
Labels: enhancement
