### ISSUE TITLE
Mini player covers bottom tab buttons

### ISSUE THREAD

**Issue by oathzed** [libre-tube/LibreTube#4153] opened 2023-07-03 16:45 UTC
### Steps to reproduce

1. Open any video
2. Minimize it
3. You can't access any of the buttons it's covering

### Expected behavior

Should be able to access the bottom buttons, the player should go above them.

### Actual behavior

You can't access the buttons, the player goes on top of them.
![Screenshot_20230703-094514](https://github.com/libre-tube/LibreTube/assets/52545913/f60f9aef-4d7a-4665-b53c-a9a3993d97a4)

### LibreTube version

0.15.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-03 16:47
duplicate of https://github.com/libre-tube/LibreTube/issues/3861

**Closed by Bnyro** 2023-07-03 16:47 UTC
Labels: bug
