### ISSUE TITLE
Button behaviour and repeat option in notification bar and repeat option for playing as audio.

### ISSUE THREAD

**Issue by muhammadabdullah007git** [libre-tube/LibreTube#2418] opened 2022-12-17 11:26 UTC
### Describe your suggested feature

It would be great if you below add options :-
1. Button behaviour :- Can you add option to go as audio mood if i press home button/recent button instead of popup.
2. Repeat option in notification bar :- Can you add option to change repeat moods from notification bar.
3. Audio repeat :- Can you add repeat mood for audio.

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-17 12:54
Please only one feature request per issue.

1. That's not really a good idea, manually entering the audio mode before quitting should be the go-to.
2. That's a duplicate of some other issue.
3. That should probably be achieved with 2.

**Closed by Bnyro** 2022-12-17 12:54 UTC
Labels: enhancement
