### ISSUE TITLE
Can't play videos.

### ISSUE THREAD

**Issue by Lence23** [libre-tube/LibreTube#5851] opened 2024-04-02 04:35 UTC
### Steps to reproduce

1. Opening app
2. video thums load accurately
3. but, while clicking video link (thumbs) player opened but play nothing.

### Expected behavior

Normally while we click the video thumbs or link video plays on the next screen.  Here the issue is player opening and play nothing.

### Actual behavior

While clicking video thumbs or link player showing buffering sign or showing play sign (click on the sign do nothing). 

### LibreTube version

v0.22.2

### Android version

android 13, One UI 5.1

### Other details

Sometimes videos may play while I change the instance (piped).  After sometimes the issues starts again (play no videos and sound).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by creativetrendsapps** [comment] 2024-04-02 05:29
Same!

**Comment by dreammirror000** [comment] 2024-04-02 06:25
Same

**Comment by mfathurr** [comment] 2024-04-02 07:19
> Guys, go to, Setting - Audio and Video - Quality and enable both "Use HLS" and "LBRY HLS". You're welcome.
> 
> The issue can also be fixed by disabling piped proxy at the bottom of , Settings - Instances, But i don't recommend that as it defeats the purpose of using LibreTube.

Thank you @MykeHalk.
I've tried deleting the app's cache and still can't play the video, but after following your suggestion to activate "HLS" and "LBRY HLS" together now everything is back to normal.

If I may know, what are the functions of these two settings?

**Comment by dreammirror000** [comment] 2024-04-02 07:56
> Guys, go to, Setting - Audio and Video - Quality and enable both "Use HLS" and "LBRY HLS". You're welcome.
> 
> The issue can also be fixed by disabling piped proxy at the bottom of , Settings - Instances, But i don't recommend that as it defeats the purpose of using LibreTube.

Thank you!!!

**Comment by Bnyro** [comment] 2024-04-02 08:55
Duplicate of https://github.com/libre-tube/LibreTube/issues/5614

**Closed by Bnyro** 2024-04-02 08:55 UTC
Labels: bug
