### ISSUE TITLE
Strange behaviour when switching back to video mode from audio mode.

### ISSUE THREAD

**Issue by faisalcodes** [libre-tube/LibreTube#2946] opened 2023-02-02 16:46 UTC
### Steps to reproduce

1. Play a video
2. Switch to Audio-mode
3. Switch back to Video-mode
4. The issue

### Expected behavior

The video should continue playing.

### Actual behavior

The following happen:
1. The video ends
2. All the next videos on autoplay end without even starting.

### LibreTube version

LibreTube Debug

### Android version

12

### Other details

https://user-images.githubusercontent.com/62804272/216392765-cdf92641-3e99-4d77-aa7e-db72336b0399.mov

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment] 2023-02-02 21:39
Duplicate of #2800, but, if possible, can you upload this video there?

**Comment by faisalcodes** [comment] 2023-02-03 03:39
I can't edit that. I am closing it.

**Closed** 2023-02-03 03:39 UTC
Labels: bug
