### ISSUE TITLE
Text sizes acting weird after using PiP mode

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#3057] opened 2023-02-13 16:17 UTC
### Steps to reproduce

1. Go play a video
2. Go PiP mode
3. Go back to normal view
4. Experience the issue

### Expected behavior

The fonts should change sizes.

### Actual behavior

They do change.

### LibreTube version

0.12.0

### Android version

Android 13

### Other details

OnePlus 8
![Screenshot_2023-02-13-16-58-02-47_54f92cd6866f5233ab0db4392b806878](https://user-images.githubusercontent.com/76624594/218512300-5bf646d3-145f-4ddf-be17-7f9068b56a6c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by faisalcodes** [comment] 2023-02-13 16:29
The text size after switching back to normal mode looks better though ;)

**Comment by Bnyro** [comment] 2023-02-13 17:11
Duplicate of #2275

**Closed by Bnyro** 2023-02-13 17:11 UTC
Labels: bug

**Comment by d4f5409d** [comment] 2023-02-13 18:46
> The text size after switching back to normal mode looks better though ;)

Indeed
