### ISSUE TITLE
Crashes when trying to change a certain video's quality

### ISSUE THREAD

**Issue by shell-raiser** [libre-tube/LibreTube#2016] opened 2022-11-23 23:11 UTC
### Steps to reproduce

1. Open this video https://piped.video/watch?v=lkIFF4maKMU (https://www.youtube.com/watch?v=lkIFF4maKMU)
2. Click on quality in the pop up

### Expected behavior

Display available video quality options in another pop up

### Actual behavior

Crashes and gives this when restarted
```
java.lang.NumberFormatException: For input string: "LBRY"
	at java.lang.Integer.parseInt(Integer.java:747)
	at java.lang.Integer.parseInt(Integer.java:865)
	at com.github.libretube.ui.fragments.PlayerFragment.qualityToInt(PlayerFragment.kt:21)
	at com.github.libretube.ui.fragments.PlayerFragment.onQualityClicked(PlayerFragment.kt:142)
	at com.github.libretube.ui.views.CustomExoPlayerView$initializeAdvancedOptions$1$2.invoke(CustomExoPlayerView.kt:7)
	at com.github.libretube.ui.adapters.BottomSheetAdapter$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:21)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    
```

### LibreTube version

0.8.0

### Android version

12

### Other details

Other videos work perfectly, this is the only one I've seen so far

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment] 2022-11-24 07:48
I can reproduce the same :)

**Comment by Bnyro** [comment] 2022-11-24 12:06
Dupe of 5 other issues, already fixed

**Closed by Bnyro** 2022-11-24 12:07 UTC
Labels: bug
