### ISSUE TITLE
Show related videos of your recently watched videos on home screen as a substitute for a recommendation algorithm

### ISSUE THREAD

**Issue by ignamiranda** [libre-tube/LibreTube#4329] opened 2023-07-30 06:03 UTC
### Describe your suggested feature

One of the things that keeps me returning to regular YouTube is that their personalized content recommendation is my main way of discovering content.

This feature would take the videos that are recommended when you scroll down on a video and put them on the home screen. It could draw from your last 5 videos or a configurable amount.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-30 06:45
Duplicate of #2612

**Closed by Bnyro** 2023-07-30 06:45 UTC
Labels: enhancement
