### ISSUE TITLE
App crashing in "Subscriptions" tab

### ISSUE THREAD

**Issue by freak-from-the-computer-club** [libre-tube/LibreTube#1058] opened 2022-08-14 08:07 UTC
### Steps to reproduce

When I log in to my account or import subscriptions from a file, after that I go to the "subscriptions" tab, the application crashes and issues an output:

### Expected behavior

Maybe I'm doing something wrong? Help solve this problem because I love LibreTube so much. P.S I tried different instances in settings

### Actual behavior

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.get(ArrayList.java:437)
	at d4.w0.f(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView$t.j(SourceFile:91)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(SourceFile:3)
	at androidx.recyclerview.widget.GridLayoutManager.e1(Unknown Source:95)
	at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
	at androidx.recyclerview.widget.LinearLayoutManager.i0(SourceFile:19)
	at androidx.recyclerview.widget.GridLayoutManager.i0(SourceFile:7)
	at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:63)
	at android.view.View.measure(View.java:25833)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25833)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1441)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:458)
	at android.view.View.measure(View.java:25833)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(Unknown Source:53)
	at android.view.View.measure(View.java:25833)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25833)
	at androidx.constraintlayout.widget.ConstraintLayout$b.b(SourceFile:23)
	at u.f.i0(SourceFile:11)
	at v.j.g(SourceFile:2)
	at v.j.f(SourceFile:6)
	at v.j.g(SourceFile:16)
	at v.j.g(SourceFile:30)
	at u.f.Y(SourceFile:34)
	at v.b.b(SourceFile:5)
	at androidx.constraintlayout.widget.ConstraintLayout.q(SourceFile:55)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(SourceFile:12)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(SourceFile:2)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6979)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:758)
	at android.view.View.measure(View.java:25833)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2458)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2737)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2177)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8803)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    

### LibreTube version

O.4.2

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by freak-from-the-computer-club** [comment] 2022-08-14 08:08
App crashing in Subscriptions tab

**Comment by Bnyro** [comment] 2022-08-14 08:46
dupe of #1006, look there for temporary fix

**Closed by Bnyro** 2022-08-14 08:46 UTC
Labels: bug
