### ISSUE TITLE
Some videos don't work

### ISSUE THREAD

**Issue by Ismail970** [libre-tube/LibreTube#3230] opened 2023-03-03 19:59 UTC
### Steps to reproduce

https://user-images.githubusercontent.com/114358862/222814370-ff1647b2-85f5-4f0e-bd1a-4035a2835074.mp4

### Expected behavior

Video should work fine

### Actual behavior

Video stops

### LibreTube version

0.12.0

### Android version

Android 9.1

### Other details

For some reason this happens with some videos

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-03 20:05
Duplicate of #3051

**Closed by Bnyro** 2023-03-03 20:05 UTC
Labels: bug
