### ISSUE TITLE
Bug : Captions don't wotk

### ISSUE THREAD

**Issue by anidevrev** [libre-tube/LibreTube#1852] opened 2022-11-15 10:18 UTC
The captions stop working when video quality is set to any quality other than 'auto' from settings > audio and video > video resolution.

The captions work just fine when quality is set to 'auto' in the settings.

**Comment by Bnyro** [comment] 2022-11-15 10:33
Dupe of #1573

**Closed by Bnyro** 2022-11-15 10:33 UTC
