### ISSUE TITLE
[FEATURE] Landscape mode support

### ISSUE THREAD

**Issue by ygz213** [libre-tube/LibreTube#136] opened 2022-04-19 13:22 UTC
**Describe the feature you'd like to see added**

Interface for tablets, it is hard to use on them.

**Additional context**

![](https://user-images.githubusercontent.com/77006222/164013577-c81e7a49-f850-46d1-b52b-e38a6a46e176.jpeg)

**Comment by Bnyro** [comment] 2022-05-18 08:50
Dupe of #24

**Closed by Bnyro** 2022-05-18 08:50 UTC
Labels: enhancement
