### ISSUE TITLE
Channel lost labels in version 0.7.1

### ISSUE THREAD

**Issue by dpk4g** [libre-tube/LibreTube#1853] opened 2022-11-15 10:26 UTC
### Steps to reproduce

Thank the team for hard work the first of all .
I updated to version 0.7.1 yesterday from 0.7.0 and found some channel's labels missing,and it's made impossible to find the author's latest upload of the full video.
It is normal in 0.7.0.

![Screenshot_2022-11-15-17-39-35-051_com github libretube](https://user-images.githubusercontent.com/52632965/201895427-7a7021ca-449c-4905-afb6-a03667916fd1.jpg)
![Screenshot_2022-11-15-17-47-25-564_com github libretube](https://user-images.githubusercontent.com/52632965/201895475-e0a90c53-7b66-4fb2-9dd3-a349c034c2f3.jpg)

### Expected behavior

can be fixed

### Actual behavior

something went wrong

### LibreTube version

0.7.1

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-15 10:33
Dupe of #1830

**Closed by Bnyro** 2022-11-15 10:33 UTC
Labels: bug
