### ISSUE TITLE
New stream notifications.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#856] opened 2022-07-22 15:02 UTC
### Describe your suggested feature

Send a notification when a new video is released.(Subscriptions)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-07-22 15:04
dupe of #346

**Closed by Bnyro** 2022-07-22 15:04 UTC
Labels: enhancement
