### ISSUE TITLE
Sponsorblock broken after updating debug build 

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4221] opened 2023-07-12 23:14 UTC
### Steps to reproduce

starting from previous build, update to latest debug (where there was something changed regarding sponsorblock settings in small screens).
then if you try to enter sponsorblock settings it crashes and kicks you to app home screen.

### Expected behavior

open sponsorblock settings 

### Actual behavior

crash report:
`java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:321)
	at androidx.preference.Preference.getPersistedInt(Preference.java:1813)
	at com.github.libretube.ui.views.ColorPreference.onSetInitialValue(ColorPreference.kt:49)
	at androidx.preference.Preference.onSetInitialValue(Preference.java:1634)
	at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1607)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1330)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1345)
	at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:253)
	at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:173)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:350)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217)
	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380)
	at com.github.libretube.ui.preferences.SponsorBlockSettings.onCreatePreferences(SponsorBlockSettings.kt:11)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at com.github.libretube.ui.preferences.MainSettings.navigateToSettingsFragment(MainSettings.kt:138)
	at com.github.libretube.ui.preferences.MainSettings.onCreatePreferences$lambda$3(MainSettings.kt:43)
	at com.github.libretube.ui.preferences.MainSettings.$r8$lambda$38yMrwsTZfZXiuB6Yq-FCiX22KM(Unknown Source:0)
	at com.github.libretube.ui.preferences.MainSettings$$ExternalSyntheticLambda5.onPreferenceClick(Unknown Source:2)
	at androidx.preference.Preference.performClick(Preference.java:1200)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference$1.onClick(Preference.java:182)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29487)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7930)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
    `

### LibreTube version

0.16.0  versionCode 1689085543 

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-13 05:46
Duplicate of #4196

**Closed by Bnyro** 2023-07-13 05:46 UTC
Labels: bug

**Comment by luckkmaxx** [comment] 2023-07-13 07:17
Doesnt seem fixed, Im running the last build, from July 11, after the related commit.

**Comment by Bnyro** [comment] 2023-07-13 07:25
Clear the app data and restore your backup again.
