### ISSUE TITLE
Keep display awake mode does not turn off when pausing the video

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2905] opened 2023-01-29 20:03 UTC
### Steps to reproduce

1. Play a video
2. Pause it
3. Wait and see

### Expected behavior

The screen should turn off like usual when it is jot playing anything.

### Actual behavior

It does not turn off.

### LibreTube version

0.11.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by praveenrajput** [comment] 2023-01-29 20:30
Duplicate of #2877, Already fixed in #2886

**Closed** 2023-01-29 20:43 UTC
Labels: bug
