### ISSUE TITLE
Audio Player Overlapping Entire Tabs

### ISSUE THREAD

**Issue by akano12** [libre-tube/LibreTube#4711] opened 2023-09-07 21:26 UTC
### Steps to reproduce

1. Play a video
2. Go to audio mode
3. Minimize the player
4. Maximize the player 

### Expected behavior

Audio playee should be minimized and maximized without problems 

### Actual behavior

1. Audio player can't be dismissed.
2. The minimize and autoplay buttons disappear 

### LibreTube version

Latest Debug 

### Android version

Android 13

### Other details

https://github.com/libre-tube/LibreTube/assets/50032603/ce636a3c-bc6e-4fb8-be55-caf1edb3ea61

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-09-08 06:06
Duplicate of #4114

**Closed by Bnyro** 2023-09-08 06:06 UTC
Labels: bug

**Comment by akano12** [comment] 2023-09-08 09:00
He had a misleading title 😅
