### ISSUE TITLE
Showing ping next to instance on instance list.

### ISSUE THREAD

**Issue by SimplyVoid** [libre-tube/LibreTube#3228] opened 2023-03-03 16:44 UTC
### Describe your suggested feature

I generally use libretube for online classes and used to use it `kevin.rocks` as my primary instance, but it seems like it's sometime going down so I've to change instance kinda regularly nowadays.

it'd be helpful if i knew which server has the best ping available at current time so i can switch to that instance as video generally buffers with other instances.

or maybe add a option to sort the list with ping..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-03 16:55
duplicate of #3152

**Comment by Bnyro** [comment] 2023-03-03 16:56
You can use https://github.com/TeamPiped/piped-uptime

**Closed by Bnyro** 2023-03-03 16:55 UTC
Labels: enhancement

**Comment by SimplyVoid** [comment] 2023-03-03 17:00
> You can use [TeamPiped/piped-uptime](https://github.com/TeamPiped/piped-uptime)

i was looking for ping from my network as it may varies from network to network as i know.. but it maybe kinda works maybe
