### ISSUE TITLE
Progressbar location

### ISSUE THREAD

**Issue by xIUPITERx** [libre-tube/LibreTube#1632] opened 2022-10-21 23:09 UTC
### Steps to reproduce

Since 0.6.0 it happend a few times

### Expected behavior

Progressbar location shouldn't change.

### Actual behavior

https://user-images.githubusercontent.com/97352673/197303290-91f4a8fe-95b5-4420-be8c-ceaee668b188.mp4

### LibreTube version

0.6.1

### Android version

Android 12 One UI 4.1

### Other details

The progressbar is theoreticaly still useable, but the player has to be closed an the video has to be reopened to restore the progressbar location.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-10-21 23:24
I don't know if it's related, but sometimes there are no buttons at all, you have to minimize and maximize the player to get it back.

**Comment by Bnyro** [comment] 2022-10-22 06:23
Dupe of #1561 :)

**Closed by Bnyro** 2022-10-22 06:23 UTC
Labels: bug
