### ISSUE TITLE
Background play stopping after 10 seconds to 10 minutes

### ISSUE THREAD

**Issue by Arctic-Circle-System** [libre-tube/LibreTube#5055] opened 2023-10-29 12:08 UTC
### Steps to reproduce

1. Open video
2. Turn off screen
3. After some time ranging from about 10 seconds to a few minutes, it will stop playing, requiring you to start playing it again in the app.

### Expected behavior

It should continue playing until I tell it to stop.

### Actual behavior

It stopped playing within 10 seconds to 10 minutes.

### LibreTube version

0.19.0 (armeabi-v7a)

### Android version

Android 11

### Other details

Audio-only mode just doesn't play anything for some reason, even when the app is open. Possibly another bug. This also happens with Adaptive Battery settings turned off. LibreTube does not show up in the Battery Optimization menu.
Furthermore, despite my device (Motorola G Pure) being a 64-bit ARM device, the arm64-v8a APK will not install. Possibly another bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by hyperstown** [comment] 2023-10-29 13:15
> Audio-only mode just doesn't play anything for some reason

I had the same issue. Switching to HLS worked but ultimately I purged all app data including cache and it started working on DASH too. 

As for background play issue it happens to me too. But funny enough only on stock Samsung phone. On Xperia XZ3 with Linage OS it works fine. Both running Android 13.

**Comment by Arctic-Circle-System** [comment] 2023-10-30 23:46
@IndusAryan Well on my device, LibreTube doesn't show up in the battery optimization settings menu and turning off the Adaptive Battery settings doesn't help much so I don't know what's going on.

**Comment by Hujair** [comment] 2023-11-02 02:10
reporting the same bug, the player stops after 5 seconds and resumes once I open the app.

**Comment by Bnyro** [comment] 2023-11-02 12:56
Duplicate of #3589.

See https://github.com/libre-tube/LibreTube/issues/3589#issuecomment-1524927117.

If the background mode doesn't work for you at all, please open a different issue for that.

**Closed by Bnyro** 2023-11-02 12:56 UTC
Labels: bug
