### ISSUE TITLE
Videos are not playing

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#4492] opened 2023-08-15 15:36 UTC
### Steps to reproduce

1. Open the app.
2. Click on any video.
3. Try to play it.

### Videos don't start and you get stuck with the resume button and a black screen.
![videos_not_playing](https://github.com/libre-tube/LibreTube/assets/105887123/34bd60a0-d32d-4cc3-9008-b33c3aab4743)

### LibreTube version

0.17.1 and previous versions as well

### Android version

Android 10

### Other details

Reading the issues on Piped repository, it seems like there's a problem with their API, but I'm opening this issue here too just in case. Changing instances doesn't seem to work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-15 15:40
Duplicate of #4479

**Closed as completed by Bnyro** 2023-08-15 15:40 UTC
Labels: bug
