### ISSUE TITLE
[BUG] Fullscreen Horizontal not working

### ISSUE THREAD

**Issue by ManuLinares** [libre-tube/LibreTube#76] opened 2022-03-17 03:14 UTC
fullscreen horizontal not working

**To Reproduce**
How to reproduce:

    Play any video and click to go fullscreen (it fills the screen in vertical mode)
    Rotate device to horizontal.
    Player stops, and minimizes to the bottom. (No fullscreen playback)

I'm using latest CI build.

**Smartphone (please complete the following information):**
 - Device: Samsung S8 (dreamlte)
 - Android version: 12, Lineage 19.1

Related closed bugs
https://github.com/libre-tube/LibreTube/issues/28
https://github.com/libre-tube/LibreTube/issues/20

**Comment by lilcheti** [comment] 2022-03-17 05:07
I can't reproduce this my self.

**Comment by ManuLinares** [comment] 2022-03-17 18:10
> I can't reproduce this my self.

Are you in Android 12?

Post your device info

**Comment by lilcheti** [comment] 2022-03-18 16:58
Yes I'm using android 12 and still can't reproduce could it be because of lineageos?

**Comment by ManuLinares** [comment] 2022-03-18 22:45
Must be, a lineage 19.1 issue I mean. Can't reproduce in the Android emulator, on API32 sdk.

**Comment by krypciak** [comment] 2022-05-15 14:20
This bug also appears for me, but only if the Device Settings -> Display -> Display Size is set to "Smaller"
Other display configurations work just fine.
Too bad that display size is a perfect match for me :(

**Comment by krypciak** [comment] 2022-05-15 15:09
Built the app from source, the bug doesn't occur anymore. Close the issue perhaps?

**Closed** 2022-05-15 15:24 UTC
Labels: bug
