### ISSUE TITLE
Option to hide shorts

### ISSUE THREAD

**Issue by rohandebsarkar** [libre-tube/LibreTube#2141] opened 2022-11-29 02:54 UTC
### Describe your suggested feature

An option in the settings to turn off or hide shorts, especially in the subscriptions view.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-29 10:34
Dupe of #1354

**Closed** 2022-11-29 10:34 UTC
Labels: enhancement
