### ISSUE TITLE
1080p often stucks

### ISSUE THREAD

**Issue by ydqsbfsyi** [libre-tube/LibreTube#602] opened 2022-06-24 05:14 UTC
### Steps to reproduce

null

### Expected behavior

null

### Actual behavior

HLS sure is the fastest one, but it often gets me low resolution. So I changed the settings to 1080p+WEBM.
With 1080p, I found the video often stucks (turning circle), usually once or twice for a video, it will keep stuck, unless if I fast forward 5s or back 5s, it'll run fine immediately. So I guess it's not a network problem on my end.

Any idea?

### LibreTube version

0.3.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by archroid** [comment] 2022-06-24 09:35
Are you sure it's not related to your network speed and the instance you choose? Check out the [Instances list ](https://github.com/TeamPiped/Piped/wiki/Instances)and choose the one near you from settings and try again.

**Comment by FireMasterK** [comment] 2022-06-24 10:09
I think that this is because we use a MergingMediaSource in Exoplayer and not DASH.

YouTube rate-limits/throttles steam bandwidth after a few seconds, so we can use DASH which uses range requests and can bypass it.

**Comment by ydqsbfsyi** [comment] 2022-06-24 10:11
> Are you sure it's not related to your network speed and the instance you choose? Check out the [Instances list ](https://github.com/TeamPiped/Piped/wiki/Instances)and choose the one near you from settings and try again.

Thanks a lot, I never know there's regions ..... I'll try.

**Comment by ydqsbfsyi** [comment] 2022-06-24 10:18
> I think that this is because we use a MergingMediaSource in Exoplayer and not DASH.
> 
> YouTube rate-limits/throttles steam bandwidth after a few seconds, so we can use DASH which uses range requests and can bypass it.

Thanks for the info.

**Comment by Bnyro** [comment] 2022-06-24 11:14
Dupe of #231

**Closed by Bnyro** 2022-06-24 11:14 UTC
Labels: bug
