### ISSUE TITLE
Don't close comments when scrolling the player

### ISSUE THREAD

**Issue by Fish25op** [libre-tube/LibreTube#4050] opened 2023-06-19 14:20 UTC
### Steps to reproduce

1.Open the comments.
2.Scroll down the player
3.Comments close, but come back if you don't take your hand off the screen
4.After sliding into the mini player, it closes completely

### Expected behavior

Don't close comments and keep them open when you return to the main player

### Actual behavior

https://github.com/libre-tube/LibreTube/assets/136016095/42172fea-9b9a-467b-a0be-6963f3ce5382

### LibreTube version

0.15.1 Debug

### Android version

Android 12

### Other details

Tested on multiple devices

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-31 13:19
This is the intended behavior. I thought about changing it, but in my opinion it only makes sense that closing/minimizing the main player also closes the comments sheet.

**Closed by Bnyro** 2023-07-31 13:19 UTC
Labels: enhancement
