### ISSUE TITLE
Extremely low download speed 

### ISSUE THREAD

**Issue by Gul7333** [libre-tube/LibreTube#871] opened 2022-07-25 14:25 UTC
### Steps to reproduce

Download any video in any format

### Expected behavior

This app doesn't download video through new pipe API or new pipe...but instead video is downloaded through mobile download manager which is extremely slow...but I tried downloading through new pipe app...it's speed is very good and also it doesn't need help from phone download manager but it download video in itself....

### Actual behavior

But your app download video outside of your app ...and doesn't have any thread 

### LibreTube version

Latest

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-07-25 14:36
dupe of #456

**Closed by Bnyro** 2022-07-25 14:36 UTC
Labels: bug
