### ISSUE TITLE
Wide Screen

### ISSUE THREAD

**Issue by Jomyy** [libre-tube/LibreTube#250] opened 2022-05-19 05:08 UTC
### Steps to reproduce

use on a wide screen device

### Expected behavior

app should automatically go wide and select multiple grid items per row 

### Actual behavior

app just doesn't go wide it stays in a kind of phone mode 

### LibreTube version

built myself with newest source code

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-05-19 05:12
Yeah, landscape mode doesn't work yet, we're busy with other things.

**Comment by Bnyro** [comment] 2022-05-19 07:38
and its a dupe of #24

**Closed by Bnyro** 2022-05-19 07:38 UTC
Labels: duplicate, enhancement
