### ISSUE TITLE
player freezes

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1115] opened 2022-08-21 20:42 UTC
### Steps to reproduce

usually when rewinding (or at a random load time) the player freezes for a few seconds.  android message appears that app is not responding

### Expected behavior

?

### Actual behavior

![Screenshot_2022-08-21-23-37-16-142_com github libretube](https://user-images.githubusercontent.com/52075465/185810057-c981afc0-7dea-421a-b282-b51e72400727.jpg)

### LibreTube version

0.5.0

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-08-23 07:16
Can't reproduce, debug logs?

**Comment by Envel-Nikita-Gutsenkov** [comment] 2022-08-23 08:02
> Can't reproduce, debug logs?

where is it?

**Comment by Bnyro** [comment] 2022-08-23 12:01
Shows when you open the app after it crashed

**Comment by Envel-Nikita-Gutsenkov** [comment] 2022-08-23 17:36
> Shows when you open the app after it crashed

The thing is, the app doesn't crash.  it freezes and a notification pops up, after which it continues to work.  in general, this occurs so often that it is impossible to use

**Comment by Bnyro** [comment] 2022-08-23 17:41
Well, I use the app often enough on Android 12 too and don't have any issues like that. No idea what the reason could be...

**Comment by Envel-Nikita-Gutsenkov** [comment] 2022-08-23 20:21
> 

miui 13 global
android 12 
xiaomi 11 lite 5g ne

well, android thinks the app has stopped responding.  and it is the player that freezes, everything is fine with the interface itself

**Comment by Bnyro** [comment] 2022-09-09 16:22
dupe of #870

**Closed by Bnyro** 2022-09-09 16:22 UTC
Labels: bug
