### ISSUE TITLE
Blank fragments after leaving audio player fragment

### ISSUE THREAD

**Issue by anujithpp** [libre-tube/LibreTube#2818] opened 2023-01-22 03:30 UTC
### Steps to reproduce

When a song is played using new audio only mode after going home home page and other page's are just blank

### Expected behavior

Audio plays in background and other features work just like it is

### Actual behavior

Instead of showing pages and videos nothing loads 

### LibreTube version

0.11.0

### Android version

11

### Other details

![Screenshot_2023-01-22-08-54-52-98_54f92cd6866f5233ab0db4392b806878](https://user-images.githubusercontent.com/106502495/213899216-460380ec-6cdd-4dc2-b715-2c6fb16552e8.jpg)
![Screenshot_2023-01-22-08-54-49-98_54f92cd6866f5233ab0db4392b806878](https://user-images.githubusercontent.com/106502495/213899218-41b1d33e-966b-419d-a2a3-bddf16fa0049.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment] 2023-01-22 03:50
Looks like a duplicate of #2791

**Comment by xIUPITERx** [comment] 2023-01-22 12:00
>  Looks like a duplicate of #2791

They seem related, but I think they were different in their manifestation.

**Comment by anujithpp** [comment] 2023-01-22 12:20
> >  Looks like a duplicate of #2791
> 
> They seem related, but I think they were different in their manifestation.

#2791 and the problem i reported is almost the same but the bug happens another way let me show you

**Comment by anujithpp** [comment] 2023-01-22 12:24
https://user-images.githubusercontent.com/106502495/213915624-b04d93ab-00e9-4706-9a34-704c96169269.mp4

**Comment by Archeix7** [comment] 2023-01-25 04:49
After leaving the audio mode, the page page freezes, after touching down and opening again - the video has come to an end

https://user-images.githubusercontent.com/51048550/214482121-a21a8324-94d6-4396-8ec2-811ab4d896ab.mp4

**Comment by Bnyro** [comment] 2023-03-22 07:22
This should have been with #3335 too. If it still persists please file a new issue after the next release.

**Closed by Bnyro** 2023-03-22 07:22 UTC
Labels: bug
