### ISSUE TITLE
App crashes on opening

### ISSUE THREAD

**Issue by pklion** [libre-tube/LibreTube#1584] opened 2022-10-18 08:23 UTC
### Steps to reproduce

1. Just open the app

### Expected behavior

This just shuold not happen, I think. 

### Actual behavior

App crashes without saying anything. 

### LibreTube version

0.6.1

### Android version

Android 9(armv7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-10-18 08:24
Dupe of #1551

**Closed by Bnyro** 2022-10-18 08:24 UTC
Labels: bug
