### ISSUE TITLE
Video not showing in full screen

### ISSUE THREAD

**Issue by adu-lab** [libre-tube/LibreTube#3709] opened 2023-05-04 18:33 UTC
### Steps to reproduce

Open anything in smartphone that contains proper URL on YouTube video. Click on this link. Choose to view it by LibreTube and notice that player is not in a full screen mode as i set in Settings of this app - but in a smaaaal microwindow right above the navigation panel: Pulled right to its top border.

### Expected behavior

Player window should be opened in a full screen mode as i set it in main Settings 

### Actual behavior

Player is opening in a smaaaal micro-window.

### LibreTube version

0.14.1 debug

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-05 06:25
Duplicate of #3260.

**Closed by Bnyro** 2023-05-05 06:25 UTC
Labels: bug
