### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [libre-tube/LibreTube#1736] opened 2022-11-03 11:12 UTC
### Steps to reproduce

The application cycling crashing after the update (this is the second such update), it is solved by erasing all data. this is probably related to the bar items (after all, everyone disables an unnecessary section "home" is it true?)

### Expected behavior

?

### Actual behavior

Crash

### LibreTube version

0.7.0

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-03 11:47
Dupe of #1698

**Closed by Bnyro** 2022-11-03 11:47 UTC
Labels: bug
