### ISSUE TITLE
[regression][CRASH] fatal upgrades

### ISSUE THREAD

**Issue by ildar** [libre-tube/LibreTube#1717] opened 2022-10-31 18:45 UTC
### Steps to reproduce

upgrade

### Expected behavior

app works

### Actual behavior

app CRASH
it's amazing that the second upgrade in a raw (0.6.0 → 0.6.1 → 0.7.0) makes the app crash.
🤦🏻‍♂

### LibreTube version

0.7.0

### Android version

Android 12 GSI Phh LA

### Other details

ref: https://github.com/libre-tube/LibreTube/issues/1551

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-10-31 19:13
Nobody has been reporting such bugs via GitHub or privately before any update in any debug builds. I'm not almighty and able to spot all those potential issues before releasing a new update, that's why I appreciate anyone who tests debug builds before releases. I can't afford spending much time testing as it's more important for me to work on new features than testing the resistance of already existing ones. 

As you might imagine I'm not a full-time FOSS developer, I also got a life and other things to do! Anyone contributing here does it in their free time, just to make others like you happy with new features that the developer often would never even consider to use.

I understand that this might have caused inconvenience, but that's still not a reason to offend me like that.
Apart from that you should have taken a look at #1698 and #1706 before opening a new issue, you ticked the checkbox that you browsed the existing issues, which you obviously didn't!

I recommend you to breath in and [exhale](https://piped.kavin.rocks/watch?v=6u6jDIf35Oo) slowly to calm down.


Closing as a duplicate of #1698

**Closed** 2022-10-31 19:14 UTC
Labels: bug

**Comment by ildar** [comment] 2022-10-31 20:35
@Bnyro , I am sorry to upset you. I never wanted to do that.
I searched the `upgrade` word and found nothing relevant.
Anyway, as the testing is so important, I suggest making a big note about
that. I fairly didn't know it's so (though I could probably guess, sorry
again).
I'm willing to test it further through the debug builds. Just let me (or
everyone) know what info channel to follow so that I/we know a few days
before release. is it https://github.com/libre-tube/LibreTube/discussions ?
Thanks.

**Comment by Rtype-SPC** [comment] 2022-10-31 22:47
Same problem for me.

Thanks.

**Comment by Bnyro** [comment] 2022-11-01 12:36
Debug builds in general are located under the [repo actions](https://github.com/libre-tube/LibreTube/actions) labeled with `CI`.

Announcing updates always days earlier is not possible as for example there are sometimes breaking changes in the API that require a fast update to follow, so I'd prefer if debug builds just could be tested in general without a specific focus on whether they're related to an update or not!

I agree, it might make sense to open a discussion about it and pin it but I feel like nobody really notices discussions, opening and pinning an issue might be the better approach to get more people involved.
