### ISSUE TITLE
About the download management crash

### ISSUE THREAD

**Issue by zmyznu** [libre-tube/LibreTube#3824] opened 2023-05-24 11:43 UTC
### Steps to reproduce

版本：0.14.1java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:587)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/大清官 第32集【歡迎訂閱】高明、傅彪、周野芒、劉奕君等主演。該劇講述了四個男人皇帝乾隆、忠臣劉統勛、偽善寵臣納善以及滑頭福康之間的鬥智鬥法的故事。_126_kbps_M4A.mp4
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
	at j$.nio.file.spi.a.x(Unknown Source:14)
	at j$.nio.file.Files.readAttributes(SourceFile:0)
	at j$.nio.file.Files.size(Unknown Source:5)
	at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(DownloadsAdapter.kt:101)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26389)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:838)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3991)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2684)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2982)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2399)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9403)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1193)
	at android.view.Choreographer.doCallbacks(Choreographer.java:945)
	at android.view.Choreographer.doFrame(Choreographer.java:851)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1175)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8305)
	... 3 more
    

### Expected behavior

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:587)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/大清官 第32集【歡迎訂閱】高明、傅彪、周野芒、劉奕君等主演。該劇講述了四個男人皇帝乾隆、忠臣劉統勛、偽善寵臣納善以及滑頭福康之間的鬥智鬥法的故事。_126_kbps_M4A.mp4
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
	at j$.nio.file.spi.a.x(Unknown Source:14)
	at j$.nio.file.Files.readAttributes(SourceFile:0)
	at j$.nio.file.Files.size(Unknown Source:5)
	at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(DownloadsAdapter.kt:101)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26389)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7098)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:838)
	at android.view.View.measure(View.java:26389)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3991)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2684)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2982)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2399)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9403)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1193)
	at android.view.Choreographer.doCallbacks(Choreographer.java:945)
	at android.view.Choreographer.doFrame(Choreographer.java:851)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1175)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8305)
	... 3 more
    

### Actual behavior

I found a very serious thing here, that is to say, if you click on the media library and then click on the download, it will often flash back at this time

### LibreTube version

版本：0.14.1

### Android version

Android12 Mi UI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-24 11:49
Duplicate of #3379

**Closed by Bnyro** 2023-05-24 11:49 UTC
Labels: bug
