### ISSUE TITLE
Separate the scrolling options

### ISSUE THREAD

**Issue by Dertyiula** [libre-tube/LibreTube#2133] opened 2022-11-28 14:30 UTC
### Describe your suggested feature

Separate the slider options for volume and brightness in settings, as some users may want to use one of them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-11-28 14:36
Do you mean something like #2048?

**Comment by Dertyiula** [comment] 2022-11-28 14:39
For example, the option to turn off the brightness gesture if I don't want it.I want the volume option to stay on.

**Comment by Bnyro** [comment] 2022-11-28 14:41
Then it's a dupe of #2084

**Closed by Bnyro** 2022-11-28 14:41 UTC
Labels: enhancement

**Comment by Dertyiula** [comment] 2022-11-28 14:42
![Screenshot_20221128-184155](https://user-images.githubusercontent.com/119277871/204305675-7c087fac-806c-4e80-aef3-5af0aa911a12.jpg)
