### ISSUE TITLE
Video is interrupted on orientation change

### ISSUE THREAD

**Issue by imwints** [libre-tube/LibreTube#5754] opened 2024-03-17 14:45 UTC
### Steps to reproduce

* Enable auto-rotate in app and for device
* Start video
* Rotate device

### Expected behavior

Video should play seamlessly

### Actual behavior

Video is interrupted quickly

### LibreTube version

Nightly

### Android version

14

### Other details

This is a followup of https://github.com/libre-tube/LibreTube/issues/5727. I observed this before the fixing commit as well, so this shouldn't be a regression. 

I'm sadly not at home and don't have a machine with Android Studio at hand, otherwise I would debug this properly. A quick search on the internet spits out [this reddit](https://www.reddit.com/r/androiddev/comments/3vwgg9/video_restarts_on_orientation_change_when/) post but the manifest declares the orientation config. So my guess it that it's an issue in this app and how it handles orientation changes.

Maybe you know if this is fixable at all?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-17 15:58
Duplicate of https://github.com/libre-tube/LibreTube/issues/5538.

Unfortunately, there's no better way to achieve this. I've already tried to make the transition as seamless as possible in https://github.com/libre-tube/LibreTube/pull/5635, but that's the best we can get.

When rotating the phone, we need to use a different player layout - hence we must recreate the current layout to load the landscape version when you started in portrait mode and vice versa.

That just takes some time - as things must get rendered first.

**Closed by Bnyro** 2024-03-17 15:58 UTC
Labels: bug

**Comment by imwints** [comment] 2024-03-17 16:04
Loading into fullscreen from portrait mode doesn't have this issue. Do you think it would work if the landscape mode would be disabled for small screens and rotating would launch fullscreen mode? I find landscape mode useless on my phone anyway.

**Comment by Bnyro** [comment] 2024-03-17 16:10
> Loading into fullscreen from portrait mode doesn't have this issue. Do you think it would work if the landscape mode would be disabled for small screens and rotating would launch fullscreen mode? I find landscape mode useless on my phone anyway.
>
That's already possible:

Settings -> General -> Disable auto rotation

Player -> Enable Auto fullscreen

**Comment by imwints** [comment] 2024-03-17 16:15
Ah alright, I was thinking that this would launch every new Video in fullscreen

**Comment by Pittvandewitt** [comment] 2024-07-12 14:39
> Duplicate of #5538.
> 
> Unfortunately, there's no better way to achieve this. I've already tried to make the transition as seamless as possible in #5635, but that's the best we can get.
> 
> When rotating the phone, we need to use a different player layout - hence we must recreate the current layout to load the landscape version when you started in portrait mode and vice versa.
> 
> That just takes some time - as things must get rendered first.

Buffering again doesn't happen if the exoplayer object is persisted upon orientation change, which is not the case yet. Moving it to the ViewModel and managing the object from there should fix it I think.

**Comment by Bnyro** [comment] 2024-07-12 17:52
> exoplayer object is persisted upon orientation change, which is not the case yet. 
>
That's false, it's already the case. Feel free to make a PR if you think you can improve things though.

**Comment by Pittvandewitt** [comment] 2024-07-16 07:35
> That's false, it's already the case. Feel free to make a PR if you think you can improve things though.

Here's what I mean.
By not using the exoplayer in fragment, but in the viewmodel, the media will keep playing without interrupts on orientation change. It's a quick draft and I have tested nothing but the orientation change in PlayerFragment.

[Shared_exoplayer.patch](https://github.com/user-attachments/files/16244618/Shared_exoplayer.patch)
