### ISSUE TITLE
Error in low android version.

### ISSUE THREAD

**Issue by Fertanima** [libre-tube/LibreTube#1242] opened 2022-09-09 09:37 UTC
### Steps to reproduce

1.Open the application.
2.Unfortunately the application has stopped error.
3.Can't open the app.
4.I couldn't send an error report.

### Expected behavior

There should be no error.

### Actual behavior

Can't access the app.

### LibreTube version

0.5.1

### Android version

Android 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VDavid003** [comment] 2022-09-11 12:38
As someone who recently backported this app to run on 4.4 for personal reasons, I can say that by default, lollipop support seems fine from me on an emulator.
I think providing your phone's model number and especially a logcat from when the crash happens would help the developers a lot.

**Comment by Bnyro** [comment] 2022-09-11 12:44
@VDavid003 That's cool, how did you get it working? I thought Retrofit requires SDK 21 at minimum to work 🤔

**Comment by VDavid003** [comment] 2022-09-11 13:03
@Bnyro 
> @VDavid003 That's cool, how did you get it working? I thought Retrofit requires SDK 21 at minimum to work 🤔

It needed lots of work actually, but interestingly I left retrofit as is and it worked!
I did downgrade Coil to 1.4.0, modified 3 lines in exoplayer code to work properly on 4.4, had to disable multidex and desugaring (even with the androidx multidex support library, it was causing weird problems), had to turn on minify, so it fits in one dex, modified quite a few layout files for it to work with vector drawables (android:src -> app:srcCompat) and due to an openssl bug in 4.4, sadly I had to use play services to update the security provider (ProviderServices.installIfNeeded), so without gms it crashes when switching resolution on playback. Oh, and of course add if clauses to some api 21+ calls here and there.

**Comment by Bnyro** [comment] 2022-09-11 13:43
Oh okay, wow. That must have been a lot of work, it's a harm that so many libraries are fully or partly incompatible with SDKs below 21, but understandable at the same time since the amount of users still using it is very low.
However, glad you had success in backporting it, that's really impressive, but using NewPipe would probably have been the faster solution in this case :)

**Comment by Bnyro** [comment] 2022-09-11 15:15
I just set up an emulator with Android 5.1 and it works perfectly fine, therefore I'll close the issue due to it not being reproducible. Feel free to send any error logs here, but it's most likely a device specific issue.

**Closed by Bnyro** 2022-09-11 15:15 UTC
Labels: bug
