### ISSUE TITLE
SponsorBlock not working at all

### ISSUE THREAD

**Issue by killqbit** [libre-tube/LibreTube#3322] opened 2023-03-17 22:35 UTC
### Steps to reproduce

1. Enable all Sponsorblock related options in settings
2. Open a video with sponsorblock segments
3. Sponsorblock segments aren't present at all

### Expected behavior

Segments should appear on the selected video and be able to be skipped.

### Actual behavior

Sponsorblock isn't present at all in any way.

### LibreTube version

0.12.1

### Android version

Android 10

### Other details

Sponsorblock works perfectly fine in other apps (NewPipe, Revanced, Youtube in any browser). Also not working at Piped.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-18 06:46
Duplicate of #3288

**Closed by Bnyro** 2023-03-18 06:46 UTC
Labels: bug
