### ISSUE TITLE
Unable to scroll up Playlist in Library

### ISSUE THREAD

**Issue by IkelAtomig** [libre-tube/LibreTube#2526] opened 2022-12-28 03:06 UTC
### Steps to reproduce

Go to 

1. Library
2. Scroll all the way down to end of the Playlist section
3. Now try scrolling up to the top of the playlists

### Expected behavior

You should be able to go to the top of the playlists

### Actual behavior

Pull to refresh is working instead.

### LibreTube version

0.9.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-28 07:18
Dupe of #2434

**Closed by Bnyro** 2022-12-28 07:19 UTC
Labels: bug
