### ISSUE TITLE
Error playing long videos.

### ISSUE THREAD

**Issue by Nizami20052022** [libre-tube/LibreTube#810] opened 2022-07-17 14:01 UTC
### Steps to reproduce

1.You played a long video.

### Expected behavior

Maybe you need to add a buffer settings feature to solve this problem.

### Actual behavior

https://user-images.githubusercontent.com/104249296/179401973-25315fb1-c759-43b1-97e5-ee8e2d9e17cf.mp4

### LibreTube version

0.3.3

### Android version

Android 11

### Other details

There was no problem with short duration videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-07-17 15:39
dupe of #231

**Closed by Bnyro** 2022-07-17 15:39 UTC
Labels: bug
