### ISSUE TITLE
The application closes when you swipe the "Download" page

### ISSUE THREAD

**Issue by Monoloshka** [libre-tube/LibreTube#4284] opened 2023-07-21 00:29 UTC
### Steps to reproduce

The application closes when you swipe the "Download" page

### Expected behavior

The app will not close when you swipe the "download" page

### Actual behavior

The application closes when you swipe the "Download" page

### LibreTube version

0.16.1

### Android version

Android 12

### Other details

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:573)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
 ... 1 more
Caused by: java.nio.file.NoSuchFileException: /storage/emulated/0/Android/data/com.github.libretube/files/audio/КРИЗИС В СТУДИЙНОЙ БАНДЕ  ЛЛН_122_kbps_WEBMA_OPUS.webm
 at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
 at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
 at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
 at j$.nio.file.spi.a.x(Unknown Source:14)
 at j$.nio.file.Files.readAttributes(SourceFile:0)
 at j$.nio.file.Files.size(Unknown Source:5)
 at com.github.libretube.ui.adapters.DownloadsAdapter.onBindViewHolder(SourceFile:293)
 at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(SourceFile:1136)
 at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(SourceFile:46)
 at androidx.recyclerview.widget.GapWorker.prefetch(SourceFile:174)
 at androidx.recyclerview.widget.GapWorker.run(SourceFile:74)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8582)
 ... 3 more

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-21 06:27
Duplicate of #3379

**Closed by Bnyro** 2023-07-21 06:27 UTC
Labels: bug
