### ISSUE TITLE
Mini player is in an unusual position.

### ISSUE THREAD

**Issue by nanedi** [libre-tube/LibreTube#3861] opened 2023-05-31 09:36 UTC
### Steps to reproduce

Mini player is in an unusual position.

### Expected behavior

Mini player should be on top of the navigation bar.

### Actual behavior

Mini player is in an unusual position.

![alt text](https://i.imgur.com/rjQ9cSn.png)

### LibreTube version

0.15.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-31 09:55
The funny thing is that the bug doesn't exist in the debug builds...

**Comment by nanedi** [comment] 2023-05-31 11:33
> @JohnBetaro I got this bug yesterday but i thought its bcos of my ROM's custom gesture as the aplha debug miniplayer was fine!

My Google Pixel and my Sony 1 IV have the same problem.

**Comment by Domefemia** [comment] 2023-05-31 19:35
I can confirm I have experienced this, and literally 5 minutes ago I have installed the new version.

It happens every time with every video I have tried so far

Phone: Poco X3 NFC
ROM: LineageOS 20
Android version: 13

**Comment by akano12** [comment] 2023-05-31 20:20
Same here,
S20 Android 13

**Comment by guiopen** [comment] 2023-05-31 20:29
Same here on stock android 11 rom

**Comment by xlash123** [comment] 2023-06-01 13:47
I'm also experiencing this issue as of v0.15.0. In the past, I've had this happen with the audio player too, but the video player one is new as of the latest version.

I'm on a OnePlus 7T running /e/OS 1.11 (Android 11).

**Comment by person10301** [comment] 2023-06-01 15:16
I see the same thing on Realme 9 pro (Android 12)

**Comment by SajalRG** [comment] 2023-06-02 04:46
Hi, I'm able to reproduce this issue by creating a local release build as well. Currently trying to root cause this issue.

**Comment by archroid** [comment] 2023-06-03 16:35
Same on A13 raw rom

**Comment by crzjp** [comment] 2023-06-04 12:44
Same here on Moto G9 Play + LineageOS A13

**Comment by Kinitsans** [comment] 2023-06-05 00:44
Same here
Realme 9i
Android 13

**Comment by SajalRG** [comment] 2023-06-05 08:31
> Hi, I'm able to reproduce this issue by creating a local release build as well. Currently trying to root cause this issue.

Hi, does the commit list in github and git log in local can differ?

I was trying to identify the culprit commit to started git reset based on this list of commmits https://github.com/libre-tube/LibreTube/compare/v0.14.1...v0.15.0

Below is the analysis so far
Latest -- issue
May 15th -- issue
May 12th -- issue
May 11th -- issue
May 10th -- commit "checkout repository before setting up java" -- issue
May 10th -- commit "Merge AGP_8.0 with upstream and fix some deprecations" -- issue
May 10th -- commit "Switch CodeQL to Java 17" -- issue
May 10th -- commit "Merge pull request #3745 from Isira-Seneviratne/Skip_stream_check" -- no issue
May 10th - commit "Fix crash when closing player due to view bindings" -- no issue
May 10th - commit "Update dependency androidx.core:core to v1.10.1" -- no issue
may 9th -- no issue

I was locally doing git  reset --hard to those commit, doing gradle sync and clean release build. But after above analysis I reached nowhere.
And now I'm even more confused because when I check my local git log, the gits are not in same order.

My doubt here is, I'm not able to understand why the git log in my local and to commit list are coming different. I don't have much github contributions so I'm not able to get this.

Below are details for reference:
### In local I'm going to specific commit and checking git log
1. Go to the commit
$ git reset --hard 248e41b4f476180e8e7a786e939b854fa7711b69
HEAD is now at 248e41b4f Switch CodeQL to Java 17

2. Check git log local
$ git log
commit 248e41b4f476180e8e7a786e939b854fa7711b69 (HEAD -> master)
Author: Bnyro <bnyro@tutanota.com>
Date:   Wed May 10 19:28:50 2023 +0200

    Switch CodeQL to Java 17

commit 3e079902d26855fe02c4786df0d08bbd98c87728
Author: Isira Seneviratne <isirasen96@gmail.com>
Date:   Thu May 4 08:14:21 2023 +0530

    Update AGP to 8.0.1.

3. In the link  https://github.com/libre-tube/LibreTube/compare/v0.14.1...v0.15.0:
<img width="1217" alt="image" src="https://github.com/libre-tube/LibreTube/assets/17106096/25c5cf85-215c-4698-aceb-2410c5b1c8e5">

Attached entire git log for reference after reset.
[gitlog.txt](https://github.com/libre-tube/LibreTube/files/11650385/gitlog.txt)

**Comment by Bnyro** [comment] 2023-06-07 12:20
So if I get it correctly from your investigation, the issue seems to have been introduced with migrating the app to AGP 8.0 and Java 17.

It's possible that commits are in a weird order if the changes were made earlier, but the pull request got merged later (e.g. after some weeks) like it was the case with the PR the commits mentioned above belong to.

I currently don't have the possibility to do it, but it might be worth trying to just move the AGP version back to 7.6 and the Java version to 11.

Thanks for your work so far though!

**Comment by FireMasterK** [comment] 2023-06-07 13:11
Tip: use git bisect the next time!

**Comment by Domefemia** [comment] 2023-06-12 07:22
I can confirm the bug is still in the app on Libretube 15.1

**Comment by akano12** [comment] 2023-06-12 08:25
> I can confirm the bug is still in the app on Libretube 15.1

It's not like the project maintainer mentioned this in the 0.15.1 changelog 😬

**Comment by SajalRG** [comment] 2023-06-14 05:26
Thanks all for your support.
Have raised a PR as not able to reproduce the issue locally.

**Comment by itsmmt305** [comment] 2023-06-14 06:21
this has always existed for the audio player but now its in the video player as well. smh. but i rlly appreciate the advancements with the download speeds. great work nevertheless.

**Closed** 2023-06-14 07:12 UTC
Labels: bug, help wanted

**Comment by devbytemehedi** [comment] 2023-06-16 14:40
### Miniplayer overlaps with UI buttons

![issue-is-this](https://github.com/libre-tube/LibreTube/assets/89072438/caefa06c-979d-477c-a599-03da42e73cde)


- LibreTube Version: **[v0.15.1](https://github.com/libre-tube/LibreTube/releases/tag/v0.15.1)**
- Android Version: **13**
- Device: **[Realme Narzo 50 Pro](https://www.devicespecifications.com/en/model/4fa25984)**

**Comment by heartlog** [comment] 2023-06-20 10:52
#dev this issue is not resolved i think
Android 13
## How this issue appear again?

1. Play video in background 
2. On ••• (more opt) select Audio played
3. Minimize it
4. Bam !! Issue appear and don't go even after app restart.

![Screenshot_20230620_161512_LibreTube](https://github.com/libre-tube/LibreTube/assets/76758776/2d735cff-ebea-4df9-8021-09e966e32ba2)

**Comment by itsmmt305** [comment] 2023-06-21 06:15
its been this way with the background player since long ago

**Comment by terminal-cs** [comment] 2023-07-04 20:08
I'm still having an issue with this on 1.15.1, why is this closed?

**Comment by akano12** [comment] 2023-07-04 23:12
> I'm still having an issue with this on 1.15.1, why is this closed?

Wait for next release.
