### ISSUE TITLE
Mark as watched

### ISSUE THREAD

**Issue by d-0l** [libre-tube/LibreTube#3005] opened 2023-02-08 21:45 UTC
### Describe your suggested feature

Add ability to mark videos as watched on the hold down menu and wherever else it makes sense to.

This would enhance the feature to hide videos in the subscription box upon watching, if for instance if they've been watched on another device/want to skip a video. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by RickyM7** [comment] 2023-02-09 03:06
Duplicate of #1077. This is a good feature, it would be great if it were implemented.

**Comment by d-0l** [comment] 2023-02-09 05:05
Oh, I didn't know how to see closed requests.  Sorry about that.

**Comment by ARBoyGo** [comment] 2023-02-09 10:24
If I watched a video on piped and when I open LibreTube I need to mark it watched, That'll be nice.

**Comment by Bnyro** [comment] 2023-02-10 12:56
> Duplicate of #1077. This is a good feature, it would be great if it were implemented.
>
It'll be re-considered as in comparison to the other issue, this one conatians a valid and understandable argument why it would be useful.

**Closed** 2023-02-10 17:10 UTC
Labels: enhancement
