### ISSUE TITLE
Allow for Last.fm/Libre.fm/Listenbrainz scrobbling apps to detect when LibreTube is playing in the background

### ISSUE THREAD

**Issue by Lazer01** [libre-tube/LibreTube#5502] opened 2024-01-16 19:33 UTC
### Describe your suggested feature

When using LibreTube to listen in the background, the content should be detected by scrobbling apps on the user's device. This doesn't mean integrating any of the scrobbling software into the LibreTube app, but only to allow LibreTube to appear as a player on the user's device, so that the scrobbling app detects the content being played. The scrobbling work is done by the scrobbler by scanning the notification of the running app (LibreTube). Since LibreTube already seems to act as a player in some form -- Pano Scrobbler at least detects it as a player -- there may be some other issue preventing the content from being scanned. Perhaps other YouTube frontends that work with this functionality, like (Re)Vanced, can be used as a reference here.

### Other details

Tried both Pano Scrobbler and Simple Scrobbler.

Only Pano Scrobbler could detect the app.
(Both couldn't detect the content.)

![Screenshot_20240116_143213_Pano Scrobbler](https://github.com/libre-tube/LibreTube/assets/65929763/c5f6e560-a258-43b8-adad-3e32eb262d1b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-01-16 21:21
What's a scrobbling app?

**Comment by Lazer01** [comment] 2024-01-16 22:11
It detects music played on the user's device and keeps a record of your listen through an outside site, most commonly Last.fm. Last.fm calls each of these listens a "scrobble", so an app that tracks these listens is a "scrobbler" or scrobbling app.

**Comment by shuvashish76** [comment] 2024-01-17 02:56
Tried with [Audile](https://f-droid.org/en/packages/com.mrsep.musicrecognizer/), works as expected.

**Comment by Lazer01** [comment] 2024-01-17 05:56
> Tried with [Audile](https://f-droid.org/en/packages/com.mrsep.musicrecognizer/), works as expected.

Sorry, but if I'm understanding correctly, this app isn't a scrobbler but a music recognition service. Also, the process I describe above involves detecting the music content through the device's notifications, not the microphone, so I don't think it applies.

**Comment by Lazer01** [comment] 2024-01-17 06:01
Edited the original request for clarity.

**Comment by Bnyro** [comment] 2024-01-17 14:12
Sorry, no plans for that.

First of all, I'd have no idea how that should work, and second it's out of scope to support scrobbling apps. 

LibreTube already is declared as a music player, which is all that's being relevant for the app from my side generally concerning that topic.

**Closed by Bnyro** 2024-01-17 14:12 UTC
Labels: enhancement

**Comment by marcdw1289** [comment] 2024-01-18 08:18
Although the issue is closed I just wanted to add that LibreTube has always showed up in Simple Scrobbler on my devices/ROMs (Android 8 to 11).
