### ISSUE TITLE
can't install - crashes pm

### ISSUE THREAD

**Issue by FoxsDenYT** [libre-tube/LibreTube#5426] opened 2024-01-03 14:39 UTC
### Steps to reproduce

Try to install it from GitHub or fdroid 

### Expected behavior

It successfully installs

### Actual behavior

Package manager crashes
See video
https://foxsden.is-a.dev/Miscellaneous-Files/screen-20240104-002915.mp4

### LibreTube version

attempting to install 0.21.0 from fdroid and github

### Android version

Google Pixel 6a, Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-01-03 16:33
Duplicate of https://github.com/libre-tube/LibreTube/issues/5406

**Closed by Bnyro** 2024-01-03 16:33 UTC
Labels: bug
