### ISSUE TITLE
Regression in auto-fullscreen behavior

### ISSUE THREAD

**Issue by omentic** [libre-tube/LibreTube#5810] opened 2024-03-26 07:08 UTC
### Steps to reproduce

1. Open a video while holding your phone vertically.
2. After the video starts playing, hold your phone horizontally. The video should switch to full screen mode.
3. Hold your phone vertically again. The video should switch back to vertical mode.
4. Hold your phone horizontally again. The video **does not** switch back to horizontal mode.

### Expected behavior

Prior to the current version of LibreTube, switching between watching a video vertically and watching a video horizontally could be done by rotating the device. In the current version of LibreTube, this may only be done **once**, upon which you need to swipe slightly down on the top of the video in vertical mode to trigger a rotation again.

### Actual behavior

This regression is new since version 0.21.1.

### LibreTube version

0.22.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2024-03-26 09:36
Duplicate of https://github.com/libre-tube/LibreTube/issues/5800

**Closed by Bnyro** 2024-03-26 09:36 UTC
Labels: bug
