### ISSUE TITLE
Better downloaded videos player interface

### ISSUE THREAD

**Issue by pawa2401** [libre-tube/LibreTube#2466] opened 2022-12-21 13:06 UTC
### Describe your suggested feature

When you play a downloaded file, you get thrown straight into a full screen player. I think downloaded files should have the same interface as normal videos, but without the download, audio and playlist button, comments, likes etc. (though audio extraction and adding offline videos to playlists could be possible with more work). This is useful for playing downloaded media in portrait and PiP.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-21 14:01
Dupe of #1467

**Closed by Bnyro** 2022-12-21 14:01 UTC
Labels: enhancement
