### ISSUE TITLE
Custom order for playlists

### ISSUE THREAD

**Issue by DecemberGiraffe** [libre-tube/LibreTube#4331] opened 2023-07-30 11:33 UTC
### Describe your suggested feature

I am interested in a custom order via drag and drop for
1. Clips within a playlist
2. Playlists from the Library tab

I see that there is an option to change the playlist order based on creation date or alphabetically as well options to change order of clips within a playlist, but would like to see a custom option as well if possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-07-30 12:41
Duplicate of #3740.
Not planned currently as it's not supported by the API.

**Closed by Bnyro** 2023-07-30 12:41 UTC
Labels: enhancement
