### ISSUE TITLE
Videos unable to play.

### ISSUE THREAD

**Issue by YawPilgrim** [libre-tube/LibreTube#568] opened 2022-06-19 13:19 UTC
### Steps to reproduce

I tried playing a new music video by drake.
1. It tries loading the video but it can't.
2. It always returns to the pause button when I tap on the play button.
3. After several taps (10-15 times) on the  play button video starts to play.

### Expected behavior

Videos are supposed to play upon a tap.

### Actual behavior

Tapping on the play button several times before video starts to play 

### LibreTube version

0.3.2

### Android version

Android 12

### Other details

![Screenshot_20220619-125611](https://user-images.githubusercontent.com/52858975/174482950-fccae186-8f14-4f31-8314-c7887f96fd58.png)
![Screenshot_20220619-125732](https://user-images.githubusercontent.com/52858975/174482951-4a46ec6e-d5f0-4ae9-9975-c0a555f88d54.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-06-21 17:29
@laur89 that's probably sth different, I think that android just freezes the app in the background/cleans the activity out of the ram. Do you have battery optimization turned off?

**Comment by archroid** [comment] 2022-06-24 11:24
Duplicate of #231

**Comment by archroid** [comment] 2022-06-24 11:25
And also try changing instance based on your location.

**Closed by archroid** 2022-06-24 11:24 UTC
Labels: bug
