### ISSUE TITLE
LibreTube does not appear in recent applications

### ISSUE THREAD

**Issue by VidalGB** [libre-tube/LibreTube#3008] opened 2023-02-09 15:48 UTC
### Steps to reproduce

1 - Open the app
2 - Close the app (press the home button)
3 - Tap the recent apps button

### Expected behavior

The application should appear among the recent applications.

### Actual behavior

The application closes by itself and is inaccessible from recent applications, only from the launcher.

### LibreTube version

v0.11.1

### Android version

Android 9 (Pie)

### Other details

Device lnfo
Manufacturer: motorola
Model: moto e(6) plus
SDK: 28
Board: p161 m
OS: Android 9
Arch: armeabi-v7a
Product: pokerp

I tested it on another device and this does not happen (Xiaomi M2007J20CG), I do not know what it is.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-02-12 08:12
Duplicate of #1970. The issue is probably device or Android version specific, since it can't be reproduced on recent devices.

**Closed by Bnyro** 2023-02-12 08:12 UTC
Labels: bug, can't reproduce
