### ISSUE TITLE
### Miniplayer overlaps with UI buttons

### ISSUE THREAD

**Issue by devbytemehedi** [libre-tube/LibreTube#3990] opened 2023-06-12 16:17 UTC
### Miniplayer overlaps with UI buttons

![issue-is-this](https://github.com/libre-tube/LibreTube/assets/89072438/ef28620f-c9fc-40d7-b0e2-2fd98b6c6229)

LibreTube Version: **v0.15.0**
Android Version: **13**
Device: **Realme Narzo 50 Pro**

_Originally posted by @devbytemehedi in https://github.com/libre-tube/LibreTube/issues/594#issuecomment-1584013643_

**Comment by Bnyro** [comment] 2023-06-12 16:18
duplicate of #3861

**Closed by Bnyro** 2023-06-12 16:18 UTC
