### ISSUE TITLE
Watch progress being displayed even though `Remember Position` is turned off.

### ISSUE THREAD

**Issue by VedxP** [libre-tube/LibreTube#2001] opened 2022-11-23 14:01 UTC
### Steps to reproduce

- Turn `Remember Position` off 
- Navigate throught tabs 
- Sometimes, videos you've watched will still show the watch progress

### Expected behavior

It should not show up when the feature is turned off, infact I never use this feature and so never turned on too :)

### Actual behavior

It still remembers the position :(

### LibreTube version

0.8.0

### Android version

Android 12

### Other details

Reference screenshots:
> ![Screenshot_20221123-185445~2](https://user-images.githubusercontent.com/87353286/203565660-99532230-3b8c-4545-9a4e-677f8696f74a.png)
---
>![Screenshot_20221123-185452](https://user-images.githubusercontent.com/87353286/203565677-239c8922-6f1a-4f2c-a150-09fbbc1fea28.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VedxP** [comment] 2022-11-23 14:23
It's probably bugged, showing up on random videos I even never watched:

> ![Screenshot_20221123-195204~2](https://user-images.githubusercontent.com/87353286/203570562-13a613b2-51ce-4697-abcc-ba366d5e83cc.png)

**Comment by Bnyro** [comment] 2022-11-23 15:29
Dupe of #1933

**Closed by Bnyro** 2022-11-23 15:29 UTC
Labels: bug
