### ISSUE TITLE
Settings to improve/change resolution of thumbnails.

### ISSUE THREAD

**Issue by BadBoy-Github** [libre-tube/LibreTube#2274] opened 2022-12-06 18:27 UTC
### Steps to reproduce

The resolution of thumbnails were not good.

### Expected behavior

The resolution of thumbnails can be changed by settings.

### Actual behavior

No actual settings to do with thumbnails.

![Screenshot_20221206-235602_LibreTube](https://user-images.githubusercontent.com/119521952/205991929-4d824a7d-8e45-447b-84e0-af05379df71a.jpg)

### LibreTube version

0.9.0

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2022-12-06 18:44
Dupe of #973

**Closed** 2022-12-06 19:00 UTC
Labels: bug
