### ISSUE TITLE
Unable to see YT subscriptions

### ISSUE THREAD

**Issue by swarnendumaiti** [libre-tube/LibreTube#1861] opened 2022-11-16 06:31 UTC
### Steps to reproduce

1. Open LibreTube 
2. Settings > Instance > Import subscriptions
3. Import YT subscriptions in ".csv" format using Google Takeout feature.
4. Go to Subscriptions Tab
5. Shows error "There is a problem with the server. Try another instance?"
6. Error Screenshot ⬇️
![Screenshot_20221115-133529](https://user-images.githubusercontent.com/86847643/202102825-e70a5b06-5ee7-49fd-bd54-51d0394d94f2.png)

### Expected behavior

Find subscriptions in subscriptions tab.

### Actual behavior

Error as per step 5 above.

Error not resolving even after trying out other different instances.

### LibreTube version

0.7.1

### Android version

Android 12

### Other details

After importing subs, I can find that the channels I've subscribed on YouTube are shown as subscribed in LibreTube as well. This means that the subscriptions have been successfully imported, but is unable to show them in the subscriptions tab on the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-16 08:47
It seems like either the instance you're using has a database issue or you have subscribed to too many channels which causes the Piped API to time out.
Feel free try the same on the instance you use via the web frontend, e.g. piped.video for pipedapi.kavin.rocks, it's most going to result in the same behavior.
Closing this as it's a server and not a client side issue!

**Closed by Bnyro** 2022-11-16 08:47 UTC
Labels: bug

**Comment by swarnendumaiti** [comment] 2022-11-16 09:47
Yeah I've over a 1500 channels subscribed and the issue exist in the web frontend as well 😄. Btw is there any workaround or can I expect any solution in the future from the server side?

**Comment by swarnendumaiti** [comment] 2022-11-16 11:08
> It's likely an instance issue, is this by any chance on kavin.rocks?

I've tried all the other instances shown in LibreTube, all show the same error.

**Comment by FireMasterK** [comment] 2022-11-16 11:20
Are you using unauthenticated subscriptions? (If so, I might know why this is happening) Could you share your subscription list here, or privately maybe? Can you also open an issue in https://github.com/TeamPiped/Piped, since its likely a backend issue.

**Comment by Bnyro** [comment] 2022-11-16 13:17
> How should I privately share my subs?
>
Via Matrix: @kavin1337:matrix.org

**Comment by swarnendumaiti** [comment] 2022-11-17 03:07
> It seems like either the instance you're using has a database issue or you have subscribed to too many channels which causes the Piped API to time out. Feel free try the same on the instance you use via the web frontend, e.g. piped.video for pipedapi.kavin.rocks, it's most going to result in the same behavior. Closing this as it's a server and not a client side issue!

The server side issue has been fixed by @FireMasterK

**Comment by leoossa** [comment] 2022-11-30 19:50
@swarnenduu can you confirm? I am still having this issue

**Comment by FireMasterK** [comment] 2022-11-30 20:56
> @swarnenduu can you confirm? I am still having this issue v. 0.8.0

This was fixed in https://github.com/TeamPiped/Piped-Backend/pull/438, can you reproduce this in the official instance?

**Comment by leoossa** [comment] 2022-12-01 12:42
@FireMasterK definitely both official instances don't work via app. As far as I remember the import via web panel does not work too.

**Comment by FireMasterK** [comment] 2022-12-01 12:44
> @FireMasterK definitely both official instances don't work via app. As far as I remember the import via web panel does not work too.

Can you share your subscriptions file here, or privately?

**Comment by leoossa** [comment] 2022-12-01 12:58
@FireMasterK please share contact details so I can reach you on priv

**Comment by swarnenduu** [comment] 2022-12-01 13:01
> > How should I privately share my subs?
> >
> Via Matrix: @kavin1337:matrix.org

@leoossa You can share him privately on Matrix.

**Comment by FireMasterK** [comment] 2022-12-01 13:04
> @FireMasterK please share contact details so I can reach you on priv

See https://github.com/TeamPiped/Piped#contact
