### ISSUE TITLE
Watched videos leave a hole in feed

### ISSUE THREAD

**Issue by SalusVF** [libre-tube/LibreTube#3120] opened 2023-02-19 09:22 UTC
### Steps to reproduce

1. Activate Advanced>Hide Watched videos from feed.
2. Set Appearance>Layout>Grid Colums to a number greater than 1.
3. Go to your feed and mark a video as watched, or watch until more than 90%.
4. Now your feed won't reorganize the non watched videos and will show holes where the watched videos were.

### Expected behavior

I would expect my feed to reorganize, at least when updating via scroll down and not show wholes on it.

### Actual behavior

Watched videos leave a hole in the feed:

![Screenshot_20230219-102049](https://user-images.githubusercontent.com/53519166/219939643-c7ab5450-9473-450c-ad09-4faf7b8ced8f.png)

### LibreTube version

0.12.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by xIUPITERx** [comment] 2023-02-19 13:30
The same thing happens in the alternative player layout.
(Uploading screenshot later, if I can reproduce it.)

**Comment by Bnyro** [comment] 2023-02-19 13:54
Duplicate of #2658

**Closed by Bnyro** 2023-02-19 13:54 UTC
Labels: bug

**Comment by SalusVF** [comment] 2023-02-19 14:35
> Duplicate of #2658

Sorry, apparently I didn't use the appropriate keywords on my search... I didn't realized that already existed. Thank you.
