### ISSUE TITLE
Add actions for playlists/bookmarks

### ISSUE THREAD

**Issue by luckkmaxx** [libre-tube/LibreTube#4400] opened 2023-08-07 17:16 UTC
### Describe your suggested feature

Thinking about my prevous opened issue, regarding music playlist that has yet started videos, I thought about adding an option for playlist when is long pressed (along side "rensme playlist" and so):

1. `Mark list as watched` / `Mark list as not watched` (this will let start all items from the begining)

Additionally: 
2. `Add list to queue`
3. `Download list`

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-09 06:12
1. Seems to be a good thing to become implemented for the current queue as it simplifies things.
2. seems reasonable as well
3. Is a duplicate of #3080

**Comment by luckkmaxx** [comment] 2023-08-09 09:08
Good!...
3. Duplicate of duplicate LOL, but I dont know if it will finally be implemented since you only mention the duplicate between both posts and close as completed.

**Comment by Bnyro** [comment] 2023-08-09 09:36
I don't have plans for this currently.

**Closed** 2023-08-09 11:06 UTC
Labels: enhancement, priority: low
