### ISSUE TITLE
Trending feed always shows

### ISSUE THREAD

**Issue by anaseig** [libre-tube/LibreTube#3197] opened 2023-02-26 08:07 UTC
### Steps to reproduce

Even when I removed the home section from Navigation bar, it always shows whenever I open the app.
It says I am on Subscription, but I am seeing Trending videos at first glance.
I have to click again on the Subscription button to get rid of it.d

### Expected behavior

Home feed/Trending videos would not show at all.
Subscription feed would show first when the app is open.

### Actual behavior

Home feed/Trending videos shows regardless of whatever tab I have selected.

### LibreTube version

0.12.0

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Elim707** [comment] 2023-02-26 08:24
I was bout to share the same problem.

**Comment by Bnyro** [comment] 2023-02-26 08:35
Duplicate of #3105, #3163, and a bunch of other issues

**Closed by Bnyro** 2023-02-26 08:35 UTC
Labels: bug
