### ISSUE TITLE
About videos

### ISSUE THREAD

**Issue by Nghia323223** [libre-tube/LibreTube#4641] opened 2023-08-27 03:57 UTC
### Steps to reproduce

Open the app
Open a video
Wait for the circle to turn
Press play.

### Expected behavior

The video should be played.

### Actual behavior

The screen was black.

### LibreTube version

0.17.1-arm64-v8a
### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-27 04:49
Duplicate of #4479

**Closed by Bnyro** 2023-08-27 04:49 UTC
Labels: bug
