### ISSUE TITLE
App Crashes When Pressing the X While the Video is Minimized

### ISSUE THREAD

**Issue by KaiserCalm** [libre-tube/LibreTube#3356] opened 2023-03-23 11:19 UTC
### Steps to reproduce

1. Play a video
2. Minimize the video by draging it down, so it looks like so:
![Screenshot_20230323-131456_LibreTube](https://user-images.githubusercontent.com/81613945/227187251-91b80a5d-4e18-47c4-89fd-8399d6d17e8e.png)
3. Press the X
4. Libretube crashes.

### Expected behavior

The app wouldn't crash, just close the video.

### Actual behavior

The app crashes.

### LibreTube version

0.12.1

### Android version

DivestOS 20.0 Android 13

### Other details

```
java.lang.IllegalStateException: Fragment's view can't be accessed. Fragment isn't added
	at by.kirich1409.viewbindingdelegate.LifecycleViewBindingProperty.getValue(ViewBindingProperty.kt:131)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue(FragmentViewBindings.kt:2)
	at by.kirich1409.viewbindingdelegate.FragmentViewBindingProperty.getValue$1(FragmentViewBindings.kt:3)
	at com.github.libretube.ui.fragments.PlayerFragment.getBinding(PlayerFragment.kt:8)
	at com.github.libretube.ui.fragments.PlayerFragment.setCurrentChapterName(PlayerFragment.kt:15)
	at com.github.libretube.ui.fragments.PlayerFragment$$ExternalSyntheticLambda20.run(R8$$SyntheticClass:13)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
    
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-23 12:29
Duplicate of #3245

**Closed by Bnyro** 2023-03-23 12:29 UTC
Labels: bug
