### ISSUE TITLE
Crash when removing a vid from playlist

### ISSUE THREAD

**Issue by d4f5409d** [libre-tube/LibreTube#2629] opened 2023-01-07 22:09 UTC
### Steps to reproduce

1. Go to playlist
2. Remove a video from the playlists

### Expected behavior

-

### Actual behavior

Crash

### LibreTube version

0.10.0

### Android version

13

### Other details

Playlists are remote-synced with Piped account on kavin.rocks instance

Crash log:
```java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.github.libretube.ui.adapters.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.kt:5)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:1157)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:59)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:54)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:825)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:79)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:64)
	at android.view.View.measure(View.java:26653)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26653)
	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1450)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.widget.ScrollView.onMeasure(ScrollView.java:462)
	at android.view.View.measure(View.java:26653)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26653)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:547)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:253)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:31)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:102)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:186)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:460)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:440)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:34)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1433)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:509)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:90)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:160)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7074)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:829)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4060)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2733)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3009)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2442)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9375)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1388)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:408)
	at android.view.Choreographer.doFrame(Choreographer.java:900)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8355)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)```
    

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-01-08 08:25
Dupe of #2601

**Closed by Bnyro** 2023-01-08 08:25 UTC
Labels: bug
