### ISSUE TITLE
App opens previously watched video on resume

### ISSUE THREAD

**Issue by gbieging** [libre-tube/LibreTube#3840] opened 2023-05-26 23:55 UTC
### Steps to reproduce

1. Use app normally
2. Do other stuff for some hours
3. Reopen app

### Expected behavior

App reopens with latest video paused if unfinished, or without video

### Actual behavior

App opens and starts playing an older already watched video, not the latest one, and always the same

### LibreTube version

0.14.1

### Android version

13

### Other details

I think the issue started after I pressed "share" on the video on another app and selected LibreTube as the target, now it almost always opens with the "shared" video.

Maybe related to #3187 ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-27 06:04
Duplicate of #3187

**Closed by Bnyro** 2023-05-27 06:04 UTC
Labels: bug
