### ISSUE TITLE
Cannot import NewPipe Subscriptions

### ISSUE THREAD

**Issue by akasaka99** [libre-tube/LibreTube#1839] opened 2022-11-13 20:47 UTC
### Steps to reproduce

The same error has already been reported on  LibreTiube sub-reddit but has not been resolved yet. And was asked to report it here.  I have checked and followed  previous recommendation https://www.reddit.com/r/Libretube/comments/x0kx8d/unable_to_import_newpipe_or_youtube_subscriptions/ 
1. Go into Subscription tab on NewPipe.
2. Export to File
3. Import File in LibreTube
4.

### Expected behavior

Import NewPipe Subscriptions to LibreTube

### Actual behavior

Getting error message: "Something went wrong" and the subscripcions are not imported

### LibreTube version

0.7.0

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-13 21:17
Duplicate of #1556, please provide some device specific information there to make it easier to reproduce as only very few devices seem to have issues.

**Closed by Bnyro** 2022-11-13 21:17 UTC
Labels: bug

**Comment by akasaka99** [comment] 2022-11-13 21:36
Samsung S10+ w/ Android 11 and LG V30 w/ Android 8 neither work.
