### ISSUE TITLE
Video locks when viewing comments

### ISSUE THREAD

**Issue by crzjp** [libre-tube/LibreTube#3334] opened 2023-03-20 16:33 UTC
### Steps to reproduce

1. Open any video
2. Open comments section
3. Try to pause, forward or minimize the video

### Expected behavior

The video accepts input, like pausing or forwarding.

### Actual behavior

The video doesn't accept inputs, staying locked. Only accepts when closing the comments section.

### LibreTube version

0.12.1

### Android version

Android 13

### Other details

I don't know if this is the stardard behavior. If it is, feel free to close the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-03-20 16:57
Duplicate of #2922

**Closed by Bnyro** 2023-03-20 16:57 UTC
Labels: bug
