### ISSUE TITLE
If could add a sound booster, it would be awesome

### ISSUE THREAD

**Issue by Official-Mlx** [libre-tube/LibreTube#4915] opened 2023-10-06 14:13 UTC
### Describe your suggested feature

if could add a sound booster like mxplayer or km player, it would be great;
It would be very convenient if there is a library or a project for it on somewhere like github …

### Other details

if could add a sound booster like mxplayer or km player, it would be great;
It would be very convenient if there is a library or a project for it on somewhere like github …

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-10-06 15:10
duplicate of #2186

**Closed by Bnyro** 2023-10-06 15:10 UTC
Labels: enhancement
