### ISSUE TITLE
[FEATURE] Personalized Feed

### ISSUE THREAD

**Issue by mistermaun98** [libre-tube/LibreTube#82] opened 2022-03-17 21:38 UTC
**Describe the feature you'd like to see added**
If possible, please add personalized video feed just like youtube

**Additional context**
When you subscribe or searching video, the app will recommending some relevant video based on what you search or subscribe

![Screenshot_20220318-043555](https://user-images.githubusercontent.com/60864939/158899178-663aae2a-ed1e-4aa4-a043-ae70547a5838.jpg)

**Comment by FireMasterK** [comment] 2022-03-17 21:47
That goes against the point of the app, this would essential require YouTube to track you.

**Comment by alefvanoon** [comment] 2022-03-19 12:27
Duplicate of #67

**Closed by alefvanoon** 2022-03-19 12:27 UTC
Labels: enhancement
