### ISSUE TITLE
Backup doesn't work on debug build. 

### ISSUE THREAD

**Issue by rozari0** [libre-tube/LibreTube#3833] opened 2023-05-25 15:39 UTC
### Steps to reproduce

1. Open app
2. Try to backup app setting for *App Backup* Section.

### Expected behavior

Should open a file manager to save backup file.

### Actual behavior

Nothing happens

### LibreTube version

0.14.1 debug (last one)

### Android version

Android 9

### Other details

I was about to backup settings so I can uninstall the current debug and check if the `PlayerNotificationManager` implementation has any issues. 
As I can not backup, I won't be able to do that now. Sorry about that. :(

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-05-25 20:23
Duplicate of #3427, still trying to figure out what's causing the issue :/

**Closed by Bnyro** 2023-05-25 20:23 UTC
Labels: bug
