### ISSUE TITLE
Support for VR & 3D videos

### ISSUE THREAD

**Issue by musabninja** [libre-tube/LibreTube#2480] opened 2022-12-22 20:01 UTC
### Describe your suggested feature

Videos with 3D or videos that support VR have the ability to work in libretube

### Other details

Ability to pan 3D video without VR
Use of phone gyroscope to view 3D

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-12-22 20:12
Dupe of #2126

**Closed** 2022-12-22 20:12 UTC
Labels: enhancement
