### ISSUE TITLE
Position reset

### ISSUE THREAD

**Issue by ghost** [libre-tube/LibreTube#2125] opened 2022-11-28 04:50 UTC
### Steps to reproduce

1.Open the video.
2.Click the button to go to the next video.
3.Then click the button to go to the previous video.
4.The video does not play from the last position.
5.It starts again.

### Expected behavior

The video should continue from the last position played.

### Actual behavior

https://user-images.githubusercontent.com/119277871/204196203-0effee3d-8bbc-456a-9e89-f4fff3f9d125.mp4

### LibreTube version

Debug

### Android version

Android 12

### Other details

![Screenshot_20221128-084615_LibreTube Debug](https://user-images.githubusercontent.com/119277871/204195987-7f121f88-67e8-437b-990d-1b47064ce2e1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2022-11-28 12:09
Dupe of #1919

**Closed** 2022-12-27 18:32 UTC
Labels: bug
