### ISSUE TITLE
App opens MiniPlayer when a YT Link is opened or Handled.

### ISSUE THREAD

**Issue by IndusAryan** [libre-tube/LibreTube#3503] opened 2023-04-08 11:40 UTC
### Steps to reproduce

Step 1 - Set LibreTube as Default Link Handler for All 4 YT Links

Step 2 - Open any YouTube VIDEO link in LibreTube  OR

Step 3 -  Share the Video Link from YT to LibreTube Through LT's Link Handler(Open With...)

### Expected behavior

Libretube should open the main Player Fragment just Like YT or NewPipe.

### Actual behavior

But When link is shared it Opens the Mini Player on the default Page you have set(Home or trending or subscriptions) and you have to swipe up the miniplayer to watch the Video.

### LibreTube version

013.1

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-04-08 12:17
Duplicate of #3260

**Closed by Bnyro** 2023-04-08 12:17 UTC
Labels: bug
