### ISSUE TITLE
Audio hangs or refuse to play after switching and playback is blocking the menu button below (UI)

### ISSUE THREAD

**Issue by unknoxx** [libre-tube/LibreTube#3931] opened 2023-06-05 03:05 UTC
### Steps to reproduce

1. Press the switch to audio
2. Player hangs doesn't play or plays after a long period of waiting
3. Video works immediately switching away from audio 

### Expected behavior

Audio should play immediately after switching but keeps hanging unless you wait for a long period before it plays automatically 

### Actual behavior

Hanging behavior due to switching from video to audio 

### LibreTube version

0.15.0

### Android version

10

### Other details

The playback is also 
![Screenshot_20230605_050247](https://github.com/libre-tube/LibreTube/assets/81586558/262a7cb4-ef2f-486b-ae36-91a18ed7d3e3)
blocking the menu section below also 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-06-05 06:07
Duplicate of #3808

**Closed by Bnyro** 2023-06-05 06:07 UTC
Labels: bug
