### ISSUE TITLE
Enhancements for "DeArrow" Option

### ISSUE THREAD

**Issue by akashsriramganapathy** [libre-tube/LibreTube#5747] opened 2024-03-17 03:20 UTC
### Overview:
The "DeArrow" feature, while appreciated, could benefit from additional functionalities to offer users greater flexibility and customization options.

### Proposed Enhancements:
1. **Random Timestamp Selection:**
   - **Description:** Introduce the ability to select a random timestamp if a thumbnail is unavailable.
   - **Benefits:** Enhances user options and improves user experience when dealing with missing thumbnails.

2. **Userid Contribution:**
   - **Description:** Allow users to contribute to "DeArrow" using a userid, similar to the SponsorBlock implementation.
   - **Benefits:** Increases user engagement, provides a sense of ownership, and enhances the feature's functionality.

### Implementation Suggestions:
- Consider integrating a user-friendly interface for selecting random timestamps.
- Implement a system to track and credit user contributions through userids.
- Conduct user testing to ensure the new functionalities align with user expectations and needs.

### Impact:
These enhancements aim to elevate the "DeArrow" feature, making it more versatile and engaging for users. By incorporating these suggestions, the feature can offer a more personalized and interactive experience within the nightly build on GitHub.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by akano12** [comment] 2024-03-18 09:07
Just my own humble view on this, LibreTube is supposed to be an open source front end alternative to YouTube, this feature (in addition to the contribute to spobsorblock), i believe they fall outside the scope of this project.

But it's still up to the maintainers to decide,best of luck.

**Comment by Bnyro** [comment] 2024-03-24 22:59
1. I don't really see how this is useful. Apart from that there's currently no way to get the current frame at a specific time (except if we loaded the whole video ...). And even if, that's out of scope.
2. Duplicate of https://github.com/libre-tube/LibreTube/issues/5739

**Closed by Bnyro** 2024-03-24 22:59 UTC
Labels: enhancement, priority: low, wontfix
